Repository EddieHubCommunity/BioDrop, pull requests merged in 2021-10, with the labels that each got.

#375 fix: Update my data
  public/data/roshanmhatre.json
Labels: ✍ chore: profile addition

#350 adding my profile in eddie community
  public/data/sunil_joshi.json
Labels: ✍ chore: profile addition

#329 Added Praveen's details.
  public/data/praveenscience.json
Labels: ✍ chore: profile addition

#331 feat: more links
  src/Components/Links.js
Labels: ⭐ goal: addition, 🕹 aspect: interface

#344 Add Atharva Shirdhankar to the list
  public/data/StarTrooper08.json
Labels: ✍ chore: profile addition

#334 Add kulkarnigaurav38 profile
  public/data/kulkarnigaurav38.json
Labels: ✍ chore: profile addition

#357 add ashwin to the list
  public/data/ashwin.json
Labels: ✍ chore: profile addition

#355 Added Amit Khatri profile
  public/data/aamita96.json
Labels: ✍ chore: profile addition

#363 Added back button to profile page
  package-lock.json
  package.json
  src/Components/Socials.js
Labels: Hacktoberfest, hacktoberfest-accepted

#362 Please add Pranav Singh to the list
  public/data/theBeginner86.json
Labels: ✍ chore: profile addition

#365 Added My Profile
  public/data/vishal-codes.json
Labels: ✍ chore: profile addition

#411 Adding Json file for LinkFree
  public/data/shivamshrivastava.json
Labels: ✍ chore: profile addition

#402 added my name and details to data/AsifHabib.json
  public/data/AsifHabib.json
Labels: ✍ chore: profile addition

#413 Added my JSON file
  public/data/RakshitGupta621.json
Labels: ✍ chore: profile addition

#410 Adding member JSON data
  public/data/bamblebam.json
Labels: ✍ chore: profile addition

#451 Create subhamengine.json
  public/data/subhamengine.json
Labels: ✍ chore: profile addition

#438 First commit for Linktree
  public/data/MekongDelta-mind.json
Labels: ✍ chore: profile addition

#619 fix: more consistent loading skeleton
  src/Components/Home/Home.js
  src/Components/Home/Placeholders.js
Labels: hacktoberfest-accepted
