Repository EddieHubCommunity/BioDrop, pull requests merged in 2021-12, with the labels that each got.

#754 fix: blog post button hover
  src/Components/Links.js
  src/config/links.json
Labels: 🛠 goal: fix

#750 fix: improve Avneesh's profile
  public/data/Minecodes.json
  public/data/avneesh0612.json
  public/data/kingwisdom.json
Labels: ✨ goal: improvement

#758 docs: added blog links in qwe123coder's profile
  public/data/qwe123coder.json
Labels: ⭐ goal: addition

#756 fix: Add theriyazo
  public/data/theriyazo.json
Labels: ✍ chore: profile addition

#760 fix: failing ci due to auth
  .github/workflows/prettier.yml
Labels: 🛠 goal: fix

#764 chore: Add a new milestone `eddiejaoude.json`
  public/data/eddiejaoude.json
Labels: ⭐ goal: addition

#763 docs: Add gitpod tutorial gif
  README.md
Labels: ⭐ goal: addition

#759 docs(grammar): fix using grammarly
  Contributing.md
  README.md
Labels: 📄 aspect: text

#747 fix: Add Rowland Adimoha profile
  public/data/rowjay007.json
Labels: ✍ chore: profile addition

#772 fix: add Anu Wat
  public/data/taravis.json
Labels: ✍ chore: profile addition

#776 fix: add Vaibhav Upreti
  public/data/VaibhavUpreti.json
Labels: ✍ chore: profile addition

#771 fix: add Saurabh Mehta
  public/data/saurabhmehta1601.json
Labels: ✍ chore: profile addition

#781 docs: update directory path link
  README.md
Labels: 📄 aspect: text

#782 fix: remove extra backward slash #780
  README.md
Labels: 🛠 goal: fix

#774 docs: make template-y
  README.md
Labels: 📄 aspect: text

#786 docs: Capitalize `t` in the `YouTube` word in `README.md` #785
  README.md
Labels: 🛠 goal: fix, 📄 aspect: text

#789 Make C to c in the word Connects
  README.md
Labels: 📄 aspect: text

#793 fix: add Dhruva Srinivas
  public/data/carrotfarmer.json
Labels: ✍ chore: profile addition

#797 fix: add The Algorithms
  public/data/thealgorithms.json
Labels: ✍ chore: profile addition

#796 docs: replace screenshot with GIF
  README.md
Labels: 🕹 aspect: interface

#795 docs: add new icons
  README.md
Labels: 📄 aspect: text

#799 fix: add Amr Monier
  public/data/AmrMonier.json
Labels: ✍ chore: profile addition

#801 docs: update the `Available Icons` table structure
  README.md
Labels: 📄 aspect: text

#803 docs: update Hacktoberfest section to a dropdown
  README.md
Labels: 📄 aspect: text

#804 Add Tejas profile
  public/data/Tejas-Teju.json
Labels: ✍ chore: profile addition

#806 fix: add Abhinav Dubey
  public/data/ad9.json
Labels: ✍ chore: profile addition

#813 fix: add Jatin Kumar
  public/data/Jatinkumar30.json
Labels: ✍ chore: profile addition

#821 docs: add information about `type` parameter in `README.md`
  README.md
Labels: 📄 aspect: text

#827 fix: avatar
  public/data/irusha.json
Labels: 🛠 goal: fix

#831 fix: add Sagnik Sahoo
  public/data/devgossips.json
Labels: ✍ chore: profile addition

#835 fix: add TikKok icon
  src/Components/Icons/GetIcons.js
Labels: ⭐ goal: addition, 🕹 aspect: interface

#839 fix: add matthewraymond
  public/data/matthewraymond.json
Labels: ✍ chore: profile addition

#824 Number of links appear on homepage when hover
  generate.js
  src/Components/Home/Home.css
  src/Components/Home/Placeholders.js
  src/Components/Home/Users.js
  src/Components/Profile.js
Labels: 💻 aspect: code, 🕹 aspect: interface

#832 docs: improve `README.md`
  README.md
Labels: 📄 aspect: text

#843 feat: code optimization
  src/Components/Footer.js
  src/Components/Icons/GetIcons.js
  src/Components/Navbar.js
  src/Components/UserProfile/User.js
Labels: 💻 aspect: code

#846 fix: add Abdus Salam
  public/data/Abdus_Salam.json
Labels: ✍ chore: profile addition

#844 docs: update `README.md` with newly introduced icons
  README.md
Labels: 📄 aspect: text

#857 fix: add Telegram icon and its relevant color
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: 🕹 aspect: interface, 🛠 goal: fix

#850 fix: avatar aspect ratio distortion
  src/Components/Profile.css
Labels: 🕹 aspect: interface, 🛠 goal: fix

#859 fix: add Anish Lohiya to the list
  package.json
  public/data/AnishLohiya.json
Labels: ✍ chore: profile addition

#864 fix: add Aniruddha Inge
  public/data/Aniruddha-Inge.json
Labels: ✍ chore: profile addition

#869 docs: grammar fix in the `README.md` file
  README.md
Labels: 🛠 goal: fix, 📄 aspect: text

#875 fix: small typo errors in kumarsonoff3's profile
  public/data/kumarsonsoff3.json
Labels: 🛠 goal: fix

#876 fix: add Sarah Lean
  public/data/sarahlean.json
Labels: ✍ chore: profile addition

#882 fix: add lakshay-nasa
  public/data/lakshay-nasa.json
Labels: ✍ chore: profile addition

#878 chore: update profile, add few more details and links
  public/data/kumarsonsoff3.json
Labels: ⭐ goal: addition

#884 fix: add Gurjeet Singh Virdee
  public/data/gurjeetsinghvirdee.json
Labels: ✍ chore: profile addition
