Repository EddieHubCommunity/BioDrop, pull requests merged in 2021-11, with the labels that each got.

#622 Add FidalMathew.json
  public/data/FidalMathew.json
Labels: ✍ chore: profile addition

#627 Created my JSON
  public/data/abhishekY2401.json
Labels: ✍ chore: profile addition

#628 Add SyedSohan.json
  public/data/SyedSohan.json
Labels: ✍ chore: profile addition

#641 fix: add siddhi-244
  public/data/SiddhiBhanushali.json
Labels: ✍ chore: profile addition

#652 adding vignesh
  public/data/ckvignesh.json
Labels: ✍ chore: profile addition

#657 Added tanisha-gupta details
  public/data/tanishagupta1.json
Labels: ✍ chore: profile addition

#663 Added new user profile json file
  public/data/shukla007.json
Labels: ✍ chore: profile addition

#676 Add Profile RayyanRNKJ
  public/data/RayyanRNKJ.json
Labels: ✍ chore: profile addition

#677 fix: add itself13
  public/data/itself13.json
Labels: ✍ chore: profile addition

#688 fix: add Gaurav Pandey
  public/data/gaurtvin.json
Labels: ✍ chore: profile addition

#686 fix: add Priyanshu Indra
  public/data/PriyanshuIndra.json
Labels: ✍ chore: profile addition

#679 fix: add Dhananjayan's data
  public/data/dhananjayan.json
Labels: ✍ chore: profile addition

#684 fix(data): Add Zishan-7
  public/data/zishan.json
Labels: ✍ chore: profile addition

#681 fix(data): Add salmantec
  public/data/salmantec.json
Labels: ✍ chore: profile addition

#680 docs - Fix the href links and changed the fork icon
  Contributing.md
Labels: ✨ goal: improvement

#672 chore: update .gitpod.yml removing the link to the dockerfile
  .gitpod.dockerfile
  .gitpod.yml
Labels: 💬 talk: discussion

#678 updated my profile
  package-lock.json
  public/data/hareom284.json
Labels: ✨ goal: improvement

#689 Chore: Format public/data
  public/data/Alwaz.json
  public/data/AnanthaRamanathan138.json
  public/data/Ankkkitt.json
  public/data/Anushka-codergirl.json
  public/data/CodingSpecies.json
  public/data/FidalMathew.json
  public/data/HrishiKumbhar.json
  public/data/Kunal0007.json
  public/data/Omkar.json
  public/data/PriyanshuIndra.json
  public/data/RakeshPotnuru.json
  public/data/Tishasoumya-02.json
  public/data/abhishekY2401.json
  public/data/anassbouchfar.json
  public/data/ashishshaji.json
  public/data/atharvamogade.json
  public/data/avidcoder101.json
  public/data/ckvignesh.json
  public/data/dhananjayan.json
  public/data/fayazmiraz.json
  public/data/frankiefab100.json
  public/data/hareom284.json
  public/data/harshmathurx.json
  public/data/itsarghyadas.json
  public/data/itself13.json
  public/data/jatiinyadav.json
  public/data/jatin.json
  public/data/kodewithchirag.json
  public/data/motasimmakki.json
  public/data/nhcarrigan.json
  public/data/niteshseram.json
  public/data/ravireddy07.json
  public/data/shukla007.json
  public/data/subhamengine.json
  public/data/subhendudash02.json
  public/data/suchitragiri.json
  public/data/suubh.json
  public/data/vsnthdev.json
  public/data/yashrajthakor.json
  public/data/zishan.json
Labels: 💻 aspect: code

#692 fix: spelling errors in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🛠 goal: fix

#695 fix: Add pranay's data
  public/data/pranay.json
Labels: ✍ chore: profile addition

#694 fix: icons in all profiles
  public/data/AbhijithGanesh.json
  public/data/Anirudh.json
  public/data/MekongDelta-mind.json
  public/data/Moeen-Ul-Islam.json
  public/data/Pradumnasaraf.json
  public/data/Sachin-chaurasiya.json
  public/data/amino19.json
  public/data/anassbouchfar.json
  public/data/atharvamogade.json
  public/data/doniwirawan.json
  public/data/evavic44.json
  public/data/fayazmiraz.json
  public/data/frankiefab100.json
  public/data/harshmathurx.json
  public/data/itself13.json
  public/data/kodewithchirag.json
  public/data/krishguptadev.json
  public/data/sanjay-kv.json
  public/data/shivamshrivastava.json
  src/config/links.json
Labels: 🛠 goal: fix

#691 feat: provide more information in the `package.json` file
  package.json
Labels: ✨ goal: improvement

#698 Add khushi-linkfree
  public/data/khushisaxena.json
Labels: ✍ chore: profile addition

#699 fix: Update `link` to `globe`
  public/data/khushisaxena.json
Labels: ✨ goal: improvement

#700 fix: Use HTTPs links instead of HTTP
  Contributing.md
  package-lock.json
  public/data/Akshu-on-github.json
  public/data/Anirudh.json
  public/data/Arshdeep-0509.json
  public/data/Aryan.json
  public/data/FayasNoushad.json
  public/data/Krishnapro.json
  public/data/LakshayVardhan.json
  public/data/MukulKolpe.json
  public/data/SahityaRoy.json
  public/data/Sejal-16.json
  public/data/ShaileshKumar007.json
  public/data/SimranGupta.json
  public/data/Sin-Sumit.json
  public/data/Skyhero-admin.json
  public/data/SriSatyaT.json
  public/data/StarTrooper08.json
  public/data/ahnafahamed.json
  public/data/arnav1776.json
  public/data/ashishshaji.json
  public/data/bhargav794.json
  public/data/dhananjayan.json
  public/data/dwivedyaakash.json
  public/data/eddiejaoude.json
  public/data/felipetodev.json
  public/data/florianclanet.json
  public/data/frankiefab100.json
  public/data/harkiratsm.json
  public/data/harshmathurx.json
  public/data/iasonathanasiosgiatsios.json
  public/data/infoxicator.json
  public/data/itsarghyadas.json
  public/data/jayvirrathi.json
  public/data/kaiwalyakoparkar.json
  public/data/khan-droid.json
  public/data/krishdevdb.json
  public/data/lakshya7878.json
  public/data/merouanezouaid.json
  public/data/recognizeyourself.json
  public/data/rishabhrathore055.json
  public/data/salmantec.json
  public/data/shivamshrivastava.json
  public/data/shukla007.json
  public/data/spy-1234.json
  public/data/subhodynamics.json
  public/data/suhail34.json
  public/data/suubh.json
  public/data/technophile-04.json
  public/data/vedant-kakde.json
  public/data/verma-kunal.json
  public/data/vikasganiga05.json
  public/data/yashrajthakor.json
Labels: 🛠 goal: fix

#702 docs: add globe icon to the list of valid icons
  README.md
Labels: ⭐ goal: addition

#705 feat: add version on Navbar
  src/Components/Navbar.js
Labels: ⭐ goal: addition

#709 fix: Add My Profile to Public Directory
  public/data/Ratheshan03.json
Labels: ✍ chore: profile addition

#710 added avneesh0612
  public/data/avneesh0612.json
Labels: ✍ chore: profile addition

#703 feat(add-profile): EddieHubCommunity
  public/data/EddieHubCommunity.json
Labels: ✍ chore: profile addition

#704 feat(add-profile): web3community
  public/data/web3community.json
Labels: ✍ chore: profile addition

#707 fix: add foxy4096
  public/data/foxy4096.json
Labels: ✍ chore: profile addition

#718 docs: Removed Trailing '/'.
  .github/ISSUE_TEMPLATE/config.yml
Labels: 📄 aspect: text

#720 fix: Add App-Choreography
  public/data/App-Choreography.json
Labels: ✍ chore: profile addition

#719 docs: add missing comma
  public/data/avneesh0612.json
Labels: 🛠 goal: fix

#722 fix: add Anurag to the list
  public/data/anurag.json
Labels: ✍ chore: profile addition

#724 docs(coc): update coc email
  CODE_OF_CONDUCT.md
Labels: 🛠 goal: fix

#731 fix: username change
  public/data/Anubhavdevv.json
Labels: 🛠 goal: fix

#726 fix: rename Anirudh.json to qwe123coder.json
  public/data/qwe123coder.json
Labels: 🛠 goal: fix

#727 fix(update-profile): add blog to avneesh0612
  public/data/avneesh0612.json
Labels: ⭐ goal: addition

#742 fix: add donlouie
  public/data/donlouie.json
Labels: ✍ chore: profile addition

#741 fix: add Mohasin to the list
  public/data/Mohasin-Haque.json
Labels: ✍ chore: profile addition

#744 fix: add Minecodes.json
  public/data/Minecodes.json
Labels: ✍ chore: profile addition

#745 fix: add kingwisdom profile
  public/data/kingwisdom.json
Labels: ✍ chore: profile addition

#746 fix: add missing endline in `public/data/Mohasin-Haque.json`
  public/data/Mohasin-Haque.json
Labels: 🛠 goal: fix

#743 feat: format files and add format action
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/workflows/community.yml
  .github/workflows/prettier.yml
  .github/workflows/stale.yml
  .prettierignore
  Contributing.md
  package.json
  public/data/anurag.json
  public/data/foxy4096.json
  public/index.html
  src/Components/Home/Home.css
  src/Components/Home/Placeholders.js
  src/Components/Navbar.js
Labels: ⭐ goal: addition
