Repository EddieHubCommunity/BioDrop, pull requests merged in 2021-09, with the labels that each got.

#264 [feat/fix]: Update the Code of Conduct to the latest version
  CODE_OF_CONDUCT.md
Labels: ✨ goal: improvement

#269 feat: Use HTTPS instead of HTTP
  README.md
Labels: ✨ goal: improvement

#263 fix: formatting issues in all profiles
  public/data/Akshu-on-github.json
  public/data/Kaushik.json
  public/data/MukulKolpe.json
  public/data/Nikhil-1503.json
  public/data/ShaileshKumar007.json
  public/data/SimranGupta.json
  public/data/Sin-Sumit.json
  public/data/SriSatyaT.json
  public/data/arnav1776.json
  public/data/itsarghyadas.json
  public/data/omkar342.json
  public/data/orama254.json
  public/data/ragibajmal3.json
  public/data/roshanmhatre.json
  public/data/subhodynamics.json
  public/data/verma-kunal.json
  public/data/yashrajthakor.json
Labels: 💻 aspect: code

#234 Create ShreyaansJain.json
  public/data/ShreyaansJain.json
Labels: DATA-JSON-ADDED

#246 Add doni
  public/data/doniwirawan.json
Labels: DATA-JSON-ADDED

#280 Add rish-singhal profile
  public/data/rishabhsinghal.json
Labels: DATA-JSON-ADDED

#279 fix: Use HTTPS instead of HTTP in `data/ShreeyansJain.json`
  public/data/ShreyaansJain.json
Labels: 💻 aspect: code, 🛠 goal: fix

#285 Add Arsheel Sheikh
  public/data/arsheelsheikh.json
Labels: DATA-JSON-ADDED

#286 feat: Improve the `README.md` file
  README.md
Labels: 🕹 aspect: interface

#297 Profile amittri1025 added
  public/data/amittri1025.json
Labels: DATA-JSON-ADDED

#288 Add harshraj8843
  public/data/harshraj8843.json
Labels: DATA-JSON-ADDED

#298 Aligning paragraph to center and applied a max-width to it
  src/Components/Profile.js
  src/index.css
Labels: ⭐ goal: addition, 🕹 aspect: interface

#299 [feat/fix]: Improve the templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/pull_request.md
Labels: 🕹 aspect: interface, ✨ goal: improvement

#301 feat: add Sejal-16
  public/data/Sejal-16.json
Labels: DATA-JSON-ADDED

#307 add niteshseram's data
  public/data/niteshseram.json
Labels: DATA-JSON-ADDED

#277 Add AbhijithGanesh to the list
  public/data/AbhijithGanesh.json
Labels: DATA-JSON-ADDED

#254 feat: milestones (#252)
  README.md
  public/data/eddiejaoude.json
  src/Components/Home.css
  src/Components/Home.js
  src/Components/Links.css
  src/Components/Links.js
  src/Components/Milestone.css
  src/Components/Milestones.js
  src/Components/Profile.css
  src/Components/Profile.js
  src/Components/Socials.js
  src/index.css
Labels: ⭐ goal: addition

#202 Created Anirudh.json
  public/data/Anirudh.json
Labels: DATA-JSON-ADDED

#317 Change fork icon's color in readme
  Contributing.md
Labels: 🕹 aspect: interface, 🛠 goal: fix

#311 Add adityatheoctocatdev to the list
  public/data/adityatheoctocatdev.json
Labels: DATA-JSON-ADDED

#320 Add Yash Wankhade to the list
  public/data/yashwankhade.json
Labels: ✍ profile addition

#335 Add deephunt3r to the list
  public/data/Deephunt3r.json
Labels: ✍ profile addition

#336 Add vrajdesai78 profile
  public/data/vrajdesai78.json
Labels: ✍ profile addition

#325 Add Tisha Soumya to the list
  public/data/Tishasoumya-02.json
Labels: ✍ profile addition

#322 Add Hariket Sukeshkumar Sheth to the list
  public/data/hariketsheth.json
Labels: ✍ profile addition

#321 Add Pradyumna Gayake to the list
  public/data/prgayake.json
Labels: ✍ profile addition

#195 Update the hover effect and background colors of links
  src/Components/Links.js
  src/index.css
Labels: ⭐ goal: addition, 🕹 aspect: interface

#231 created khan-droid.json
  public/data/khan-droid.json
Labels: ✍ chore: profile addition

#330 Add Subhadip Das to the list
  public/data/subhadiptech.json
Labels: ✍ chore: profile addition

#348 fix: Use HTTPS in the `README.md` file
  README.md
Labels: 🛠 goal: fix

#333 Add Bhavya Wahie to the list
  package-lock.json
  public/data/bhavyawahie.json
Labels: ✍ chore: profile addition

#337 feat: Add Panquesito7 to the list
  public/data/panquesito7.json
Labels: ✍ chore: profile addition

#347 Add Andres Bermeo to the list
  public/data/andres-bermeo.json
Labels: ✍ chore: profile addition
