Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-07, with the labels that each got.

#1420 Added Abhishikth.json file
  public/data/Abhishikth.json
Labels: ✍ chore: profile addition

#1416 creating and adding ashmudra.json
  public/data/ashmudra.json
Labels: ✍ chore: profile addition

#1414 added samikshakute.json file
  public/data/samikshakute.json
Labels: ✍ chore: profile addition

#1433 added to the file
  public/data/yogesh.json
Labels: ✍ chore: profile addition

#1434 Added profile to linkfree
  public/data/hady68.json
Labels: ✍ chore: profile addition

#1445 add Kapil Kumar
  public/data/KapilKumar.json
Labels: ✍ chore: profile addition

#1450 Add Aayush Deshmukh Profile
  public/data/aayushd18.json
Labels: ✍ chore: profile addition

#1456 profile added
  public/data/abhay-h.json
Labels: ✍ chore: profile addition

#1463 Update brianNduhiu.json
  public/data/brianNduhiu.json
Labels: 📄 aspect: text

#1462 Add ThiagoTatico Page
  public/data/ThiagoTatico.json
Labels: ✍ chore: profile addition

#1436 added ayushlohmod.json
  public/data/ayushlohmod.json
Labels: ✍ chore: profile addition

#1464 Add New Profile
  public/data/mehakagrawal.json
Labels: ✍ chore: profile addition

#1466 added aditya172926.json
  public/data/aditya172926.json
Labels: ✍ chore: profile addition

#1468 chore: add Abbey Santos profile
  public/data/AbbeyIT.json
Labels: ✍ chore: profile addition

#1336 Update README.md
  README.md
Labels: 📄 aspect: text

#1469 chore: ShreyaPrasad1209.json addition
  public/data/ShreyaPrasad1209.json
Labels: ✍ chore: profile addition

#1449 (Accessibility): Links need distiguishing
  src/Components/Home.js
Labels: 🕹 aspect: interface

#1484 Ahmed zougari
  public/data/zougari47.json
Labels: 🛠 goal: fix

#1387 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📄 aspect: text

#1476 modify amelia2802.json
  public/data/amelia2802.json
Labels: ⭐ goal: addition

#1483 Adding profile detail on LinkFree shubhamsigdar1.json
  public/data/shubhamsigdar1.json
Labels: ✍ chore: profile addition

#1489 Chore: add profile type
  public/data/Suman373.json
Labels: ✍ chore: profile addition

#1486 chore: Add ksaurabh4 profile
  public/data/ksaurabh4.json
Labels: ✍ chore: profile addition

#1304 Add my profile to LinkFree
  public/data/wendeee.json
Labels: ✍ chore: profile addition

#1490 added JoBaHP user
  public/data/JoBaHP.json
Labels: ✍ chore: profile addition

#1502 Create nayan1xyz.json
  public/data/nayan1xyz.json
Labels: ✍ chore: profile addition

#1501 Added profile for kum9748ar
  public/data/kum9748ar.json
Labels: ✍ chore: profile addition

#1503 added Niravprajapati1
  public/data/Niravprajapati1.json
Labels: ✍ chore: profile addition

#1505 Added my profile, ( leonid066 )
  public/data/leonid066.json
Labels: ✍ chore: profile addition

#1508 Added my Profile!!
  public/data/yashwanthSRIVAT.json
Labels: ✍ chore: profile addition

#1507 Add Vinitvh as my profile
  public/data/VinitHemadri.json
Labels: ✍ chore: profile addition

#1510 Add profile Maheshpatro.json
  public/data/Maheshpatro.json
Labels: ✍ chore: profile addition

#1509 made my profile for Linkfree
  public/data/itsomsarraf_.json
Labels: ✍ chore: profile addition

#1516 chore: added username scottwil
  public/data/scottWil.json
Labels: ✍ chore: profile addition

#1518 Added my profile
  public/data/Ernest2026.json
Labels: ✍ chore: profile addition

#1515 Creating my Profile in Bonganibendi.json
  public/data/Bonganibendi.json
Labels: ✍ chore: profile addition

#1520 Soham Ratnaparkhi
  public/data/SohamRatnaparkhi.json
Labels: 🛠 goal: fix

#1523 Solved a bug in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 🛠 goal: fix

#1525 feat: Add Roshan-Sharma profile
  public/data/Roshan-Sharma.json
Labels: ✍ chore: profile addition

#1506 Add my profile as Arushay
  public/data/Arushay.json
Labels: ✍ chore: profile addition

#1493 Added my profile successfully
  public/data/Davidchaudhary.json
Labels: ✍ chore: profile addition

#1521 profile correction
  public/data/khushi818.json
Labels: ✍ chore: profile addition

#1528 Add Ruthiel's profile
  public/data/ruthiel.json
Labels: ✍ chore: profile addition

#1529 Add ghorbani-mohammad profile
  public/data/ghorbani-mohammad.json
Labels: ✍ chore: profile addition

#1526 Added deborshikun.json to the list
  public/data/deborshikun.json
Labels: ✍ chore: profile addition

#1530 Added My Profile
  public/data/giovanny-martinez.json
Labels: ✍ chore: profile addition

#1531 Update my bio
  public/data/shivam-sharma7.json
Labels: ✨ goal: improvement

#1533 Add avie-dev.json
  public/data/avie-dev.json
Labels: ✍ chore: profile addition

#1535 Added Profile Obito9596
  public/data/Obito9596.json
Labels: ✍ chore: profile addition

#1532 README.md Update
  README.md
Labels: ✨ goal: improvement

#1536 Add AyshaHakeem
  public/data/AyshaHakeem.json
Labels: ✍ chore: profile addition
