Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-10, with the labels that each got.

#1831 created my profile to be added
  public/data/SanDiego2049.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM, hacktoberfest-invalid

#1832 New profile
  public/data/Deepanshu0810.json
Labels: ✍ chore: profile addition, medium, LGTM, hacktoberfest-invalid

#1833 Add AHTHneeuhl
  public/data/AHTHneeuhl.json
Labels: ✍ chore: profile addition, large, LGTM, hacktoberfest-invalid

#1836 Create money8203.json profile page
  public/data/money8203.json
Labels: invalid, ✍ chore: profile addition, small, medium, LGTM

#1853 Create mayo7e.json profile
  public/data/mayo7e.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1841 Bhavsagar json profile page.
  public/data/itsbhavsagar.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1843 Update Srinika99.json
  public/data/Srinika99.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1844 Updated avie-dev json profile
  public/data/avie-dev.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1842 Update changes - Linkfree
  public/data/Anushka-codergirl.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#1859 chore: add behance to vczb
  public/data/vczb.json
Labels: ⭐ goal: addition, invalid, small, LGTM

#1860 Create adityasp1.json profile
  public/data/adityasp1.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1861 chore: update eddiejaoude links
  public/data/eddiejaoude.json
Labels: ⭐ goal: addition, invalid, medium, LGTM

#1851 Added milestones to my profile
  public/data/devmukhtarr.json
Labels: ⭐ goal: addition, invalid, ✍ chore: profile addition, medium

#1858 Create Collins-Omariba.json
  public/data/Collins-Omariba.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1848 fix: improved the `.dockerignore`
  .dockerignore
Labels: small

#1870 add nicoleww.json to public/data
  public/data/nicoleww.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1869 Update my bio.
  public/data/shivam-sharma7.json
Labels: ✨ goal: improvement, invalid, small, LGTM

#1868 chore: add new profile vinyldavyl.json
  public/data/vinyldavyl.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers

#1873 my first opensource code pr
  public/data/favalcodes.json
Labels: invalid, ✍ chore: profile addition, large

#1880 Add Profile kartikmehta8
  public/data/kartikmehta8.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#1876 created shahid.json
  public/data/shahid.json
Labels: invalid, ✍ chore: profile addition, medium

#1878 Added Amad3eu profile 😁😁😁
  public/data/Amad3eu.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1875 added RedHeadphone Profile
  public/data/RedHeadphone.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#1872 vivekpal1
  public/data/vivekpal1.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1826 Added profile
  public/data/kayjilesen.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#1896 adding name to contribution list
  public/data/KyngCoder.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1895 Add user profile Abayomi Ogunnusi
  public/data/drsimplegraffiti.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1894 Create Stevecmd.json
  public/data/Stevecmd.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1890 Bug 1324 graduation hat icon missing a hyphen
  icons.md
  src/Components/Icons/GetIcons.js
Labels: 💻 aspect: code, 🛠 goal: fix, small, waiting-for-reviewers

#1892 Add My Profile: Ayush-Kanduri.json
  public/data/Ayush-Kanduri.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1898 Create aryanbabber.json profile page
  public/data/aryanbabber.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers

#1899 Ali reza
  public/data/AliReza1083.json
Labels: ✨ goal: improvement, invalid, small, waiting-for-reviewers, LGTM

#1891 Randyh0120
  public/data/randyh0120.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#1893 [DOCS]
  README.md
  docs/contributing/CONTRIBUTING.md
Labels: small

#1904 Added new profile
  public/data/virtual-designer.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1900 added link tree
  public/data/aladdin.json
Labels: invalid, ✍ chore: profile addition, large

#1879 AddProfile
  public/data/irfanariyaz.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1905 added crazydevlegend
  public/data/crazydevlegend.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1909 added new profile - salahawk
  public/data/salahawk.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1882 added my profile (CanisCoder)
  public/data/CanisCoder.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1903 docs: use code backticks for icon names
  icons.md
Labels: ✨ goal: improvement, 📄 aspect: text, large

#1912 addded ch-jaswanth
  public/data/ch-jaswanth.json
Labels: invalid, ✍ chore: profile addition, medium

#1864 Created the Shivam-officials.json file
  public/data/Shivam-officials.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1923 fix: GitHub award
  public/data/eddiejaoude.json
Labels: invalid, ✍ chore: profile addition, small, LGTM

#1924 fix: only publish container
  .github/workflows/deploy.yml
Labels: large

#1921 Added anish.json
  public/data/anish27.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers

#1919 Updated my profile
  public/data/palakbhawsar98.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1925 Link free contribute files
  docs/contributing/contributinghowtos.md
Labels: large

#1852 Implemented the Dark/Light-Mode feature
  package-lock.json
  package.json
  src/App.js
  src/Components/Footer.js
  src/Components/Home.js
  src/Components/Icons/GetIcons.js
  src/Components/Links.js
  src/Components/Navbar.css
  src/Components/Navbar.js
  src/Components/Search/Placeholders.js
  src/Components/Search/Search.js
  src/Components/Search/Searchbar.js
  src/Components/Search/Users.js
  src/Components/Search/filterProfileType.js
  src/ThemeContext.js
  src/index.js
Labels: ⭐ goal: addition, 🕹 aspect: interface, large, waiting-for-reviewers

#1917 Shareicons color changing fix in build (purgecss)
  purgecss.config.js
Labels: small

#1934 Create chidubem.json profile page
  public/data/chidubem.json
Labels: invalid, ✍ chore: profile addition, medium

#1867 Added border-radius and border
  src/Components/Milestone.css
  src/Components/Milestones.js
Labels: small, waiting-for-reviewers

#1941 Update chidubem.json
  public/data/chidubem.json
Labels: 🛠 goal: fix, invalid, small

#1940 Add My Profile JSON data
  public/data/aldyadk.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1877 update profile: Pranay202
  public/data/pranay202.json
Labels: ⭐ goal: addition, invalid, large, LGTM

#1939 add jadebanares
  public/data/jadebanares.json
Labels: invalid, ✍ chore: profile addition, medium

#1947 Create bugsyy157.json
  public/data/bugsyy157.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1871 Update README
  README.md
Labels: ✨ goal: improvement, 📄 aspect: text, small, waiting-for-reviewers

#1950 Sajal24 added
  public/data/Sajal24.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1961 Update chidubem.json
  public/data/chidubem.json
Labels: invalid, ✍ chore: profile addition, small

#1967 fix: footer test
  components/Footer.js
  tests/home.spec.js
Labels: medium, v2

#1966 Update Gitpod.yml for Next.js
  .gitpod.yml
  docker-compose.yml
Labels: medium, v2

#1965 Added Atharv181.json
  public/data/Atharv181.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1963 Added my profile
  public/data/neerajrathore.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1952 Add My Profile : prasundas99.json
  public/data/PrasunDas99.json
Labels: invalid, ✍ chore: profile addition, large

#1975 fix: adds docker-compose.yml
  .gitpod.yml
  docker-compose.yml
Labels: small, v2

#1978 profile: updates public/data/dunnjacoba.json Milestone
  public/data/dunnjacoba.json
Labels: invalid, ✍ chore: profile addition, small, LGTM

#1974 Profile
  public/data/edgarefigueroa.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1863 Adding my profile
  public/data/TusharAgarwal18.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1866 Adds Lucy Macartney's profile
  icons.md
  public/data/lmac-1.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#1914 [DOCS] Contributing to next js branch #1908
  README.md
  docs/contributing/contributing-to-nextJS-branch.md
Labels: large, waiting-for-reviewers

#1911 docs: add icon contribution guidelines
  docs/contributing/contributing-icons.md
Labels: ⭐ goal: addition, 📄 aspect: text, large, waiting-for-reviewers

#1979 Add data profile for Denys Lins
  public/data/denyslins.json
Labels: invalid, ✍ chore: profile addition, medium

#1977 Create Pranit-02.json
  public/data/Pranit-02.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1820 Event Section for Users
  components/events/EventPreview.js
  components/navbar/Navbar.js
  data/anirudhp26.json
  pages/events.js
Labels: large, Next JS branch, v2

#1993 Added my profile
  public/data/sinhasagar01.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1988 chore: add Franco Sánchez
  public/data/franqsanz.json
Labels: invalid, ✍ chore: profile addition, medium

#1633 Redirecting user to their socials
  components/user/UserLink.js
Labels: small, Next JS branch, v2

#1758 Created a FallbackImage component to handle broken images
  components/FallbackImage.js
  components/user/UserPreview.js
  next.config.js
  pages/[username].js
Labels: ✨ goal: improvement, 🟨 priority: medium, medium, Next JS branch, v2

#1960 Add Navbar to Storybook
  .storybook/main.js
  stories/components/navbar/Navbar.stories.js
Labels: small, v2

#1983 feat: Add Popular page to Storybook
  stories/pages/popular.stories.js
Labels: medium, v2

#1985 fix: NextJs user preview card name size
  components/user/UserPreview.js
Labels: small, v2

#2006 HimanshuSinghNegi LinkedFree profile added
  public/data/HimanshuSinghNegi.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#2005 add Rishav-12's profile to public/data directory
  public/data/Rishav-12.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#2004 Add my profile
  public/data/SebasttianDaza.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2000 Create Althaf66.json
  public/data/Althaf66.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1997 create Nitesh-thapliyal.json LinkFree profile
  public/data/Nitesh-thapliyal.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#1971 keyboard shortcut added for seachbox
  src/Components/Home.js
  src/Components/Search/Searchbar.js
Labels: large, medium, waiting-for-reviewers

#2011 Docs(update): Corrected documentation errors
  docs/contributing/contributing-icons.md
Labels: 🛠 goal: fix, 📄 aspect: text, medium, waiting-for-reviewers

#2013 [NextJS] Mongoose - change deprecated update to updateOne
  pages/api/statistics/[...data].js
  pages/api/users/[username].js
Labels: small, waiting-for-reviewers, v2

#2010 Docs(update): Edited grammatical errors in README.md
  README.md
Labels: small

#2007 [NextJS] Bump React to 18
  package-lock.json
  package.json
Labels: large, v2

#2001 fix: mobile menu open and close functionality
  components/navbar/Navbar.js
Labels: small, v2

#1845 perf: compress site
  next.config.js
Labels: small, Next JS branch, v2

#2030 chore: update profile info
  public/data/virtual-designer.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#2028 [NextJS] Change UserLink to use anchor tag instead of button
  components/user/UserLink.js
Labels: medium, waiting-for-reviewers, v2

#2036 Add my profile
  public/data/pradhyumanarora.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2035 add: syofyanzuhad-profile
  public/data/syofyanzuhad.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2041 I would like to add my profile to LinkFree
  public/data/maemreyo.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#1929 Changed Color of Links in Dark Mode
  src/Components/Home.js
Labels: medium

#2045 feat: add link to logo
  .storybook/main.js
  components/navbar/Navbar.js
  docker-compose.yml
  next.config.js
  stories/components/navbar/Navbar.stories.js
  stories/components/user/UserPreview.stories.js
Labels: large, waiting-for-reviewers, v2

#2042 [NextJS] Migrate to Next 13
  .npmrc
  components/FallbackImage.js
  components/navbar/NavLink.js
  components/navbar/Navbar.js
  components/user/UserPreview.js
  package-lock.json
  package.json
  pages/index.js
Labels: large, v2

#2054 Update Atharv181.json
  public/data/Atharv181.json
Labels: invalid, ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#2046 chore: add ikko ashimine prof.
  public/data/eltociear.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2056 Added basil's profile data
  public/data/BasilMuhammed.json
Labels: invalid, ✍ chore: profile addition, large

#2029 Changed profile name font color on hovering in Dark mode. #2027
  src/Components/Search/Search.css
Labels: small, waiting-for-reviewers

#2014 fix(#1999) : color issue in the dark mode
  src/Components/Search/Search.css
Labels: small, waiting-for-reviewers

#2053 fix(ui): removed underline from pages title
  pages/popular.js
  pages/search.js
Labels: small, v2

#2017 fix(#2016) : dropdown label accesibility issue
  src/Components/Search/filterProfileType.js
Labels: small

#2057 feat: 2nd and 3rd Playwright tests for profiles
  tests/profile.spec.js
Labels: medium, v2

#2060 NextJS Profile tests
  .gitignore
  playwright.config.js
  tests/global-setup.js
  tests/global-teardown.js
  tests/profile.spec.js
Labels: large, v2

#2061 Added my information.
  NOCODE-CHANGELOG.md
Labels: small, waiting-for-reviewers

#2059 added my profile
  public/data/The-Saras.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2058 added Linktree profile
  public/data/CBID2.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2062 Added my profile
  public/data/soumil1.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2063 Added my profile
  public/data/Arindam200.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2064 Create Profile RohithJN.json
  public/data/RohithJN.json
Labels: invalid, ✍ chore: profile addition, large, waiting-for-reviewers

#2071 open source
  public/data/Ayush-mega-coder.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2066 Create NehaPatil03.json
  public/data/NehaPatil03.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2065 Add pasindumarasinghe profile
  public/data/pasindumarasinghe.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2073 fix: footer position is changed
  components/Footer.js
  components/layouts/MultiLayout.js
Labels: small, waiting-for-reviewers, v2

#2074 Feat: link type icons
  components/Icon.js
  components/user/UserLink.js
Labels: large, v2

#2076 feat: link colors
  components/user/UserLink.js
Labels: small, v2

#2081 fix: min 3 search characters
  pages/search.js
Labels: small, v2

#2087 test for full user name
  tests/search.spec.js
Labels: small, waiting-for-reviewers, v2

#2091 Added my information
  NOCODE-CHANGELOG.md
Labels: small

#2088 add test for popular profile search
  tests/popular.spec.js
Labels: small, v2

#2090 test for navigation of popular profile.
  tests/popular.spec.js
Labels: small, medium, v2
