Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-05, with the labels that each got.

#1262 Created johan237.json file
  public/data/johan237.json
Labels: ✍ chore: profile addition

#1246 A simple gif to add profile
  README.md
Labels: 📄 aspect: text

#1265 chore: Add vczb
  public/data/vczb.json
Labels: ✍ chore: profile addition

#1260 add KosyAbone
  public/data/KosyAbone.json
Labels: ✍ chore: profile addition

#1256 Create Manuchim.json
  public/data/Manuchim.json
Labels: ✍ chore: profile addition

#1274 "Added alokVema749 in LinkFree"
  public/data/alokVerma749.json
Labels: ✍ chore: profile addition

#1270 adding a new profile
  public/data/dunyanong.json
Labels: ✍ chore: profile addition

#1261 profile link added for ihtisham
  public/data/ihtishamKhan.json
Labels: ✍ chore: profile addition

#1279 Added json file containing my details
  public/data/panam-py.json
Labels: ✍ chore: profile addition

#1282 added info
  public/data/badmus306.json
Labels: ✍ chore: profile addition

#1275 Added NodeJs & Laravel Icons
  icons.md
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: ⭐ goal: addition

#1276 added my profile
  public/data/santoshdts.json
Labels: ✍ chore: profile addition

#1283 add jhohannes profile
  public/data/JhohannesK.json
Labels: ✍ chore: profile addition

#1241 fix: update devgossips username
  public/data/heysagnik.json
Labels: 🛠 goal: fix

#1288 Davydocsurg
  public/data/davydocsurg.json
Labels: ✍ chore: profile addition

#1287 add: Akebu
  public/data/akebu6.json
Labels: ✍ chore: profile addition

#1289 chore: add samuelajala01
  public/data/samuelajala01.json
Labels: ✍ chore: profile addition

#1292 Added profile.
  public/data/prajwalborkar.json
Labels: ✍ chore: profile addition

#1268 Add abubakar
  public/data/abubakarsadiqq.json
Labels: ✍ chore: profile addition

#1293 added profile
  public/data/sachinparihar.json
Labels: ✍ chore: profile addition

#1298 Added ioanat94's profile
  public/data/ioanat94.json
Labels: ✍ chore: profile addition

#1291 fix: uneven icon size in `icons.md`
  icons.md
Labels: 🕹 aspect: interface, 🛠 goal: fix

#1299 Updated links in readme
  README.md
Labels: 📄 aspect: text

#1296 Added profile under public/data.
  public/data/revati-deshmukh.json
Labels: ✍ chore: profile addition

#1307 new profile added
  public/data/sanchitarorra.json
Labels: ✍ chore: profile addition

#1310 Added Lukasz Przybylka profile
  public/data/l-przybylka.json
Labels: ✍ chore: profile addition

#1313 add Ahmed Zougari
  public/data/zougari47.json
Labels: ✍ chore: profile addition

#1317 Added Imam Ali Mustofa Profile
  public/data/darkterminal.json
Labels: ✍ chore: profile addition

#1311 add-arth-prajapati-profile
  public/data/arth2002.json
Labels: ✍ chore: profile addition

#1316 Add data ujjwal450.json
  public/data/ujjwal450.json
Labels: ✍ chore: profile addition

#1318 chore: Add Qreamville
  public/data/Qreamville.json
Labels: ✍ chore: profile addition

#1321 Update my bio
  public/data/shivam-sharma7.json
Labels: ✨ goal: improvement

#1319 Added personal linkfree
  public/data/hasnainmakada-99.json
Labels: ✍ chore: profile addition

#1315 Add ruchiket
  public/data/ruchiket.json
Labels: ✍ chore: profile addition

#1312 Added aparna2071
  public/data/aparna2071.json
Labels: ✍ chore: profile addition

#1309 Add Shivendu-Kumar.json
  public/data/Shivendu-Kumar.json
Labels: ✍ chore: profile addition

#1327 add Stefano Frontini profile
  public/data/StefanoFrontini.json
Labels: ✍ chore: profile addition

#1335 added nagendra devara profile to link Free
  public/data/nagendradevara.json
Labels: ✍ chore: profile addition

#1332 add kalijonn profile
  public/data/kalijonn.json
Labels: ✍ chore: profile addition

#1331 add my profile
  public/data/vinay.json
Labels: ✍ chore: profile addition

#1337 Added akshatcoder-hash to the list
  public/data/akshatcoder-hash.json
Labels: ✍ chore: profile addition

#1339 add eshan-sharma.json (resolves #1338)
  public/data/eshan-sharma.json
Labels: ✍ chore: profile addition

#1345 Add my profile to LinkFree
  public/data/prasanta10.json
Labels: ✍ chore: profile addition

#1344 Update Shivendu-Kumar.json
  public/data/Shivendu-Kumar.json
Labels: 🛠 goal: fix
