Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-11, with the labels that each got.

#2075 Created my Linkfree
  public/data/sreejit-sengupto.json
Labels: invalid, ✍ chore: profile addition, medium

#2093 Added Profile on LinkFree
  public/data/omk-coder.json
Labels: ✍ chore: profile addition

#2092 Added my profile to Public/data/
  public/data/SatyasaiNandigam.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2024 add : adding profile picture in chip
  cypress/integration/search.feature
  src/Components/Search/Search.js
  src/Components/Search/Users.js
Labels: ⭐ goal: addition, 🕹 aspect: interface, large, medium

#2097 chore: remove hacktoberfest-exclude labler
  reviewpad.yml
Labels: 💻 aspect: code, ✨ goal: improvement, medium

#2096 chore: add Akshay-bendadi
  public/data/Akshay-bendadi.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2107 Main1
  public/data/Ashimdevnath.json
Labels: ✍ chore: profile addition, medium, LGTM

#2127 Ali reza
  public/data/AliReza1083.json
Labels: ✍ chore: profile addition, large, LGTM

#2126 Main2
  public/data/Akshay-bendadi.json
Labels: ✍ chore: profile addition, small, LGTM

#2124 Changed line 98.
  README.md
Labels: small, v2

#2117 Add krupalitrivedi
  public/data/krupalitrivedi.json
Labels: ✍ chore: profile addition, medium, LGTM

#2111 add vikalp-tomer
  public/data/vikalp-tomer.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2099 Create yashsharma999.json
  public/data/yashsharma999.json
Labels: invalid, ✍ chore: profile addition, medium, LGTM

#2094 Improved dark mode property of the UI
  src/Components/Search/Searchbar.js
Labels: small, waiting-for-reviewers

#2055 Added my profile on linktree
  public/data/PriyansuMaurya.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#2098 MyProfile
  public/data/Noibisjunior.json
Labels: invalid, ✍ chore: profile addition, large, LGTM

#2049 Fixed Footer component to open urls externally
  src/Components/Footer.js
Labels: small

#2051 Improved the hover UI part in Dark Mode #2027
  src/Components/Search/Search.css
Labels: small

#1474 fix : #911 Center when only one milestone
  src/Components/Milestone.css
  src/Components/Milestones.js
Labels: medium, waiting-for-reviewers

#1931 Fixing Dark mode toggle is not reachable with keyboard navigation
  src/Components/Navbar.css
  src/Components/Navbar.js
Labels: small

#1933 Made changes for better navigation inside the website
  README.md
  cypress/integration/common/actions.js
  cypress/integration/user.feature
  docs/contributing/CONTRIBUTING.md
  src/Components/Home.css
  src/Components/Home.js
Labels: large, medium

#1954 Changed color of the text on hover in dark mode
  src/Components/Search/Users.js
Labels: small

#1981 Align icons in the Home, Navbar, Footer and Search components
  src/Components/Footer.js
  src/Components/Home.js
  src/Components/Navbar.js
  src/Components/Search/Search.js
Labels: large

#1982 Increase search and profile type input width
  src/Components/Search/Searchbar.js
  src/Components/Search/Users.js
  src/Components/Search/filterProfileType.js
Labels: medium

#1986 implemented typewriter effect using typewriter-effect package
  package-lock.json
  package.json
  src/Components/Home.js
Labels: large

#1992 add: visible links
  src/Components/Home.js
Labels: 🕹 aspect: interface, ✨ goal: improvement, small, medium, kudos

#2002 Fix dark mode profile share icon
  src/Components/ShareProfile.js
Labels: small

#2020 (feat #1995) : Cross icon feature to close shareprofile popup
  src/Components/ShareProfile.css
  src/Components/ShareProfile.js
Labels: medium

#2026 Made Profile names visible on hovering in dark mode
  src/Components/Profile.css
  src/Components/Search/Search.css
  src/Components/Search/Search.js
  src/Components/Search/Users.js
Labels: small

#2039 Check Dark/Light Mode From System Settings
  src/ThemeContext.js
Labels: medium

#2040 new window feature added
  src/Components/Links.js
Labels: small

#2047 updated v5 to v6
  package.json
Labels: small, waiting-for-reviewers

#2103 Allow using the "rel" attribute for specific link types
  src/Components/Links.js
Labels: small, waiting-for-reviewers

#2110 Align icons in the home, navbar, footer and search components
  src/Components/Navbar.js
  src/Components/Search/Search.js
Labels: large, small

#2122 Hover movile fixed
  src/Components/Links.css
  src/Components/Links.js
Labels: medium

#2135 chore: markdown in my profile
  data/eddiejaoude.json
Labels: small

#2123 Updated Milestones section
  data/CBID2.json
Labels: ✍ chore: profile addition, large, v2

#2139 Update README.md
  README.md
Labels: small

#2140 Update Profile
  public/data/manq2010.json
Labels: large, waiting-for-reviewers

#2145 chore: Delete public/data directory
  public/data/manq2010.json
Labels: large

#2149 [DOCS] remove gif from README.md
  README.md
Labels: small, waiting-for-reviewers

#2153 Update Ashimdevnath.json
  data/Ashimdevnath.json
Labels: ✍ chore: profile addition, small, LGTM

#2151 FIx : User not found
  pages/search.js
Labels: large, small

#2157 Added milestones and public stats to my profile.
  data/CodingSpecies.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2164 feat: Added LinkFree-CLI support
  package-lock.json
  package.json
Labels: large, waiting-for-reviewers

#2165 Created publikphigor.json to create my LinkFree profile
  data/publikphigor.json
Labels: ✍ chore: profile addition, medium, LGTM

#2154 fix: user not found
  pages/[username].js
  pages/api/users/[username].js
  pages/search.js
  tests/profile.spec.js
Labels: large

#2161 Removed 2022 line 28.
  data/CBID2.json
Labels: ✍ chore: profile addition, small, LGTM

#2160 bio update
  public/data/Akshay-bendadi.json
Labels: medium

#2166 [fix] Update inspiration links
  README.md
Labels: small, waiting-for-reviewers

#2144 Created soumdatta81.json
  data/soumdatta81.json
Labels: ✍ chore: profile addition, medium, LGTM

#2169 Added to information to line 3.
  data/CBID2.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM, kudos

#2003 adding my profile to the public/data
  data/philling1.json
Labels: invalid, ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2158 Profile update ( Twitter & Github)
  data/abhay-h.json
Labels: 💻 aspect: code, 🛠 goal: fix, ✍ chore: profile addition, small

#2180 chore: update Panquesito7's profile
  data/panquesito7.json
Labels: ✨ goal: improvement, 📄 aspect: text, ✍ chore: profile addition, large

#2172 Fix index image stretching
  pages/index.js
Labels: medium

#2170 Added my linkfree
  data/fluentmoheshwar.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2183 Views count
  components/user/UserPreview.js
  package-lock.json
  package.json
  pages/[username].js
  pages/index.js
Labels: large

#2181 bio update Akshay-bendadi
  public/data/Akshay-bendadi.json
Labels: ✨ goal: improvement, small

#2189 Added name LinkFree to the landing page and made it more prominent
  pages/index.js
Labels: small

#2148 feat: opengraph meta data #1366
  pages/[username].js
Labels: ⭐ goal: addition, 💻 aspect: code, small

#2192 Update and rename brianNduhiu.json to Brian-Nduhiu.json
  data/Brian-Nduhiu.json
Labels: ✍ chore: profile addition, small, LGTM

#2195 Showing text, when no events available
  pages/events.js
Labels: medium

#2191 Added my .json file to /data.
  data/adityasimant.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2204 profile tag added
  README.md
  pages/[username].js
Labels: small, medium, waiting-for-reviewers

#2201 improved profile Akshay-bendadi
  public/data/Akshay-bendadi.json
Labels: small

#2211 Milestone Added
  data/Ashimdevnath.json
Labels: ✍ chore: profile addition, small, LGTM

#2210 Sajiyah-Salat
  data/Sajiyah-Salat
Labels: ✍ chore: profile addition, large

#2209 Update Akshay-bendadi.json / not able to see previous changes
  public/data/Akshay-bendadi.json
Labels: small, waiting-for-reviewers

#2196 fix: refactor search page structure
  pages/search.js
Labels: medium, waiting-for-reviewers, kudos

#2193 Add MongoDB .env error handler
  config/mongo.js
Labels: 💻 aspect: code, 🛠 goal: fix, small, waiting-for-reviewers

#2202 Add User Social Icons
  components/Icon.js
  components/user/UserLink.js
  components/user/UserMilestone.js
  components/user/UserSocials.js
  package-lock.json
  pages/[username].js
Labels: large

#2212 Update [username].js
  pages/[username].js
Labels: small, waiting-for-reviewers

#2216 profile Akshay-bendadi
  data/Akshay-bendadi.json
Labels: ✍ chore: profile addition, small, LGTM, kudos

#2217 Patch 2
  data/Ashimdevnath.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#2219 Horizontal Scroll Bar fixed #2194
  pages/index.js
Labels: small, waiting-for-reviewers

#2220 Portfolio link updated.
  data/CodingSpecies.json
Labels: ✍ chore: profile addition, small, LGTM

#2227 Update storybook example link (#2226)
  README.md
Labels: 🛠 goal: fix, 📄 aspect: text, small

#2225 Add furkanmutlu
  data/furkanmutlu.json
Labels: ✍ chore: profile addition, large, LGTM

#2205 Add Abhishek Anand profile
  data/abhirk247.json
Labels: ✍ chore: profile addition, medium, LGTM

#2228 chore: link to releases for the release badge
  README.md
Labels: ✨ goal: improvement, 📄 aspect: text, small

#2232 Updated my linkfree profile
  data/imran1509.json
Labels: ✍ chore: profile addition, medium, LGTM

#2231 docs: fix grammatical errors in `README.md`
  README.md
Labels: small

#2234 Add juliafmorgado.json
  data/juliafmorgado.json
Labels: ✍ chore: profile addition, large, LGTM

#2233 Create QR page
  package-lock.json
  package.json
  pages/[username].js
  pages/qr/[username].js
Labels: large

#2237 Add new profile: Create my data json file
  data/zittogustavo.json
Labels: ✍ chore: profile addition, large, LGTM

#2239 adding my profile to linkfree
  data/akshaykumar05.json
Labels: ✍ chore: profile addition, large

#2240 profile added
  data/joeshajan.json
Labels: ✍ chore: profile addition, medium, LGTM

#2235 feat: QR for users profiles
  .github/workflows/build.yml
  package-lock.json
  package.json
  pages/[username].js
Labels: large

#2245 refactored popular and search page
  components/user/UserCard.js
  components/user/UserPreview.js
  pages/popular.js
  pages/search.js
  stories/components/user/UserCard.stories.js
  stories/components/user/UserPreview.stories.js
Labels: large

#2236 Reposize
  README.md
Labels: small

#2247 chore: updated Pradumnasaraf's profile
  data/Pradumnasaraf.json
Labels: ✍ chore: profile addition, large, LGTM

#2246 Update juliafmorgado.json
  data/juliafmorgado.json
Labels: ✍ chore: profile addition, medium, LGTM

#2254 Update GitHub link to icon
  components/navbar/Navbar.js
  package-lock.json
Labels: medium

#2248 Added profile for mazahaca
  data/mazahaca.json
Labels: ✍ chore: profile addition, large

#2251 Replaced a lowercase letter with an uppercase letter and added a full…
  README.md
Labels: small

#2242 Update Action Dependencies to Latest Version
  .github/workflows/build.yml
  .github/workflows/community.yml
  .github/workflows/deploy.yml
  .github/workflows/kubescape.yml
  .github/workflows/prettier.yml
  .github/workflows/release.yml
  .github/workflows/storybook.yml
Labels: 💻 aspect: code, ✨ goal: improvement, 🟨 priority: medium, large, waiting-for-reviewers

#2260 added a new milestone in my Linkfree profile
  data/SaptarshiSarkar12.json
Labels: ✍ chore: profile addition, small, LGTM

#2261 Fix Playwright setup on Gitpod
  .gitpod.Dockerfile
  .gitpod.dockerfile
  .gitpod.yml
  playwright.config.js
Labels: 💻 aspect: code, 🟨 priority: medium, 🛠 goal: fix, medium, waiting-for-reviewers

#2264 doc:fixed spelling error
  README.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text, small

#2190 Github Link Opens In New Tab
  components/navbar/Navbar.js
Labels: small, waiting-for-reviewers

#2262 Add profile for shericodes
  data/shericodes.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2269 fix: load json file directly
  pages/api/users/[username].js
Labels: 💻 aspect: code, 🛠 goal: fix, medium

#2270 update profile
  data/Collins-Omariba.json
Labels: ✍ chore: profile addition, medium, LGTM

#2272 Added Mastodon icon support
  components/Icon.js
  icons.md
Labels: ⭐ goal: addition, 💻 aspect: code, 🟩 priority: low, small

#2275 Review for Eddie
  data/eddiejaoude/CBID2.json
Labels: ✍ chore: profile addition, small

#2279 [Test] Add testimonial
  data/eddiejaoude/Akshu-on-github.json
Labels: ✍ chore: profile addition, small

#2280 Create ZeeMonk-pixel.json
  data/eddiejaoude/ZeeMonk-pixel.json
Labels: ✍ chore: profile addition, small

#2285 fix: dynamic base url
  .env.example
  Dockerfile
  components/user/UserLink.js
  config/app.json
  package-lock.json
  pages/[username].js
  pages/events.js
  pages/index.js
  pages/popular.js
  pages/search.js
Labels: large

#2273 Updated my LinkFree profile
  data/akshatcoder-hash.json
Labels: ✍ chore: profile addition, large, LGTM

#2283 add help button in home page
  components/Icon.js
  pages/index.js
Labels: ⭐ goal: addition, 🟩 priority: low, 📄 aspect: text, medium

#2271 feat: testimonioal file
  CHANGELOG.md
  components/Event.js
  components/Icon.js
  components/user/UserEvents.js
  components/user/UserLinks.js
  components/user/UserMilestones.js
  components/user/UserProfile.js
  components/user/UserTabs.js
  components/user/UserTestimonials.js
  data/akshatcoder-hash.json
  data/eddiejaoude.json
  data/eddiejaoude/Akshu-on-github.json
  data/eddiejaoude/CBID2.json
  data/eddiejaoude/ZeeMonk-pixel.json
  package-lock.json
  package.json
  pages/[username].js
  pages/api/users/[username].js
  pages/events.js
  pages/index.js
  tailwind.config.js
Labels: ✍ chore: profile addition, large

#2298 chore: updated links + public stats in LinuxGamer.json
  data/LinuxGamer.json
Labels: ✍ chore: profile addition, small, LGTM
