Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-09, with the labels that each got.

#1697 Add SattyamSamania.json
  public/data/SattyamSamania.json
Labels: ✍ chore: profile addition

#1708 chore: add description to reviewpad labels
  reviewpad.yml
Labels: small, waiting-for-reviewers

#1705 test: add marcelosousa profile
  public/data/marcelosousa.json
Labels: medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1710 add my profile
  public/data/ngdream.json
Labels: medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1681 Added my profile (akshithbellare.json)
  public/data/akshithbellare.json
Labels: ✍ chore: profile addition

#1711 fix: removed enforcing lint commits
  reviewpad.yml
Labels: medium, waiting-for-reviewers

#1701 fix: update my profile
  public/data/eddiejaoude.json
Labels: small

#1709 Add profile
  public/data/VarunNarayanan.json
Labels: medium, waiting-for-reviewers, chore: profile-adition

#1696 Adding StackOverflow icon
  icons.md
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: ⭐ goal: addition, large, medium, waiting-for-reviewers

#1609 added my links
  public/data/viktorCodes.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, chore: profile-adition, LGTM

#1713 fix: run prettier for data files
  .github/workflows/prettier.yml
Labels: small, waiting-for-reviewers

#1695 feat: add linkfree-cli support
  package-lock.json
  package.json
Labels: ⭐ goal: addition, large, waiting-for-reviewers

#1694 Added my profile
  public/data/Akshat-Mishra101.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1715 fix: gh action format
  .github/workflows/prettier.yml
Labels: 🛠 goal: fix, small, waiting-for-reviewers

#1714 Added my Profile username.BoneNzy
  public/data/BoneNzy.json
Labels: large, waiting-for-reviewers, chore: profile-adition, LGTM

#1645 Create 7flash.json
  public/data/7flash.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1699 Fixing issue: [BUG] Update the Discord icon in the readme #1698
  icons.md
Labels: large, small, waiting-for-reviewers, chore: profile-adition

#1613 README.md Update
  README.md
Labels: ✨ goal: improvement, 📄 aspect: text, small, waiting-for-reviewers

#1719 Ali reza
  public/data/AliReza1083.json
Labels: 🛠 goal: fix, small, medium, waiting-for-reviewers, LGTM

#1636 Created my profile.
  public/data/OmAvhad.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, chore: profile-adition, LGTM

#1718 void-hr
  public/data/void-hr.json
Labels: medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1717 add profile Savan Sutariya
  public/data/SavanSutariya.json
Labels: medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1720 Create ankushtripathii.json
  public/data/ankushtripathii.json
Labels: medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1716 Add My Profile
  public/data/Chirag-Lal.json
Labels: medium, waiting-for-reviewers, chore: profile-adition

#1727 Create wayneomahony.json
  public/data/wayneomahony.json
Labels: medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1726 feat: added a new profile data
  public/data/Aditya-150.json
Labels: medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1722 closes #1721
  reviewpad.yml
Labels: small, waiting-for-reviewers

#1723 issue fixed
  public/data/ankushtripathii.json
Labels: ✍ chore: profile addition, small, medium, waiting-for-reviewers, chore: profile-adition, LGTM

#1729 profile-tree
  public/data/Ashish-Khanagwal.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1734 Mancoba
  public/data/manq2010.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1733 profile added
  public/data/mohanthilak.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1730 Add My Profile: ann-design-max
  public/data/ann-design-max.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers

#1725 fix: github sponsors
  public/data/eddiejaoude.json
Labels: ⭐ goal: addition, small, waiting-for-reviewers, LGTM

#1739 Added public/data/kennie-larkson.json
  public/data/kennie-larkson.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1738 my contribution in linkfree
  public/data/Ayush0054.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1740 chore: updates milestone
  public/data/dunnjacoba.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#1737 ## Created my Linkfree Profile
  public/data/izzarzn.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1741 deepanshu profile
  public/data/deepanshu1334.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1743 new user- kdpuvvadi
  public/data/kdpuvvadi.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1746 Adding my Profile to be deployed! [Maaz]
  public/data/Maaz.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers

#1744 Added sachdevlaksh.json in public data
  public/data/sachdevlaksh.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1657 modified LABEL as Docker official documentation
  Dockerfile
Labels: 💻 aspect: code, ✨ goal: improvement, small, waiting-for-reviewers

#1748 chore: add aviralsharma07
  public/data/aviralsharma07.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1747 chore: add abdullahsajid-ma
  public/data/abdullahsajid-ma.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1750 feat: added my profile
  public/data/rohitdasu.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1749 Added LinuxGamer.json
  public/data/LinuxGamer.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1753 Kinyungu added his profile
  public/data/data2kinyungu.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1752 abhishek added his linkfree
  public/data/abhishek67.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1756 Added Profile: Stevenovak123
  public/data/Stevenovak123.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1458 links property is now optional. generate.js doesn't break when links are not defined.
  generate.js
  public/data/branrm.json
  src/Components/UserProfile/ProfilePage.js
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1581 border radius and width of card changed
  src/Components/Milestone.css
Labels: 🕹 aspect: interface, ✨ goal: improvement, medium, waiting-for-reviewers

#1724 Upated community contributions
  public/data/kumar-kalyan.json
Labels: ⭐ goal: addition, small, waiting-for-reviewers, LGTM

#1760 update Rahulbaran.json
  public/data/Rahulbaran.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#1757 feat: label PR for nextjs
  reviewpad.yml
Labels: ✨ goal: improvement, medium, waiting-for-reviewers

#1762 update my twitter and blog url
  public/data/shivam-sharma7.json
Labels: 🛠 goal: fix, small, waiting-for-reviewers, LGTM

#1765 added michagodfrey.json to public data
  public/data/michagodfrey.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1767 I have added my profile
  public/data/sudeepta.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1766 Patch2
  public/data/PritamSaha7.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1769 added my profile
  public/data/Rounak-28.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1623 Add nikhil96.json
  public/data/itsmenikhill.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1777 Update linkedin username
  public/data/haldaranup.json
Labels: 🛠 goal: fix, small, waiting-for-reviewers, LGTM

#1773 docs: Improved README
  README.md
Labels: 📄 aspect: text, small, waiting-for-reviewers

#1768 new Issue
  public/data/sapencio.json
Labels: ✍ chore: profile addition, large, medium, waiting-for-reviewers, LGTM

#1782 Add ebenezer-akhonya's profile
  public/data/ebenezer-akhonya.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1781 Added json file with name
  public/data/kanishbodhwani.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1771 add ZainMhrez.json
  public/data/ZainMhrez.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#1775 Create samadpls.json
  public/data/samadpls.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1787 chore: added public/data file
  public/data/gentlegiantdev.json
Labels: ✍ chore: profile addition, large, LGTM

#1784 Adding Yohn.json
  public/data/Yohn.json
Labels: ✍ chore: profile addition, large, LGTM

#1788 Create MasterReach1.json
  public/data/MasterReach1.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1786 Closes #1785 Added Node version to readme and added nvmrc file
  .nvmrc
  README.md
Labels: ✨ goal: improvement, 🟨 priority: medium, small

#1774 Fix: share icon not aligned properly
  src/Components/Profile.js
Labels: 🕹 aspect: interface, 🛠 goal: fix, small, waiting-for-reviewers

#1790 Added RohanH
  public/data/RohanH.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#1789 Portfolio URL changed
  public/data/JoBaHP.json
Labels: ✍ chore: profile addition, large, small, LGTM

#1778 add Meyazhagan.json
  public/data/Meyazhagan.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1793 Added my details for linkfree
  public/data/kumar-rocks.json
Labels: ✍ chore: profile addition, medium, LGTM

#1797 adding my profile to the project
  public/data/neutr0n420.json
Labels: ✍ chore: profile addition, medium, LGTM

#1799 update my profile data
  public/data/itsarghyadas.json
Labels: ✨ goal: improvement, small, LGTM

#1794 Addition my profile to LinkFree
  public/data/anirudhp26.json
Labels: ✍ chore: profile addition, medium, LGTM

#1791 add shubhambaghel profile
  public/data/shubhambaghel.json
Labels: ✍ chore: profile addition, medium

#1801 add ad3rinto profile to data
  public/data/ad3rinto.json
Labels: ✍ chore: profile addition, medium, LGTM

#1779 chore: updated my profile
  public/data/eddiejaoude.json
Labels: ✨ goal: improvement, ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#1804 Changes done to add profile details in linkFree
  public/data/ShubhraSuman.json
Labels: ✍ chore: profile addition, medium, LGTM

#1805 Added my profile
  public/data/adilwahla.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#1803 adding profile to public/data
  public/data/ahmedsilat44.json
Labels: ✍ chore: profile addition, medium, LGTM

#1812 ci: exclude from hacktoberfest
  reviewpad.yml
Labels: medium

#1814 Update eddiejaoude.json
  public/data/eddiejaoude.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM, hacktoberfest-invalid

#1813 docs: highlight warnings
  README.md
Labels: small, waiting-for-reviewers

#1815 add my profile to public/data
  public/data/2brownc.json
Labels: ✍ chore: profile addition, medium, LGTM, hacktoberfest-invalid

#1809 add Khairallah AL-Awady
  public/data/KhairallahA.json
Labels: ✍ chore: profile addition, medium, LGTM

#1807 Aman git010 patch 1
  public/data/amanGit010.json
Labels: ✍ chore: profile addition, medium

#1810 Add Profile
  public/data/chints87.json
Labels: ✍ chore: profile addition, medium, LGTM

#1819 create goobric.json page
  public/data/goobric.json
Labels: ✍ chore: profile addition, medium, LGTM, hacktoberfest-invalid

#1818 add my link and bio
  public/data/arefathi.json
Labels: ✍ chore: profile addition, medium, LGTM, hacktoberfest-invalid

#1824 Adding `omdxp` profile
  public/data/omdxp.json
Labels: ✍ chore: profile addition, large, LGTM, hacktoberfest-invalid

#1825 Create Tcodes27.json profile page
  public/data/tcodes27.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM, hacktoberfest-invalid

#1823 added my profile
  public/data/raeeceip.json
Labels: ✍ chore: profile addition, large, LGTM, hacktoberfest-invalid

#1828 Added my profile
  public/data/wajid281.json
Labels: ✍ chore: profile addition, medium, LGTM, hacktoberfest-invalid

#1827 added my username
  public/data/ImKunal13z.json
Labels: ✍ chore: profile addition, medium, hacktoberfest-invalid

#1830 Adding my profile to the the public/data/
  public/data/imran1509.json
Labels: ✍ chore: profile addition, large, medium, waiting-for-reviewers, LGTM, hacktoberfest-invalid

#1822 Added mjcoder15.json in public/data folder
  public/data/mjcoder15.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, hacktoberfest-invalid

#1780 add pranay202
  public/data/pranay202.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM, hacktoberfest-invalid

#1835 chore: updated my profile
  public/data/goobric.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM, hacktoberfest-invalid

#1834 Create money8203.json
  public/data/money8203.json
Labels: ✍ chore: profile addition, medium, LGTM, hacktoberfest-invalid
