Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-02, with the labels that each got.

#1052 Added aleemaheer
  public/data/aleemaheer.json
Labels: ✍ chore: profile addition

#1050 adding my profile to LinkFree
  public/data/nurakmal920207.json
Labels: ✍ chore: profile addition

#1053 chore: add saifrahman
  public/data/saifrahman.json
Labels: ✍ chore: profile addition

#1063 added my bio into linktree
  public/data/jeremythomas.json
Labels: ✍ chore: profile addition

#1065 Added json file for yash-0025
  public/data/Yash0025.json
Labels: ✍ chore: profile addition

#1064 chore: add Mustafiz04
  public/data/Mustafiz04.json
Labels: ✍ chore: profile addition

#1066 Gitlab icon
  README.md
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: ⭐ goal: addition

#1068 remove extra lines
  README.md
Labels: ✨ goal: improvement

#1071 Capitalize file name for contributing guidelines
  CONTRIBUTING.md
Labels: 🛠 goal: fix

#1083 Added my profile details
  public/data/GautamHegde.json
Labels: ✍ chore: profile addition

#1086 Adding User
  public/data/Pritam1812.json
Labels: ✍ chore: profile addition

#1080 add : vivek-kumar-singh
  public/data/vivek.json
Labels: ✍ chore: profile addition

#1084 Update icon for gitlab on KendallDoesCoding.json
  public/data/KendallDoesCoding.json
Labels: 🛠 goal: fix

#1015 chore: update abdussalam02
  README.md
  public/data/abdussalam_02.json
Labels: ✨ goal: improvement

#1049 added new Json data
  public/data/Ugoo-Eze.json
Labels: ✍ chore: profile addition

#1089 chore: Added Darshan Vaishya
  public/data/DarshanVaishya.json
Labels: ✍ chore: profile addition

#1090 Bisesh added information
  public/data/bisesh.json
Labels: ✍ chore: profile addition

#1088 Add Nazmul Hassan
  public/data/nazmulhassan.json
Labels: ✍ chore: profile addition

#1104 Added umaresso.json file
  public/data/umaresso.json
Labels: ✍ chore: profile addition

#1095 Adding Bala Hantsi's profile
  public/data/bala-hantsi.json
Labels: ✍ chore: profile addition

#1096 Add Dmitrii Kilishek's profile
  public/data/dmitrii-kilishek.json
Labels: ✍ chore: profile addition

#1107 Make surname capital for aayush89890.json
  public/data/aayush89890.json
Labels: 🛠 goal: fix

#1117 add Massii Nechiche profile
  public/data/massii-nechiche.json
Labels: ✍ chore: profile addition

#1128 I'm viroopaksh-utrayak
  public/data/viroopaksh-utrayak.json
Labels: ✍ chore: profile addition

#1129 Add profile chinmay29hub
  public/data/chimay29hub.json
Labels: ✍ chore: profile addition

#1130 Add profile itzwow
  public/data/itzwow.json
Labels: ✍ chore: profile addition

#1131 Added profile sshiv5768
  public/data/sshiv5768.json
Labels: ✍ chore: profile addition

#1135 Create Ash-KODES.json
  public/data/Ash-KODES.json
Labels: ✍ chore: profile addition

#1136 Add my profile Hana Aliyah Mufidah
  public/data/aliyanamu.json
Labels: ✍ chore: profile addition

#1141 Add profile Sagar0-0
  public/data/Sagar0-0.json
Labels: ✍ chore: profile addition

#1134 updated the social links with personal website
  public/data/Abbhiishek.json
Labels: ⭐ goal: addition

#1143 Add personal profile - Amit
  public/data/amitturare.json
Labels: ✍ chore: profile addition

#1146 added Devkant21.json
  public/data/Devkant21.json
Labels: ✍ chore: profile addition

#1147 Added shafaq-here.json to public/data
  public/data/shafaq-here.json
Labels: ✍ chore: profile addition

#1142 added my linkfree profile links and data
  public/data/Nnadivictory25.json
Labels: ✍ chore: profile addition

#1148 chore: add Deeksha
  public/data/Deeksha1502.json
Labels: ✍ chore: profile addition

#1149 update vasantisuthar.json
  public/data/vasantisuthar.json
Labels: ⭐ goal: addition

#1133 add MY social account to Link tree
  .github/public/data/AjRadwan.json
Labels: ✍ chore: profile addition

#1154 chore: add stephanie-kuihg
  public/data/stephanie-kuihg.json
Labels: ✍ chore: profile addition

#1155 Add SECURITY.MD
  SECURITY.md
Labels: ⭐ goal: addition
