Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-12, with the labels that each got.

#2303 Update LinuxGamer.json - Mastodon link fix
  data/LinuxGamer.json
Labels: ✍ chore: profile addition, small, LGTM

#2297 Created my Profile Ansh-Rathod
  data/Ansh-Rathod.json
Labels: ✍ chore: profile addition, large, LGTM

#2306 username.json file added
  data/Shashankzz0007.json
Labels: ✍ chore: profile addition, large, LGTM

#2312 Updated Profile
  data/CodingSpecies.json
Labels: ✍ chore: profile addition, small, LGTM, kudos

#2319 rossanodan: creating profile page
  data/rossanodan.json
Labels: ✍ chore: profile addition, large, LGTM

#2313 Add RotrixLOL
  data/RotrixLOL.json
Labels: ✍ chore: profile addition, large, LGTM

#2320 chore: Add RotrixLOL
  data/RotrixLOL.json
Labels: ✍ chore: profile addition, large

#2321 ci: change the GitHub Token to PAT
  .github/workflows/prettier.yml
Labels: small

#2291 test: implement navigate to the search page
  tests/search.spec.js
Labels: small

#2324 Docs: Improve Hacktoberfest Guidelines
  README.md
Labels: small

#2290 Beta deployment
  .env.example
  Dockerfile
  components/Event.js
  components/user/UserEvents.js
  components/user/UserLink.js
  components/user/UserLinks.js
  components/user/UserMilestones.js
  components/user/UserProfile.js
  components/user/UserTabs.js
  components/user/UserTestimonials.js
  config/app.json
  data/eddiejaoude.json
  data/eddiejaoude/Akshu-on-github.json
  data/eddiejaoude/CBID2.json
  data/eddiejaoude/ZeeMonk-pixel.json
  package-lock.json
  package.json
  pages/[username].js
  pages/api/events.js
  pages/api/users/[username].js
  pages/api/users/index.js
  pages/events.js
  pages/index.js
  pages/popular.js
  pages/search.js
  tailwind.config.js
  tests/search.spec.js
Labels: ✍ chore: profile addition, large, EPIC, tests

#2327 chore: update my profile
  data/panquesito7.json
Labels: ✨ goal: improvement, 📄 aspect: text, ✍ chore: profile addition, medium

#2328 rossanodan: update website url
  data/rossanodan.json
Labels: ✍ chore: profile addition, small, LGTM

#2326 Update To Add Your Profile section
  README.md
Labels: small

#2325 Add prettier pre-commit hook
  .husky/pre-commit
  package-lock.json
  package.json
Labels: large

#2329 Create Samarth.json
  data/samarthshetty2000.json
Labels: ✍ chore: profile addition, medium, LGTM

#2339 feat: show count in tabs + hide tabs (#2334)
  components/user/UserTabs.js
  pages/[username].js
Labels: large

#2330 [data]: added mrabro profile
  data/mrabro.json
Labels: ✍ chore: profile addition, large, LGTM

#2340 test: typing 2 characters in search
  tests/search.spec.js
Labels: medium, tests

#2338 test: no search term used
  tests/search.spec.js
Labels: small, tests

#2336 feat: create Page component to unify padding and sizing of the main pages
  components/Page.js
  pages/[username].js
  pages/events.js
  pages/popular.js
  pages/search.js
Labels: large

#2343 Added Markdowns to milestones and events description
  components/Event.js
  components/user/UserMilestone.js
  data/Klaus.json
Labels: ✍ chore: profile addition, large

#2345 fix: markdown for events
  components/Event.js
  data/eddiejaoude.json
Labels: ✍ chore: profile addition, large

#2346 feat: footer improvements
  components/Footer.js
Labels: medium

#2349 update Akshay-bendadi
  data/Akshay-bendadi.json
Labels: ✍ chore: profile addition, small, LGTM

#2357 feat: social icons increment stats
  components/user/UserProfile.js
  components/user/UserSocials.js
Labels: medium

#2289 fix: removed unnecessary bytes from broken .nvmrc
  .nvmrc
Labels: 💻 aspect: code, 🛠 goal: fix, small

#2308 Fix aria-expanded
  components/navbar/Navbar.js
  pages/index.js
Labels: 💻 aspect: code, 🛠 goal: fix, small

#2344 Add testimonial addition using issues and workflows
  .github/ISSUE_TEMPLATE/testimonial.yml
  .github/workflows/deploy.yml
  .github/workflows/testimonial.yml
Labels: large

#2359 Testimonials via issues
  .github/ISSUE_TEMPLATE/testimonial.yml
  .github/workflows/deploy.yml
  .github/workflows/testimonial.yml
Labels: large

#2341 Search users by tags
  components/user/UserProfile.js
  pages/search.js
  tests/profile.spec.js
Labels: large, tests

#2365 Update bio in my profile
  data/loftwah.json
Labels: ✍ chore: profile addition, small, LGTM

#2353 Add test for search result with 3 character
  tests/search.spec.js
Labels: medium, tests

#2348 added json for profile at LinkFree
  data/diva-21.json
Labels: ✍ chore: profile addition, medium, LGTM

#2371 [ README ] Outdated Gitpod demo Removed
  README.md
Labels: small

#2354 Added johne10
  data/johne10.json
Labels: ✍ chore: profile addition, medium

#2385 feat: move testimonials data #2384
  .github/workflows/testimonial.yml
  components/user/UserMilestone.js
  data/eddiejaoude/testimonials/Akshu-on-github.json
  data/eddiejaoude/testimonials/CBID2.json
  data/eddiejaoude/testimonials/ZeeMonk-pixel.json
  data/eddiejaoude/testimonials/krupalitrivedi.json
  pages/api/users/[username].js
Labels: ✍ chore: profile addition, medium

#2387 Added my profile Aadarsh805.json
  data/Aadarsh805.json
Labels: ✍ chore: profile addition, large, LGTM

#2393 Add profile data Chimise.json
  data/Chimise.json
Labels: ✍ chore: profile addition, large, LGTM

#2395 Topic
  components/layouts/MultiLayout.js
Labels: small, waiting-for-reviewers

#2390 profile
  data/Ajiboso-Adeola.json
Labels: ✍ chore: profile addition, large, LGTM

#2399 Profile update icon fix
  data/Aadarsh805.json
Labels: ✍ chore: profile addition, small, LGTM

#2398 Added my profile
  data/rkshaw20.json
Labels: ✍ chore: profile addition, large, LGTM

#2400 Profile Updatation For LinkFree
  data/Saurav-Pant.json
Labels: ✍ chore: profile addition, medium, LGTM

#2391 Homepage statistics
  pages/api/statistics/today.js
  pages/index.js
Labels: large

#2406 fix: ignore invalid json files #2405
  pages/api/events.js
  pages/api/users/index.js
  pages/api/users/popular.js
Labels: large

#2413 Yesayajones
  data/yesayajones.json
Labels: ✍ chore: profile addition, medium, LGTM

#2403 Create my profile and added data to it for generation of linkfree link
  data/Jaideep25-tech.json
Labels: ✍ chore: profile addition, large, LGTM

#2388 Vishrut Agarwalla LinkFree
  data/vishrut19.json
Labels: ✍ chore: profile addition, large

#2410 Supraja's Contribution
  data/Manda-supraja26.json
Labels: ✍ chore: profile addition, large, LGTM

#2412 Simple cursor fix
  components/user/UserProfile.js
Labels: 💻 aspect: code, 🛠 goal: fix, small

#2415 Add lang attribute to html tag
  next.config.js
Labels: 💻 aspect: code, ✨ goal: improvement, 🟨 priority: medium, small

#2417 Jisan's Contribution
  data/Jisan-mia.json
Labels: ✍ chore: profile addition, large, LGTM

#2416 added bhattabhi013 profile
  data/bhattabhi013.json
Labels: ✍ chore: profile addition, large, LGTM

#2418 Added my LinkFree Profile💪
  data/AngelofVerdant.json
Labels: ✍ chore: profile addition, medium, LGTM

#2419 Add agung2001.json to data directory
  data/agung2001.json
Labels: ✍ chore: profile addition, large, LGTM

#2422 Eddiejaoude2 patch 1
  data/eddiejaoude2.json
Labels: ✍ chore: profile addition, medium, LGTM

#2423 data: SaraJaoude
  data/SaraJaoude.json
Labels: ✍ chore: profile addition, large, LGTM

#1916 Profile adding guide for beginners
  docs/contributing/contributing-your-profile.md
Labels: large, waiting-for-reviewers

#2263 Updated my Linkfree
  data/adityasimant.json
Labels: ✍ chore: profile addition, medium, LGTM

#2266 Add personal profile Gianluca Galota
  data/ThorOnTheRocks.json
Labels: ✍ chore: profile addition, large, LGTM

#2299 updated Stevenovak123.json
  data/Stevenovak123.json
Labels: ✍ chore: profile addition, large

#2309 recreated and added username.json in data folder
  data/Shashankzz0007.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2429 data: SaraJaoude
  data/SaraJaoude.json
Labels: ✍ chore: profile addition, medium, LGTM

#2428 added rajeshmuthusamy profile at data
  data/connectrajesh.json
Labels: ✍ chore: profile addition, medium, LGTM

#2433 chore: Remove Twitter account
  data/indigo423.json
Labels: ✍ chore: profile addition, small, LGTM

#2424 Fix text contrast ratio on UserLink
  components/user/UserLink.js
Labels: small

#2435 file added for LinkFree project
  public/samsorrahman.json
Labels: medium

#2434 created personal profile
  data/Sativarsainath-26.json
Labels: ✍ chore: profile addition, large, LGTM

#2439 added rupeshexe.json
  data/rupeshexe.json
Labels: ✍ chore: profile addition, large, LGTM

#2440 Create Abbas-Hussain-Muzammil.json
  data/Abbas-Hussain-Muzammil.json
Labels: ✍ chore: profile addition, large, LGTM

#2449 data: SaraJaoude
  data/SaraJaoude.json
Labels: ✍ chore: profile addition, small, LGTM

#2450 data: SaraJaoude
  data/SaraJaoude.json
Labels: ✍ chore: profile addition, small, LGTM

#2451 data: SaraJaoude
  data/SaraJaoude.json
Labels: ✍ chore: profile addition, medium, LGTM

#2436 Update juliafmorgado.json
  data/juliafmorgado.json
Labels: ✍ chore: profile addition, medium, LGTM

#2438 Krishna profile update
  data/Krishnapro.json
Labels: ✍ chore: profile addition, large, LGTM

#2442 Mahesh Profile Added
  data/mahesh.json
Labels: ✍ chore: profile addition, large

#2452 data: SaraJaoude
  data/SaraJaoude.json
Labels: ✍ chore: profile addition, small, LGTM

#2427 Create SamuelIgwesi.json
  data/SamuelIgwesi.json
Labels: ✍ chore: profile addition, large, LGTM

#2447 chore: Add my profile to LinkFree
  data/anurag-rajawat.json
Labels: ✍ chore: profile addition, large, LGTM

#2455 data: update my profile
  data/panquesito7.json
Labels: ✨ goal: improvement, ✍ chore: profile addition, medium

#2457 data: Add ItsPiyusha.json
  data/ItsPiyusha.json
Labels: ✍ chore: profile addition, large, LGTM

#2460 Sara jaoude patch 7
  data/eddiejaoude.json
Labels: ✍ chore: profile addition, medium

#2468 Fix QR code margin for mobile
  components/user/UserProfile.js
Labels: small

#2469 fix: strapline
  pages/index.js
Labels: small

#2462 chore: update Rishav-12's profile
  data/Rishav-12.json
Labels: ✨ goal: improvement, small, LGTM

#2473 data: md-abid-hussain
  data/md-abid-hussain.json
Labels: ✍ chore: profile addition, medium, LGTM

#2471 data: sarthakroy2002
  data/sarthakroy2002.json
Labels: ✍ chore: profile addition, large, LGTM

#2470 fix: add twitter account info for yesayajones
  data/yesayajones.json
Labels: ⭐ goal: addition, small, LGTM

#2476 Create SanskarJain007.json
  data/SanskarJain007.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2479 Update md-abid-hussain.json
  data/md-abid-hussain.json
Labels: ✍ chore: profile addition, medium, LGTM

#2481 Corrected number of ways to 4 in README.md
  README.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text, small, waiting-for-reviewers

#2483 data: Priyanshii677
  data/Priyanshii677.json
Labels: ✍ chore: profile addition, large, LGTM

#2484 data: Create sharatkatwa.json
  data/sharatkatwa.json
Labels: ✍ chore: profile addition, large, LGTM

#2486 update README.md
  README.md
Labels: small

#2485 update: sharatkatwa.json
  data/sharatkatwa.json
Labels: ✍ chore: profile addition, small, LGTM

#2490 Add GaganpreetKaurKalsi Profile
  data/GaganpreetKaurKalsi.json
Labels: ✍ chore: profile addition, large, LGTM

#2493 data:shreyasri258
  data/shreyasri258.json
Labels: ✍ chore: profile addition, medium, LGTM

#2496 fix: docs to have titles #2495
  components/Page.js
  components/layouts/DocsLayout.js
  pages/docs/advanced/single-user-mode.mdx
  pages/docs/contributing/automated-tests.mdx
  pages/docs/contributing/hacktoberfest.mdx
  pages/docs/contributing/storybook.mdx
  pages/docs/environments/github-ui.mdx
  pages/docs/environments/gitpod.mdx
  pages/docs/environments/local-development-docker-compose.mdx
  pages/docs/environments/local-development.mdx
  pages/docs/faqs.mdx
  pages/docs/full-profile-example.mdx
  pages/docs/how-to-guides/bio.mdx
  pages/docs/how-to-guides/editing.mdx
  pages/docs/how-to-guides/events.mdx
  pages/docs/how-to-guides/links.mdx
  pages/docs/how-to-guides/milestones.mdx
  pages/docs/how-to-guides/socials-shortcuts.mdx
  pages/docs/how-to-guides/statistics.mdx
  pages/docs/how-to-guides/tags.mdx
  pages/docs/how-to-guides/testimonials.mdx
  pages/docs/index.js
  pages/docs/quickstart.mdx
Labels: large

#2500 test: for docs
  pages/docs/index.js
  tests/docs/docs.spec.js
  tests/docs/quickstart.spec.js
Labels: large, tests

#2502 Updated the typo
  pages/docs/quickstart.mdx
Labels: small

#2505 Create Devvsakib.json
  data/devvsakib.json
Labels: ✍ chore: profile addition, medium, LGTM

#2509 data:tobySolutions
  data/tobySolutions.json
Labels: ✍ chore: profile addition, medium, LGTM

#2504 data: JyothiKumar03
  data/JyothiKumar03.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2499 Kartik khode
  data/kartiklk.json
Labels: ✍ chore: profile addition, large

#2512 feat: searching icons (#2472)
  components/IconCard.js
  pages/docs/index.js
  pages/docs/quickstart.mdx
  pages/icons.js
  tests/icon.spec.js
Labels: large, tests

#2480 Create profile for iamr-kumar
  data/iamr-kumar.json
Labels: ✍ chore: profile addition, large, LGTM

#2513 data:Rhythm-08
  data/Rhythm-08.json
Labels: ✍ chore: profile addition, large, LGTM

#2514 Fixed QR code mobile view issue
  components/user/UserProfile.js
Labels: small

#2506 Added aria-label
  components/navbar/Navbar.js
Labels: small, waiting-for-reviewers

#2517 fix: only run json check on data file changes
  .github/workflows/json-check.yml
Labels: 💻 aspect: code, 🟨 priority: medium, 🛠 goal: fix, small

#2518 profile addition
  data/Gauravkumar2701.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2524 data: remove a duplicate link in my profile
  data/panquesito7.json
Labels: 🛠 goal: fix, 📄 aspect: text, ✍ chore: profile addition, small

#2520 data: Skagra42
  data/Skagra42.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2510 data:amandamartin-dev
  data/amandamartin-dev.json
Labels: ✍ chore: profile addition, large, LGTM

#2516 [Fix]:Responsiveness-Event Page
  components/Event.js
Labels: large, waiting-for-reviewers

#2515 feat: improve overall docker development
  .env.docker
  Dockerfile
  config/mongo.js
  docker-compose.yml
  package.json
Labels: 💻 aspect: code, large

#2530 [add]:responsiveness-profile page
  components/user/UserProfile.js
Labels: small

#2527 feat: events key #2414
  pages/events.js
Labels: large

#2534 Added my Profile : iamrahul8.json
  data/iamrahul8.json
Labels: ✍ chore: profile addition, large, LGTM

#2533 Create iamthecloverly.json
  data/iamthecloverly.json
Labels: ✍ chore: profile addition, large, LGTM

#2503 [Updated] UserTestimonial.js | Solved Issue #2444
  components/user/UserTestimonials.js
Labels: medium

#2532 Profile Addition
  data/mohit1607.json
Labels: ✍ chore: profile addition, medium, LGTM

#2540 fix: events to have specific folder
  data/Klaus.json
  data/Klaus/events/2022-12-10-gdg-london.json
  data/eddiejaoude.json
  data/eddiejaoude/events/2022-12-09-live-stream.json
  data/eddiejaoude/events/2022-12-10-talk.json
  data/eddiejaoude/events/2023-03-10-devrelcon.json
  data/eddiejaoude/events/2023-09-18-talk-infobip.json
  pages/api/events.js
  pages/api/users/[username].js
  pages/docs/how-to-guides/events.mdx
  pages/events.js
Labels: ✍ chore: profile addition, large

#2543 [Created] data: adityassharma-ss.json
  data/adityassharma-ss.json
Labels: ✍ chore: profile addition, large, LGTM

#2546 feat: homepage features + screenshots #2544
  pages/index.js
Labels: large

#2547 data: Valentine-chinedu
  data/Valentine-chinedu.json
Labels: ✍ chore: profile addition, large, LGTM

#2545 Accessibility Cleanup
  components/Footer.js
  components/user/UserProfile.js
  components/user/UserSocials.js
  pages/docs/index.js
Labels: medium

#2550 data:uddinArsalan
  data/uddinArsalan.json
Labels: ✍ chore: profile addition, medium, LGTM

#2552 data:mpotane
  data/mpotane.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2549 mobile testimonial UI layout fix
  components/user/UserTestimonials.js
Labels: large

#2548 feat: profile events has key
  components/event/EventCard.js
  components/event/EventKey.js
  components/user/UserEvents.js
  pages/events.js
Labels: large

#2553 fix: use event propogation to stop changeTab function to reset tabs
  components/user/UserTabs.js
Labels: small

#2554 Created my data
  data/legendarykamal.json
Labels: ✍ chore: profile addition, medium, LGTM

#2551 copy to clipboard feature added
  components/ClipboardCopy.js
  package-lock.json
  package.json
  pages/docs/quickstart.mdx
Labels: large, waiting-for-reviewers

#2555 data:Kaleem-abdull
  data/Kaleem-abdull.json
Labels: ✍ chore: profile addition, large, LGTM

#2557 Kaleem abdull patch 4
  data/Kaleem-abdull.json
Labels: ✍ chore: profile addition, small, LGTM
