Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-08, with the labels that each got.

#1543 Create kartik2220.json
  public/data/kartik2220.json
Labels: ✍ chore: profile addition

#1540 added my profile `@theabhayprajapati`
  public/data/theabhayprajapati.json
Labels: ✍ chore: profile addition

#1542 add marcokumu profile
  public/data/marcokumu.json
Labels: ✍ chore: profile addition

#1553 update profile
  public/data/brysonwaisi.json
Labels: ✍ chore: profile addition

#1548 Create RajShukla1.json
  public/data/RajShukla1.json
Labels: ✍ chore: profile addition

#1550 create[data]: add tokio3012.json
  public/data/tokio3012.json
Labels: ✍ chore: profile addition

#1549 Added aaryachopkar.json
  public/data/accodes21.json
Labels: ✍ chore: profile addition

#1558 Added my personal section to the Linkfree page
  public/data/langnerdavid.json
Labels: ✍ chore: profile addition

#1554 profile added with links and milestones
  public/data/Nyadzayo.json
Labels: ✍ chore: profile addition

#1555 Abhishinde24
  public/data/abhishinde24.json
Labels: ✍ chore: profile addition

#1562 Added profile for Njong Emy
  public/data/Njong392.json
Labels: ✍ chore: profile addition

#1561 Add profile
  public/data/jaishbs.json
Labels: ✍ chore: profile addition

#1563 [fix] : change my username
  public/data/vedanshi555.json
Labels: 🛠 goal: fix

#1560 Add my profile
  public/data/ste001.json
Labels: ✍ chore: profile addition

#1565 [fix] :added missing search
  icons.md
Labels: 🛠 goal: fix

#1567 chore: Add RayanAbid.json
  public/data/RayanAbid.json
Labels: ✍ chore: profile addition

#1552 [Add] : Added Version badge and License badge
  README.md
Labels: ⭐ goal: addition, 🕹 aspect: interface

#1566 chore: add Trust Onye
  public/data/code-with-onye.json
Labels: ✍ chore: profile addition

#1573 Add Soumya
  public/data/Soumya-Kushwaha.json
Labels: ✍ chore: profile addition

#1575 chore: add zabihhaqqani.json
  public/data/zabihhaqqani.json
Labels: ✍ chore: profile addition

#1574 Add Sudhansu's data
  public/data/the-lazy-learner.json
Labels: ✍ chore: profile addition

#1576 update username of github
  public/data/kartikgajjar7.json
Labels: 🛠 goal: fix

#1582 raiyanmook27.json Added
  public/data/raiyanmook27.json
Labels: ✍ chore: profile addition

#1580 add: chandraprakash
  public/data/Chandraprakash-Darji.json
Labels: ✍ chore: profile addition

#1585 Changes
  public/data/latenighthunter.json
Labels: 🛠 goal: fix

#1586 Added My Profile json file.
  public/data/SaptarshiSarkar12.json
Labels: ✍ chore: profile addition

#1588 Aniket created profile
  public/data/Aniket1026.json
Labels: ✍ chore: profile addition

#1591 fix: Add githubarj
  public/data/githubarj.json
Labels: ✍ chore: profile addition

#1590 chore: add RealSollyM
  public/data/realsollym.json
Labels: ✍ chore: profile addition

#1598 Added my profile
  public/data/PritamSarbajna.json
Labels: ✍ chore: profile addition

#1600 Added hemantwasthere.json in 'public/data' directory
  public/data/hemantwasthere.json
Labels: ✍ chore: profile addition

#1610 Add 2802AdityA.json
  public/data/2802AdityA.json
Labels: ✍ chore: profile addition

#1607 Adds dunnjacoba.json
  public/data/dunnjacoba.json
Labels: ✍ chore: profile addition

#1621 My linkfree profile, added json file using my username
  public/data/haldaranup.json
Labels: ✍ chore: profile addition

#1618 'Adil'
  public/data/zadilkhwaja.json
Labels: ✍ chore: profile addition

#1619 Create Ali Reza
  public/data/AliReza1083.json
Labels: ✍ chore: profile addition

#1622 Add AnanjayGurjar.json
  public/data/AnanjayGurjar.json
Labels: ✍ chore: profile addition

#1620 added profile
  public/data/kapoorsaumitra.json
Labels: ✍ chore: profile addition

#1634 Added falakamin31.json
  public/data/falakamin31.json
Labels: ✍ chore: profile addition

#1628 Update README.md
  README.md
Labels: ✨ goal: improvement

#1626 Add files via upload
  public/data/akhil.json
Labels: ✍ chore: profile addition

#1584 My Name Json File added
  public/data/Ranamalsingh12.json
Labels: ✍ chore: profile addition

#1602 Updated my json profile file
  public/data/SaptarshiSarkar12.json
Labels: ✨ goal: improvement

#1627 added my profile susheel.json
  public/data/susheelpal.json
Labels: ✍ chore: profile addition

#1632 docs: migrating to nextjs notice
  README.md
Labels: ⭐ goal: addition

#1641 added my profile info to the data folder
  public/data/psypher1.json
Labels: ✍ chore: profile addition

#1635 udated changes
  public/data/kumar-kalyan.json
Labels: 🛠 goal: fix

#1637 chore: add Nonso
  public/data/Nonso.json
Labels: ✍ chore: profile addition

#1644 Added new profile shaileshparmar11.json
  public/data/ShaileshParmar11.json
Labels: ✍ chore: profile addition

#1640 add profile
  public/data/ravibabuvadde.json
Labels: ✍ chore: profile addition

#1646 Shubhcs01 profile added
  public/data/Shubhcs01.json
Labels: ✍ chore: profile addition

#1647 added profile prateek-srivastav.json
  public/data/prateek-srivastav.json
Labels: ✍ chore: profile addition

#1650 Create ayobamiseun.json
  public/data/ayobamiseun.json
Labels: ✍ chore: profile addition

#1651 Added my profile
  public/data/ChinmayMhatre.json
Labels: ✍ chore: profile addition

#1642 'Adds npm ci remove npm install, `links` README'
  README.md
Labels: ✨ goal: improvement

#1662 Added a "github" Profile
  public/data/Pratikkumare.json
Labels: ✍ chore: profile addition

#1663 fix: changed the gitpod badge
  README.md
Labels: ✨ goal: improvement

#1668 added my profile
  public/data/chamberezigbo.json
Labels: ✍ chore: profile addition

#1654 Add KemiDoyin.json
  public/data/KemiDoyin.json
Labels: ✍ chore: profile addition

#1649 add profile
  public/data/briankiariemwaniki.json
Labels: ✍ chore: profile addition

#1655 chore: Add ThePyroTF2
  public/data/ThePyroTF2.json
Labels: ✍ chore: profile addition

#1660 chore: Add paulaxisabel
  public/data/paulaxisabel.json
Labels: ✍ chore: profile addition

#1664 Add JideAbdQudus
  public/data/jideabdqudus.json
Labels: ✍ chore: profile addition

#1667 chore: update dunnjacoba.json
  public/data/dunnjacoba.json
Labels: ⭐ goal: addition

#1666 chore: Add IMPranshu
  public/data/impranshu.json
Labels: ✍ chore: profile addition

#1658 Add Seth Addo
  public/data/seths10.json
Labels: ✍ chore: profile addition

#1669 chore: Add mendax0110
  public/data/mendax0110.json
Labels: ✍ chore: profile addition

#1670 Corrected a typo in bio
  public/data/chamberezigbo.json
Labels: ✨ goal: improvement

#1671 ADD hemantsw.json
  public/data/Hemantsw.json
Labels: ✍ chore: profile addition

#1676 Add Amedzro-Elikplim profile
  public/data/Amedzro-Elikplim.json
Labels: ✍ chore: profile addition

#1673 Add kalyan profile to LinkFree
  public/data/kalyan-vurugonda.json
Labels: ✍ chore: profile addition

#1648 Create lasse.json
  public/data/lassv.json
Labels: ✍ chore: profile addition

#1679 Create omerome83.json
  public/data/omerome83.json
Labels: ✍ chore: profile addition

#1677 add devmukhtar profile
  public/data/devmukhtarr.json
Labels: ✍ chore: profile addition

#1665 add yire morlans linkfree page
  public/data/yiremorlans.json
Labels: ✍ chore: profile addition

#1678 ankita malik profile added
  public/data/AnkitaMalik22.json
Labels: ✍ chore: profile addition

#1691 added my profile
  public/data/amarjeet.json
Labels: ✍ chore: profile addition

#1675 addProfile
  public/data/ben-dh3.json
Labels: ✍ chore: profile addition

#1692 Added my profile (AnuragK.json)
  public/data/AnuragK.json
Labels: ✍ chore: profile addition

#1689 Update imlakshay08.json
  public/data/imlakshay08.json
Labels: ✨ goal: improvement

#1597 Share Profile Icon Fix
  src/Components/Icons/GetIcons.js
  src/Components/Profile.css
  src/Components/Profile.js
  src/Components/ShareProfile.js
Labels: 🛠 goal: fix

#1703 ci: add more workflows to reviewpad configuration
  reviewpad.yml
Labels: large, waiting-for-reviewers
