Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-04, with the labels that each got.

#1213 Added my profile in LinkFree/public/data
  public/data/Pritam0077.json
Labels: ✍ chore: profile addition

#1216 added my profile to public data
  public/data/AlessandroMinoccheri.json
Labels: ✍ chore: profile addition

#1224 chore: add Horlakz
  public/data/Horlakz.json
Labels: ✍ chore: profile addition

#1218 chore: major changes to profile
  public/data/krshdev.json
Labels: ✨ goal: improvement

#1226 chore: add Jadhielv
  public/data/Jadhielv.json
Labels: ✍ chore: profile addition

#1229 akshatmittal61
  public/data/akshatmittal61.json
Labels: ✍ chore: profile addition

#1231 This is a sample message
  public/data/ezeetester.json
Labels: ✍ chore: profile addition

#1235 update blog link
  public/data/shivanshyadav.json
Labels: 🛠 goal: fix

#1239 shivam-sharma7.json file add
  public/data/shivam-sharma7.json
Labels: ✍ chore: profile addition

#1234 docs: clearer instructions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📄 aspect: text

#1242 zodraccir
  public/data/zodraccir.json
Labels: ✍ chore: profile addition

#1243 Add my profile
  public/data/ezinneanne.json
Labels: ✍ chore: profile addition

#1252 chore: add donmarvex
  public/data/donmarvex.json
Labels: ✍ chore: profile addition

#1257 Add Viraj's Profile
  public/data/virajnirbhavane.json
Labels: ✍ chore: profile addition
