Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-01, with the labels that each got.

#877 fix: add srkds/Nirav
  public/data/srkds.json
Labels: ✍ chore: profile addition

#881 fix: add Chaitanya
  public/data/Chaitanya7666.json
Labels: ✍ chore: profile addition

#893 fix: add Vaishnav Shyam
  public/data/vaishnav-sh.json
Labels: ✍ chore: profile addition

#879 fix: add Muhammad Sameem
  public/data/sameem420.json
Labels: ✍ chore: profile addition

#889 fix: add Harsh Singh
  public/data/harshsinghatz.json
Labels: ✍ chore: profile addition

#892 fix: add Wasiq Amjad Bhamla
  public/data/wasiqb.json
Labels: ✍ chore: profile addition

#903 fix: add Divyansh Raj
  public/data/divyanshraj0408.json
Labels: ✍ chore: profile addition

#906 fix: add Meet Mulik
  public/data/MeetMulik.json
Labels: ✍ chore: profile addition

#897 fix: add john babu's profile
  public/data/john.json
Labels: ✍ chore: profile addition

#905 fix: add Ankan Bag
  public/data/ankanbag101.json
Labels: ✍ chore: profile addition

#913 style: format files
  public/data/ankanbag101.json
Labels: 💻 aspect: code, 🛠 goal: fix

#909 chore: add anish de
  public/data/anishde12020.json
Labels: ✍ chore: profile addition

#919 fix: github username changed
  public/data/ashwinair.json
Labels: 🛠 goal: fix

#918 chore: add Digambar Tupurwadi
  public/data/digambar.json
Labels: ✍ chore: profile addition

#915 chore: add Rahulbaran
  public/data/Rahulbaran.json
Labels: ✍ chore: profile addition

#914 chore: add cyberdevv
  public/data/CyberDevv.json
Labels: ✍ chore: profile addition

#898 feat: add snapchat and codeforces
  README.md
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: ⭐ goal: addition, 🕹 aspect: interface

#896 chore: add Subhojit Dey
  public/data/Subhojit-Dey1234.json
Labels: ✍ chore: profile addition

#916 chore: add Adarsh
  public/data/Adarsh.json
Labels: ✍ chore: profile addition

#922 chore: add Nirbhay Chaplot
  public/data/nirbhay12345.json
Labels: ✍ chore: profile addition

#908 feat: added profile sharing option
  src/Components/Profile.js
  src/Components/ShareIcon.js
  src/Components/ShareProfile.js
Labels: 🕹 aspect: interface

#926 chore: add Teddy Yongo
  public/data/teyddie22.json
Labels: ✍ chore: profile addition

#920 fix: improve documentation
  README.md
Labels: 📄 aspect: text

#929 Adding profile for Abhishek Gite
  public/data/abhishek.json
Labels: ✍ chore: profile addition

#936 Profile Details
  public/data/lawanu.json
Labels: ✍ chore: profile addition

#942 Create Cyebukayire.json
  public/data/Cyebukayire.json
Labels: ✍ chore: profile addition

#931 Create LukeMurray.json
  public/data/LukeMurray.json
Labels: ✍ chore: profile addition

#945 Adding personal profile
  public/data/eoinmurphy.json
Labels: ✍ chore: profile addition

#947 chore: add user: nhemnt
  public/data/nhemnt.json
Labels: ✍ chore: profile addition

#949 chore: add user : subash
  public/data/subash.json
Labels: ✍ chore: profile addition

#939 Adding my profile on linkfree
  public/data/HAT52.json
Labels: ✍ chore: profile addition

#937 feat: Filter by profile type
  generate.js
  package-lock.json
  package.json
  src/App.js
  src/Components/Home/Users.js
  src/Components/Home/filterProfileType.js
Labels: ⭐ goal: addition

#958 Profile to LinkFree
  public/data/ronenhammnd.json
Labels: ✍ chore: profile addition

#962 Chore update vikasganiga05
  public/data/vikasganiga05.json
Labels: ⭐ goal: addition

#963 Added my .json bio
  public/data/ryan-broguiere.json
Labels: ✍ chore: profile addition

#959 Added my file sauradip.json to linkfree
  public/data/sauradip.json
Labels: ✍ chore: profile addition

#967 Added aliraza944.json
  public/data/aliraza944.json
Labels: ✍ chore: profile addition

#970 chore: fixup package files
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: 🛠 goal: fix

#971 add kabir0x17 LinkFree
  public/data/kabir0x17.json
Labels: ✍ chore: profile addition

#979 add mansi-binjola.json in public/data/ folder
  public/data/mansi-binjola.json
Labels: ✍ chore: profile addition

#974 chore: add Lakshay Tyagi
  public/data/imlakshay08.json
Labels: ✍ chore: profile addition

#981 fix: add profile arpanaditya
  public/data/arpanaditya.json
Labels: ✍ chore: profile addition

#943 Added Profile to Public/data
  public/data/AntonyKimani.json
Labels: ✍ chore: profile addition

#985 add devesh2511
  public/data/devesh2511.json
Labels: ✍ chore: profile addition

#984 fix: Add medium as new social icon #982
  README.md
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: ⭐ goal: addition, 🕹 aspect: interface

#975 chore: add Aaquib Ali
  public/data/aaquibdev.json
Labels: ✍ chore: profile addition

#987 added portfolio website to profile
  public/data/ronenhammnd.json
Labels: ✍ chore: profile addition

#986 chore: add lavakush
  public/data/Lavakush Biyani.json
Labels: ✍ chore: profile addition

#995 added my blogs 😁
  public/data/shivanshyadav.json
Labels: ⭐ goal: addition

#994 my info added
  public/data/Srinika99.json
Labels: ✍ chore: profile addition

#997 Add profile for amehi0index
  public/data/amehi0index.json
Labels: ✍ chore: profile addition

#660 Corrected element hierarchy
  src/Components/Profile.js
  src/Components/ShareProfile.js
Labels: 🛠 goal: fix

#953 chore: add cerulean coders
  public/data/CeruleanCodersComm.json
Labels: ✍ chore: profile addition

#998 Create VinsonSamuel.json
  public/data/VinsonSamuel.json
Labels: ✍ chore: profile addition

#1002 Aaquib
  public/data/aaquibdev.json
Labels: ✍ chore: profile addition

#1004 chore: Add Sarvesh Limaye
  public/data/SarveshLimaye.json
Labels: ✍ chore: profile addition

#1001 chore: add Peter Ime
  public/data/PeroHub.json
Labels: ✍ chore: profile addition

#1011 saugat information added
  public/data/saugat.json
Labels: ✍ chore: profile addition

#1019 Add 'Lovakush'
  public/data/lovakush.json
Labels: ✍ chore: profile addition

#1017 chore: add Sagar0-0
  public/data/Sagar0-0.json
Labels: ✍ chore: profile addition

#1020 chore: add Madhavi Mandalia
  public/data/MadhaviMandalia.json
Labels: ✍ chore: profile addition

#1018 chore: add T.kumaran
  public/data/kumaran.json
Labels: ✍ chore: profile addition

#1022 chore: update krshdev
  public/data/krshdev.json
Labels: 🛠 goal: fix

#1012 feat:Added HackerRank Icon-Issue-1010
  README.md
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: ⭐ goal: addition

#1026 Add Polywork Icon
  README.md
  src/Components/Icons/GetIcons.js
  src/config/links.json
Labels: ⭐ goal: addition

#1030 Create supunsathsara.json
  public/data/supunsathsara.json
Labels: ✍ chore: profile addition

#1028 My profile added Fremen1990 and package json repaired with npm audit --force
  public/data/fremen1990.json
Labels: ✍ chore: profile addition

#1033 chore: add abhilipsasahoo03
  public/data/abhilipsasahoo03.json
Labels: ✍ chore: profile addition

#1025 change buttons to links #1016
  cypress/integration/user.feature
  src/Components/Links.js
  src/Components/StyledLink.js
Labels: ✨ goal: improvement

#976 docs: add warning about not adding package.json
  Contributing.md
Labels: 📄 aspect: text

#1035 Add Susmita-Dey.json
  public/data/Susmita-Dey.json
Labels: ✍ chore: profile addition

#1036 Add Sangjin.json
  public/data/Sangjin.json
Labels: ✍ chore: profile addition

#1034 added hailer24.json
  public/data/hailer24.json
Labels: ✍ chore: profile addition

#1038 including Json File for Aryan Raj
  public/data/AryanRaj.json
Labels: ✍ chore: profile addition

#1039 Add PhilipBDev.json to LinkFree directory
  public/data/PhilipBDev.json
Labels: ✍ chore: profile addition

#1042 add lloydlobo.json
  public/data/lloydlobo.json
Labels: ✍ chore: profile addition

#1041 add vasanti suthar
  public/data/vasantisuthar.json
Labels: ✍ chore: profile addition

#1044 kendalldoescoding linktree
  public/data/KendallDoesCoding.json
Labels: ✍ chore: profile addition

#1047 Added Brian Nduhiu
  public/data/brianNduhiu.json
Labels: ✍ chore: profile addition

#1046 Chaitanya_Sawant.json file added
  public/data/Chaitanya_Sawant.json
Labels: ✍ chore: profile addition

#1048 Added my profile
  public/data/MadhuSaini22.json
Labels: ✍ chore: profile addition
