Repository EddieHubCommunity/BioDrop, pull requests merged in 2022-03, with the labels that each got.

#1160 Add OkeyChukwude.json
  public/data/OkeyChukwude.json
Labels: ✍ chore: profile addition

#1162 Add profile benjaminmichaelis.json
  public/data/benjaminmichaelis.json
Labels: ✍ chore: profile addition

#1167 chore: add Dalpat Rathore
  public/data/dalpatrathore.json
Labels: ✍ chore: profile addition

#1165 Added j-barreiros
  public/data/j-barreiros.json
Labels: ✍ chore: profile addition

#1164 add victoriacheng15.json
  public/data/victoriacheng15.json
Labels: ✍ chore: profile addition

#1163 add souravsk
  public/data/souravsk.json
Labels: ✍ chore: profile addition

#1175 Add: Karlgusta's profile
  public/data/karlGusta.json
Labels: ✍ chore: profile addition

#1176 Add profile indigo423
  public/data/indigo423.json
Labels: ✍ chore: profile addition

#1173 Fix: MD034/no-bare-urls: Bare URL used
  SECURITY.md
Labels: 🛠 goal: fix

#1177 Added file vaibhav.json
  public/data/vaibhav.json
Labels: ✍ chore: profile addition

#1179 Added URL key and value inside milestones
  README.md
Labels: ⭐ goal: addition

#1178 Create sheoranharis.json
  sheoranharis.json
Labels: ✍ chore: profile addition

#1183 Update README.md
  README.md
Labels: ✨ goal: improvement

#1180 #866-align version and input field on small screen
  src/Components/Navbar.css
Labels: ✨ goal: improvement

#1194 Created codewithfan LinkFree
  public/data/codewithfan.json
Labels: ✍ chore: profile addition

#1198 Add saikalyan15
  public/data/saikalyan.json
Labels: ✍ chore: profile addition

#1199 chore: add Sam Chan
  public/data/samchan.json
Labels: ✍ chore: profile addition

#1191 Patch 1
  public/data/saifrahman.json
Labels: ✍ chore: profile addition

#1202 chore: add robertusbagaskara
  public/data/robertusbagaskara.json
Labels: ✍ chore: profile addition

#1203 chore: add mohamed_ah
  public/data/mohamed_ah.json
Labels: ✍ chore: profile addition
