Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-06, with the labels that each got.

#7294 refactored total.js to load app stats from DB
  pages/api/statistics/totals.js
Labels: medium, waiting-for-reviewers, issue linked

#7293 data: chaitanyakatore
  data/chaitanyakatore.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7295 data: itsdevdeepak.json
  data/itsdevdeepak.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7296 data: AbhayaShankar
  data/AbhayaShankar.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7299 data:heyrishabh13
  data/heyrishabh13.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7303 Patch 2: pankajktech.json
  data/pankajktech.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7305 data: bikrantjajware
  data/bikrantjajware.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7313 Update Hittitech.json
  data/Hittitech.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7314 data: CYBWEBALI
  data/CYBWEBALI.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7316 data: PuneetMahali
  data/puneetmahali.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7307 data :rishu6263
  data/rishu6263.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7321 Update data of my profile
  data/Rahulbaran.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7323 fix: update linkfree-cli version
  package-lock.json
  package.json
Labels: 💻 aspect: code, 🛠 goal: fix, small, waiting-for-reviewers

#7330 Reduce bundle size by minimizing use of `react-icons`
  components/Alert.js
  components/BreadCrumb.js
  components/Button.js
  components/ClipboardCopy.js
  components/Footer.js
  components/Modal.js
  components/icons/FaGithub.js
  components/icons/FaLinkedin.js
  components/icons/FaYoutube.js
  components/navbar/Navbar.js
  components/user/UserProfile.js
  pages/404.js
  pages/auth/signin.js
  pages/index.js
  pages/map.js
  pages/playground.js
  pages/premium.js
Labels: large, waiting-for-reviewers

#7125 feat: added skip links to pages
  components/SkipLink.js
  components/layouts/MultiLayout.js
  components/layouts/SingleLayout.js
Labels: large, waiting-for-reviewers, issue linked

#7308 fix: add responsive height to youtube embeds (#7273)
  components/embeds/Youtube.js
Labels: small, waiting-for-reviewers

#7322 Create JimmyTron.json
  data/JimmyTron.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7328 data: homelyseven250
  data/homelyseven250.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7329 Create Sanmidaniels07.json
  data/Sanmidaniels07.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7331 data: katzjeff
  data/katzjeff.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7332 data:funmilolaadebisi
  data/funmilolaadebisi.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7335 data: l-legren
  data/l-legren.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7336 data:Amit-45
  data/Amit-45.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7347 data:kdp-alpha
  data/kdp-alpha.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7350 Remove single use mode #7343
  components/layouts/SingleLayout.js
  config/user.json
  pages/[username].js
  pages/docs/advanced/single-user-mode.mdx
  pages/docs/faqs.mdx
  pages/docs/index.js
  pages/index.js
Labels: large, waiting-for-reviewers

#7338 data:Jacques-Murray
  data/Jacques-Murray.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7351 data:SaumyaBhushan
  data/SaumyaBhushan.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7074 (docs): add alert boxes
  pages/docs/environments/gitpod.mdx
  pages/docs/quickstart.mdx
Labels: large, waiting-for-reviewers, issue linked

#7356 Set preload to false on most links
  components/Button.js
  components/Link.js
  components/navbar/NavLink.js
Labels: small, waiting-for-reviewers

#7360 Docs alert boxes
  pages/docs/environments/gitpod.mdx
  pages/docs/environments/local-development.mdx
  pages/docs/quickstart.mdx
Labels: large, waiting-for-reviewers

#7363 fix: vercel single deploy
  .github/workflows/vercel.yml
Labels: small, waiting-for-reviewers

#7288 Search page cleanup
  components/user/UserCard.js
  pages/api/users/index.js
  pages/search.js
Labels: medium, waiting-for-reviewers

#7357 data:bansaltushar014
  data/bansaltushar014.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7353 data : shreyas0924
  data/shreyas0924.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7367 increses the font size
  pages/index.js
Labels: small, waiting-for-reviewers

#7339 Add link markdown style in bio
  components/user/UserProfile.js
Labels: small, waiting-for-reviewers, issue linked

#7372 Fix the TODOs of api/event.js #7341
  pages/api/events.js
Labels: medium, waiting-for-reviewers

#7370 data:SudarshanSirsi
  data/SudarshanSirsi.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7374 data:krimoelbahri
  data/krimoelbahri.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7377 data: rudra016
  data/rudra016.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7378 Update money8203.json
  data/money8203.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7380 data: katzjeff
  data/katzjeff.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7382 Update: 'Alkaison' profile details. Its my profile.
  data/Alkaison.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7387 data: Kzoeps
  data/Kzoeps.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7325 feat: add zod validation
  .env.docker
  .env.example
  config/logger.js
  config/mongo.js
  config/schemas/clientSchema.js
  config/schemas/serverSchema.js
  package-lock.json
  package.json
  pages/[username].js
  pages/account/statistics.js
  pages/api/auth/[...nextauth].js
  pages/api/revalidate.js
  pages/api/system/reload.js
  pages/api/users/[username]/index.js
  pages/docs/environments/environment-variables.mdx
  pages/playground.js
  tests/setup/auth.js
  tests/setup/global-setup.js
Labels: large, waiting-for-reviewers, tests, issue linked

#7348 [OTHER]: Added Changelog Basic Test
  pages/changelog.js
  tests/changelog.spec.js
  tests/events.spec.js
Labels: large, waiting-for-reviewers, tests, issue linked

#7391 data: aarushiksk
  data/aarushiksk.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7393 Update shubhsharma19.json
  data/shubhsharma19.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7395 Update UserMilestone.js line color from multicolor to light gray.
  components/user/UserMilestone.js
  pages/docs/how-to-guides/events.mdx
Labels: small, waiting-for-reviewers, issue linked

#7402 fix: milestone border color
  components/user/UserMilestones.js
Labels: small, waiting-for-reviewers

#7400 data: grand-rick001 - Add milestone
  data/grand-rick001.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7408 data: Pradumnasaraf
  data/Pradumnasaraf/events/2023-04-15-api-days-patna.json
  data/Pradumnasaraf/events/2023-09-11-web3conf-india.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#7414 Fix home page screenshots
  pages/index.js
Labels: small, waiting-for-reviewers

#7413 package.json description changed
  components/mdx/ComponentStyle.js
  package.json
Labels: small, waiting-for-reviewers

#7412 Update Poonam1607.json
  data/Poonam1607.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7415 data: preethi1915.json
  data/preethi1915.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7421 data: mallyapravin
  data/mallyapravin.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7423 data: SaraviaMartin
  data/SaraviaMartin.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7424 Update itsdevdeepak.json
  data/itsdevdeepak.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7425 changes the font size of future description
  pages/index.js
Labels: small, waiting-for-reviewers

#7355 Issue #7072 | Rename "users" API endpoints to "profiles"
  components/user/UserLink.js
  components/user/UserSocials.js
  pages/[username].js
  pages/account/statistics.js
  pages/api/profiles/[username]/index.js
  pages/api/profiles/[username]/links/[url].js
  pages/api/profiles/index.js
  pages/map.js
  pages/search.js
  tests/reload-check.js
  tests/reload-fake.js
Labels: medium, waiting-for-reviewers, tests, issue linked

#7430 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: medium, waiting-for-reviewers

#7432 Update README.md
  README.md
Labels: medium, waiting-for-reviewers

#7379 Run profile stat updates concurrently
  pages/api/profiles/[username]/index.js
  tests/profile.spec.js
Labels: large, waiting-for-reviewers, tests

#7434 footer icons fixed correctly
  components/icons/FaGithub.js
  components/icons/FaLinkedin.js
  components/icons/FaYoutube.js
Labels: large, waiting-for-reviewers

#7436 Changed Scroll Wheel Zoom
  components/map/Map.js
Labels: small, waiting-for-reviewers

#7304 Added YouTube video to contributing file with the img (#7289)
  CONTRIBUTING.md
Labels: small, waiting-for-reviewers, issue linked

#7444 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: small, waiting-for-reviewers

#7384 Fix: Cannot de-select tag/skill in search page when coming from profile.
  components/user/UserProfile.js
  tests/profile.spec.js
Labels: small, waiting-for-reviewers, tests, issue linked

#7337 fix: resolves issue where <a> tag and <li> are misaligned (#6967)
  pages/docs/quickstart.mdx
Labels: medium, waiting-for-reviewers, issue linked

#7426 data: AbhinavJaintle
  data/AbhinavJaintle.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7399 data: jegrami
  data/jegrami.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7453 data: BatuhanOnge
  data/BatuhanOnge.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7455 data: MohdTanzeel
  data/MohdTanzeel.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7457 Update : SiddheshBangar.json
  data/SiddheshBangar.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7458 data: Devansh-Singh-Parmar
  data/Devansh-Singh-Parmar.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7460 docs: quickstart copy non json
  pages/docs/quickstart.mdx
Labels: small, waiting-for-reviewers

#7392 Improve user search experience #6872
  pages/search.js
Labels: large, waiting-for-reviewers, issue linked

#7471 update:navharsh.json
  data/navharsh.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7473 fix: increase profile page tabs text size (EddieHubCommunity#7049)
  components/user/UserTabs.js
Labels: small, waiting-for-reviewers

#7468 data: chaitali-khangar
  data/chaitali-khangar.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7481 fix: profile tab font size #7049
  components/user/UserTabs.js
Labels: small, waiting-for-reviewers

#7478 Create IsaamAkhtar.json
  data/IsaamAkhtar.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7475 fix: double tabbable tags
  components/user/UserProfile.js
  tests/profile.spec.js
Labels: medium, waiting-for-reviewers, tests, issue linked

#7232 Data: Omcodes23
  Omcodes23.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#7269 fix:Automatically unlock issue (#6770)
  .github/lock-unlock-issues.yml
  .github/workflows/issue-lock.yml
  .github/workflows/lock-unlock-issues.yml
Labels: 🚧 status: blocked, large, waiting-for-reviewers, issue linked

#7485 fix: automatically unlock issue by labels (#6770) (#7269)
  .github/config/issue-lock-unlock.yml
  .github/config/reviewpad.yml
  .github/workflows/issue-lock-unlock.yml
  .github/workflows/issue-lock.yml
  .github/workflows/reviewpad.yml
Labels: large, waiting-for-reviewers

#7495 fix: release action
  .github/workflows/release.yml
Labels: small, CI/CD

#7506 data: Pradumnasaraf
  data/Pradumnasaraf.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7505 fix: floating button focus issue
  pages/[username].js
  pages/index.js
Labels: small, waiting-for-reviewers

#7503 Timestamps added to all db models
  models/Account.js
  models/Link.js
  models/LinkStats.js
  models/Profile.js
  models/ProfileStats.js
  models/Session.js
  models/Stats.js
  models/User.js
  models/VerificationToken.js
Labels: medium, waiting-for-reviewers

#7493 fix : Playground preview theme
  components/Modal.js
Labels: small, waiting-for-reviewers

#7513 fix: deployment trigger for releases
  .github/workflows/vercel.yml
Labels: small, waiting-for-reviewers

#7500 data: Soumava-221B
  data/Soumava-221B.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7504 Updated my LinkFree profile
  data/SaptarshiSarkar12.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7508 data: Soham-glitch
  data/Soham-glitch.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7515 Fix release action token
  .github/workflows/release.yml
  .github/workflows/vercel.yml
Labels: small, waiting-for-reviewers

#7510 feat: timestamps to all db models (#7503)
  .github/workflows/build.yml
  models/Account.js
  models/Link.js
  models/LinkStats.js
  models/Profile.js
  models/ProfileStats.js
  models/Session.js
  models/Stats.js
  models/User.js
  models/VerificationToken.js
Labels: large, waiting-for-reviewers

#7518 Update quickstart.mdx
  pages/docs/quickstart.mdx
Labels: medium, waiting-for-reviewers

#7523 data: arshidte
  data/arshidte.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7525 data: KunalVerma
  data/verma-kunal.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7526 Updated my LinkFree Profile
  data/SaptarshiSarkar12.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7477 data: Panquesito7
  data/Panquesito7.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7529 data: SebastianJames55
  data/SebastianJames55.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7532 data: remove type key from profiles
  data/piaseckijulian.json
  data/victorchrollo14.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers

#7527 fix: Changed Profile page group link headings from h3 to h2.
  components/user/UserLinks.js
Labels: small, waiting-for-reviewers, issue linked

#7539 data: jfmartinz
  data/jfmartinz.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7542 Thisisdishang patch 1
  data/thisisdishang.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7536 data: creating anasouardini.json
  data/anasouardini.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7544 data: zaktech96
  data/zaktech96.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7545 data:Tanmay-Joshi73
  data/Tanmay-Joshi73.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7546 data: helloakash1701
  data/helloakash1701.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7548 data: Sugam Goel
  data/Sugamgoel28.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7550 data:AbrarAlHasan.json
  data/AbrarAlHasan.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7551 Sugamgoel28 patch 2
  data/Sugamgoel28.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7555 update /data/anasouardini.json: added a links category and changed some icons.
  data/anasouardini.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7156 Group events attended by multiple people
  components/event/EventCard.js
  pages/api/events.js
  pages/events.js
Labels: large, waiting-for-reviewers, issue linked

#7558 /data/anasouardini.json: fixed a typo.
  data/anasouardini.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7563 data: Panquesito7
  data/Panquesito7.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7566 data: jegrami
  data/jegrami.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7569 fix: formatting
  pages/api/events.js
Labels: large, waiting-for-reviewers

#7556 fix: Profile page links shows background color on hover
  components/user/UserLink.js
Labels: small, waiting-for-reviewers, issue linked

#7561 data: samthatcode
  data/samthatcode.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7572 data: Rohit312001
  data/Rohit312001.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7573 data:programmer765
  data/programmer765.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7574 data: ChavvaNarayana
  data/ChavvaNarayana.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7584 data: iam-Rps
  data/iam-Rps.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7587 data: add new milestone
  data/CBID2.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7589 data: revise date of new milestone
  data/CBID2.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7594 Testimonial for 'Pradumnasaraf' by 'iam-Rps'
  data/Pradumnasaraf/testimonials/iam-Rps.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers

#7609 updated profile link to preview correctly on share
  pages/[username].js
Labels: medium, waiting-for-reviewers

#7613 Fix pr 7609 formatting
  pages/[username].js
Labels: small, waiting-for-reviewers

#7600 data: austincomer
  data/austincomer.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7603 data: vigdisha
  data/vigdisha.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7615 fix: social og description
  components/PageHead.js
  pages/[username].js
Labels: small, waiting-for-reviewers

#7578 data:DevasyaRajguru
  data/devasyarajguu.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#7535 feat: search by location
  pages/search.js
Labels: large, waiting-for-reviewers, issue linked

#7596 data: iam-Rps
  data/iam-Rps.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7620 data: Pravesh-Sudha
  data/Pravesh-Sudha.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7621 data: vigdisha
  data/vigdisha.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#7626 data: BDFL669.json
  data/BDFL669.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7629 data: SAD0XER
  data/SAD0XER.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7630 data: shadrack-mwelwa
  data/shadrack-mwelwa.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#7633 data: nabin47
  data/nabin47.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7634 data: PeterSamuel
  data/Petsamuel.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7631 data: LeonNunes
  data/afro-coder.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7636 data: CBID2
  data/CBID2.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7641 updated my profile with milestone
  data/kunal00000.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#7638 fix: update the LinkFree CLI version
  package-lock.json
  package.json
Labels: large, waiting-for-reviewers

#7640 [FIX] getting localhost in BASE_URL on statistics and playground page
  pages/account/statistics.js
  pages/playground.js
Labels: medium, waiting-for-reviewers, issue linked
