Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-04, with the labels that each got.

#5728 Create Jkudjo.json
  data/Jkudjo.json
Labels: ✍ chore: profile addition, medium, LGTM

#5734 Sectioned my Linkfree profile
  data/CBID2.json
Labels: ✍ chore: profile addition, small, LGTM

#5741 data: akshatshukla13
  data/akshatshukla13.json
Labels: ✍ chore: profile addition, large, LGTM

#5745 Add profile
  data/rohansx.json
Labels: ✍ chore: profile addition, medium, LGTM

#5746 data: mikejw
  data/mikejw.json
Labels: ✍ chore: profile addition, medium, LGTM

#5749 Patch 3
  data/iAnonymous3000.json
Labels: ✍ chore: profile addition, large, LGTM

#5758 data: Vishal21121
  data/Vishal21121.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#5750 data:nkitanand
  data/nkitanand.json
Labels: ✍ chore: profile addition, large, LGTM

#5759 data: Kevinkp09
  data/Kevinkp09.json
Labels: ✍ chore: profile addition, medium, LGTM

#5637 [FEATURE] Move community resources to a page in the app #5489
  package-lock.json
  pages/docs/contributors-changelog.mdx
  pages/docs/index.js
Labels: large

#5768 docs: improve the LinkFree-CLI page
  pages/docs/environments/linkfree-cli.mdx
Labels: 📄 aspect: text, small

#5769 Community resource
  NOCODE-CHANGELOG.md
  pages/docs/community-resources.mdx
  pages/docs/index.js
Labels: large

#5773 fix: community resources link
  pages/docs/index.js
Labels: medium

#5775 [Homepage]:Statistics screenshot added to features section.
  pages/index.js
Labels: small

#5763 Create akhilesh-w.json
  data/akhilesh-w.json
Labels: ✍ chore: profile addition, medium, LGTM

#5778 data:AdityaChaudhary3
  data/AdityaChaudhary3.json
Labels: ✍ chore: profile addition, large, LGTM

#5779 data: surajmaity1
  data/surajmaity1.json
Labels: ✍ chore: profile addition, large, LGTM

#4902 Feature: Dark Mode
  components/Footer.js
  components/Testimonials.js
  components/event/EventCard.js
  components/event/EventKey.js
  components/event/EventTabs.js
  components/layouts/DocsLayout.js
  components/navbar/Navbar.js
  components/statistics/BasicCards.js
  components/user/UserCard.js
  components/user/UserLink.js
  components/user/UserLinks.js
  components/user/UserTabs.js
  components/user/UserTestimonials.js
  package-lock.json
  package.json
  pages/_app.js
  pages/docs/index.js
  pages/index.js
  pages/playground.js
  pages/search.js
  styles/globals.css
  tailwind.config.js
Labels: large

#5777 chore: update naomi's github username
  data/naomi-lgbt.json
Labels: ✍ chore: profile addition, small, LGTM

#5795 Optimised search to find by GitHub Username Added
  pages/search.js
Labels: small

#5786 data: JeffProd
  data/Tazeg.json
Labels: ✍ chore: profile addition, medium, LGTM

#5784 Update shubhsharma19.json
  data/shubhsharma19.json
Labels: ✍ chore: profile addition, medium, LGTM

#5789 data: Mohitkoley
  data/Mohitkoley.json
Labels: ✍ chore: profile addition, medium, LGTM

#5790 Update Ankur6702.json
  data/Ankur6702.json
Labels: ✍ chore: profile addition, large, LGTM

#5782 added LinkFree profile JSON file.
  data/Satyxm.json
Labels: ✍ chore: profile addition, medium, LGTM

#5783 data: updates
  data/mikejw.json
Labels: ✍ chore: profile addition, large, LGTM

#5794 data: prashant235913
  data/prashant235913.json
Labels: ✍ chore: profile addition, medium, LGTM

#5792 data: Add API Day Patna event
  data/Pradumnasaraf/events/2023-04-15-api-days-patna.json
Labels: ✍ chore: profile addition, medium

#5800 Link for Single User Mode 404d, added the missing / and advanced folder
  pages/docs/faqs.mdx
Labels: small

#5799 Grammar fix on Hacktoberfest page
  pages/docs/contributing/hacktoberfest.mdx
Labels: small

#5797 added tailwind classes to home page
  components/Testimonials.js
  components/navbar/Navbar.js
  pages/index.js
  styles/globals.css
  tailwind.config.js
Labels: large

#5793 data : prasadhimanshu789
  data/himanshuprasad789.json
Labels: ✍ chore: profile addition, medium, LGTM

#5798 data: DrVickie8
  data/DrVickie8.json
Labels: ✍ chore: profile addition, medium, LGTM

#5802 data : Abdullah-moiz
  data/Abdullah-moiz.json
Labels: ✍ chore: profile addition, medium, LGTM

#5733 Dineshlalam15 patch 4
  data/dineshlalam15.json
Labels: ✍ chore: profile addition, medium, LGTM

#5752 switched line 7 and 8 in public/manifest.json
  public/manifest.json
Labels: small

#5806 Create a new repo. add main & supporting files
  data/JonVojtush.json
  data/JonVojtush/testimonials/bethDubyak.json
  data/JonVojtush/testimonials/rickPollick.json
Labels: ✍ chore: profile addition, large

#5818 update Storybook to v7 GA
  .storybook/main.js
  package-lock.json
  package.json
Labels: large

#5821 data: NishantCoder108
  data/NishantCoder108.json
Labels: ✍ chore: profile addition, large, LGTM

#5814 data: Palakkgoyal
  data/Palakkgoyal.json
Labels: ✍ chore: profile addition, medium, LGTM

#5484 Updated the screenshots for Quickstart guide
  pages/docs/quickstart.mdx
Labels: 🕹 aspect: interface, ✨ goal: improvement, small, waiting-for-reviewers, kudos

#5766 docs: add information on why user markers not appearing in local dev
  pages/docs/map.mdx
Labels: medium

#5816 Fixed Issue#3080 Removed the dropdown if User has only links.
  components/user/UserTabs.js
Labels: small

#5826 fix: removed dropdown if user has only links (#5816)
  components/user/UserTabs.js
Labels: medium

#5823 data: shadmanhere
  data/shadmanhere.json
Labels: ✍ chore: profile addition, medium, LGTM

#5809 Dark mode fixes to the home page and profile page
  components/Testimonials.js
  components/event/EventCard.js
  components/event/EventKey.js
  components/statistics/BasicCards.js
  components/user/UserEvents.js
  components/user/UserLink.js
  components/user/UserLinks.js
  components/user/UserMilestone.js
  components/user/UserMilestones.js
  components/user/UserTabs.js
  components/user/UserTestimonials.js
  pages/index.js
  tailwind.config.js
Labels: large

#5829 fix: Fixed issue#5828 Updated UI of the Search bar
  components/Tag.js
  pages/search.js
Labels: small

#5833 Updated Profile
  data/Vishrut19.json
Labels: ✍ chore: profile addition, large, LGTM

#5837 data: PriyanshuPatel
  data/priyanshu096.json
Labels: ✍ chore: profile addition, large, LGTM

#5839 data: pushkaraj2007
  data/pushkaraj2007.json
Labels: ✍ chore: profile addition, medium, LGTM

#5847 Darkmode
  components/Badge.js
  components/Button.js
  components/ClipboardCopy.js
  components/Footer.js
  components/IconCard.js
  components/Tag.js
  components/event/EventTabs.js
  components/form/input.js
  components/modals/ProfilePreview.js
  components/navbar/NavLink.js
  components/navbar/Navbar.js
  components/statistics/ProgressBar.js
  components/user/UserCard.js
  components/user/UserMilestones.js
  pages/[username].js
  pages/account/no-profile.js
  pages/account/statistics.js
  pages/changelog.js
  pages/docs/index.js
  pages/events.js
  pages/icons.js
  pages/playground.js
  pages/search.js
  tailwind.config.js
Labels: large

#5848 profile: added new link, changed bio, tags
  data/priyankarpal.json
Labels: ✍ chore: profile addition, medium, LGTM

#5843 data: ashlab05
  data/ashlab05.json
Labels: ✍ chore: profile addition, medium, LGTM

#5851 Create cyberpratv.json
  data/cyberpratv.json
Labels: ✍ chore: profile addition, large, LGTM

#5835 Nitisjan patch 1 linkfree profile
  data/nitisjan.json
Labels: ✍ chore: profile addition, medium, LGTM

#5723 data:shubham185y
  data/Shubham185y.json
Labels: ✍ chore: profile addition, medium, LGTM

#5855 data:HarshitMahara
  data/HarshitMahara.json
Labels: ✍ chore: profile addition, medium, LGTM

#5871 docs: multiple assignees and collaborators
  CONTRIBUTING.md
Labels: small

#5857 Add SmashingCon event to profile
  data/amandamartin-dev/events/2023-05-23-smashingcon.json
Labels: ✍ chore: profile addition, medium

#5859 Create sudarshan-doiphode.json
  data/sudarshan-doiphode.json
Labels: ✍ chore: profile addition, large, LGTM

#5875 dark mode fixes
  components/Button.js
  components/Testimonials.js
  pages/index.js
  pages/map.js
Labels: medium

#5834 updated social links
  data/tanitoluwam.json
Labels: ✍ chore: profile addition, small, LGTM

#5844 Techy starr patch 1
  data/TechyStarr.json
Labels: ✍ chore: profile addition, large, LGTM

#5838 data: anekemichael
  data/anekemichael.json
Labels: ✍ chore: profile addition, large, LGTM

#5861 data:ROUSE_prog
  data/ROUSE-prog.json
Labels: ✍ chore: profile addition, medium, LGTM

#5864 Update profile - STIAANWOL
  data/STIAANWOL.json
Labels: ✍ chore: profile addition, medium, LGTM

#5873 data: nfa1
  data/nfa1.json
Labels: ✍ chore: profile addition, medium, LGTM

#5874 data:StarKnightt
  data/StarKnightt.json
Labels: ✍ chore: profile addition, large, LGTM

#5863 Create jaiswalshash.json
  data/jaiswalshash.json
Labels: ✍ chore: profile addition, medium, LGTM

#5876 data:EminTalhaArik
  data/EminTalhaArik.json
Labels: ✍ chore: profile addition, large, LGTM

#5877 data: aka91hu
  data/aka91hu.json
Labels: ✍ chore: profile addition, medium, LGTM

#5879 data: shivamsinghydv
  data/shivamsinghydv.json
Labels: ✍ chore: profile addition, medium, LGTM

#5883 data: Tommymarvel
  data/Tommymarvel.json
Labels: ✍ chore: profile addition, medium, LGTM

#5886 data:Pallavi-33
  data/Pallavi-33.json
Labels: ✍ chore: profile addition, medium, LGTM

#5885 data: temilolakutelu
  data/temilolakutelu.json
Labels: ✍ chore: profile addition, medium, LGTM

#5887 data:naveen13-06
  data/naveen13-06.json
Labels: ✍ chore: profile addition, large, LGTM

#5888 data:Brian-Pob
  data/Brian-Pob.json
Labels: ✍ chore: profile addition, medium, LGTM

#5533 data: queenstack
  data/queenstack.json)
Labels: ✍ chore: profile addition, medium

#5893 Fix queenstack
  data/queenstack.json
Labels: ✍ chore: profile addition, medium

#5860 data:harisdev
  data/harisdev-netizen.json
Labels: ✍ chore: profile addition, large, LGTM

#5900 profile-link-added
  data/parma1111.json
Labels: ✍ chore: profile addition, large, LGTM

#5892 data: StarKnightt
  data/StarKnightt.json
Labels: ✍ chore: profile addition, small, LGTM

#5905 data: RohanSasne
  data/RohanSasne.json
Labels: ✍ chore: profile addition, large, LGTM

#5902 data: rajaditya06
  data/rajaditya06.json
Labels: ✍ chore: profile addition, medium, LGTM

#5904 data: Manazsharma
  data/Manazsharma.json
Labels: ✍ chore: profile addition, medium, LGTM

#5894 data: 1js2002
  data/1js2002.json
Labels: ✍ chore: profile addition, medium, LGTM

#5903 Updated the social links
  data/J-CODE07.json
Labels: ✍ chore: profile addition, small, LGTM

#5906 Darkmode stats and change log fixes
  pages/account/statistics.js
  pages/changelog.js
Labels: medium

#5907 data: rohit190183107010
  data/rohit190183107010.json
Labels: ✍ chore: profile addition, large, LGTM

#5781 feat: dark mode (#4902)
  components/Badge.js
  components/Button.js
  components/ClipboardCopy.js
  components/Footer.js
  components/IconCard.js
  components/Tag.js
  components/Testimonials.js
  components/event/EventCard.js
  components/event/EventKey.js
  components/event/EventTabs.js
  components/form/input.js
  components/layouts/DocsLayout.js
  components/map/Map.js
  components/modals/ProfilePreview.js
  components/navbar/NavLink.js
  components/navbar/Navbar.js
  components/statistics/BasicCards.js
  components/statistics/ProgressBar.js
  components/user/UserCard.js
  components/user/UserEvents.js
  components/user/UserLink.js
  components/user/UserLinks.js
  components/user/UserMilestone.js
  components/user/UserMilestones.js
  components/user/UserTabs.js
  components/user/UserTestimonials.js
  package-lock.json
  package.json
  pages/[username].js
  pages/_app.js
  pages/account/no-profile.js
  pages/account/statistics.js
  pages/changelog.js
  pages/docs/index.js
  pages/events.js
  pages/icons.js
  pages/index.js
  pages/map.js
  pages/playground.js
  pages/search.js
  styles/globals.css
  tailwind.config.js
Labels: large

#5897 data: MuhammadNoorani
  data/MuhammadNoorani.json
Labels: ✍ chore: profile addition, large, LGTM

#5917 docs: darkmode screenshots
  README.md
  pages/index.js
  public/mockup.png
Labels: small

#5915 data: VaradBelwalkar
  data/VaradBelwalkar.json
Labels: ✍ chore: profile addition, large, LGTM

#5921 data: Chandraprakash-Darji
  data/Chandraprakash-Darji.json
Labels: ✍ chore: profile addition, large, LGTM

#5919 data: surendhar-palanisamy
  data/surendhar-palanisamy.json
Labels: ✍ chore: profile addition, medium, LGTM

#5760 data: PrasunKundu
  data/PrasunKundu.json
Labels: ✍ chore: profile addition, medium, LGTM

#5862 Create NathanRag.json
  data/NathanRag.json
Labels: ✍ chore: profile addition, medium, LGTM

#5923 data: Vikash-8090-Yadav
  data/Vikash-8090-Yadav.json
Labels: ✍ chore: profile addition, medium, LGTM

#5924 data: nabadev
  data/nabadev.json
Labels: ✍ chore: profile addition, medium, LGTM

#5933 data: Parmesh119
  data/Parmesh119.json
Labels: ✍ chore: profile addition, large, LGTM

#5951 data: RohanSasne
  data/RohanSasne.json
Labels: ✍ chore: profile addition, medium, LGTM

#5941 data: surendhar-palanisamy
  data/surendhar-palanisamy.json
Labels: ✍ chore: profile addition, large, LGTM

#5880 Create ShivangiS04
  data/ShivangiS04.json
Labels: ✍ chore: profile addition, large, LGTM

#5937 Create Mubashir-Md.json
  data/Mubashir-Md.json
Labels: ✍ chore: profile addition, medium, LGTM

#5939 data: streetstylecoder
  data/streetstylecoder.json
Labels: ✍ chore: profile addition, small, LGTM

#5943 Create SimonVerhoeven.json
  data/SimonVerhoeven.json
Labels: ✍ chore: profile addition, large, LGTM

#5944 Create tangorishi.json
  data/tangorishi.json
Labels: ✍ chore: profile addition, large, LGTM

#5956 Updated Title
  data/KishanGupta114.json
Labels: ✍ chore: profile addition, small, LGTM

#5954 data: BeyondEternal
  data/BeyondEternal.json
Labels: ✍ chore: profile addition, medium, LGTM

#5916 Slowcheetah07 patch 1
  data/slowcheetah07.json
Labels: ✍ chore: profile addition, medium, LGTM

#5963 Update Manazsharma.json
  data/Manazsharma.json
Labels: ✍ chore: profile addition, small, LGTM

#5961 STIAANWOL: Profile Update - Fix youtube icon
  data/STIAANWOL.json
Labels: ✍ chore: profile addition, small, LGTM

#5942 Parmesh119 patch 1
  data/Parmesh119.json
Labels: ✍ chore: profile addition, medium, LGTM

#5964 Add dark mode support to storybook
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  package-lock.json
  package.json
Labels: large

#5955 data: Ayaan49
  data/Ayaan49.json
Labels: ✍ chore: profile addition, small, LGTM

#5928 feat: add text-color white on hover in light mode to button component
  components/Button.js
Labels: small

#5974 issue #5972 Hover action in the icons and logo of NavBar solved
  components/navbar/Navbar.js
Labels: small

#5982 fix: nav buttons and hover colours
  components/navbar/NavLink.js
  components/navbar/Navbar.js
Labels: medium

#5970 data: thesobercoder.json
  data/thesobercoder.json
Labels: ✍ chore: profile addition, large, LGTM

#5976 Update Ashutosh-s07.json
  data/Ashutosh-s07.json
Labels: ✍ chore: profile addition, small, LGTM

#5971 Create sagar1621.json
  data/sagar1621.json
Labels: ✍ chore: profile addition, large, LGTM

#5952 data: chetannada
  data/chetannada.json
Labels: ✍ chore: profile addition, large, LGTM

#5977 Update freedompraise.json
  data/freedompraise.json
Labels: ✍ chore: profile addition, medium, LGTM

#5973 data: AshishThakur
  data/ashishMECHA.json
Labels: ✍ chore: profile addition, large, LGTM

#5978 data: wrmacdonald
  data/wrmacdonald.json
Labels: ✍ chore: profile addition, medium, LGTM

#5997 data: Shiva953
  data/Shiva953.json
Labels: ✍ chore: profile addition, medium, LGTM

#5987 Data: Update thesobercoder.json
  data/thesobercoder.json
Labels: ✍ chore: profile addition, small, LGTM

#6000 Fixed a, blockquote, strong tags in darkmode
  components/mdx/BlockQuote.js
  components/mdx/ComponentStyle.js
  components/mdx/Strong.js
Labels: medium

#6005 Fix darkmode docs
  components/mdx/BlockQuote.js
  components/mdx/ComponentStyle.js
  components/mdx/Strong.js
Labels: medium

#5932 (feat): improved accessibility for modal box
  components/modals/ProfilePreview.js
Labels: large

#6009 Fix profile modal
  components/modals/ProfilePreview.js
Labels: medium

#6003 data: Pradumnasaraf
  data/Pradumnasaraf.json
Labels: ✍ chore: profile addition, small, LGTM

#5988 Zaid hassan patch 1
  data/zaid-hassan.json
Labels: ✍ chore: profile addition, large, LGTM

#5993 data:Cshiva773
  data/Cshiva773.json
Labels: ✍ chore: profile addition, medium, LGTM

#5989 Create soumik-saha.json
  data/soumik-saha.json
Labels: ✍ chore: profile addition, small, LGTM

#5950 data: Younus-Saberi
  data/Younus-Saberi.json
Labels: ✍ chore: profile addition, large, LGTM

#5901 data:aeejaz
  data/aeejaz.json
Labels: ✍ chore: profile addition, medium, LGTM

#6023 Li component moved to a separate file
  components/mdx/ComponentStyle.js
  components/mdx/Li.js
Labels: small

#6011 Updated Events Files
  data/SandipPalit/events/2022-08-27-Cloud-Community-Days-2022-Kolkata.json
  data/SandipPalit/events/2022-11-13-DevFest-2022-Kolkata.json
  data/SandipPalit/events/2023-02-11-TFUG-Kolkata-Reboot.json
  data/SandipPalit/events/2023-02-22-AWS-Innovate.json
  data/SandipPalit/events/2023-03-04-Being-Women-IWD-Celebration.json
  data/SandipPalit/events/2023-03-11-Dare-To-Be-an-Entrepreneur-IWD-2023.json
  data/SandipPalit/events/2023-04-22-MongoDB-Inaugural-Kickoff-Meetup.json
  data/SandipPalit/events/2023-05-07-Cloud-Community-Day-Kolkata-2023-Kolkata.json
Labels: ✍ chore: profile addition, large

#6015 data: arijit-pal
  data/arijit-pal.json
Labels: ✍ chore: profile addition, medium, LGTM

#6018 data:roy2pushkar
  data/roy2pushkar.json
Labels: ✍ chore: profile addition, medium, LGTM

#6032 data: anekemichael
  data/anekemichael.json
Labels: ✍ chore: profile addition, small, LGTM

#6033 Create Jp88Programmer.json
  data/Jp88Programmer.json
Labels: ✍ chore: profile addition, medium, LGTM

#6035 fix: alias imports in services
  services/github/getLocationByUsername.js
  services/profiles/findAllBasic.js
  services/profiles/findOneByUsernameBasic.js
  services/profiles/findOneByUsernameFull.js
  services/profiles/getLocation.js
  services/profiles/loadProfiles.js
Labels: medium

#6030 User profile reset issue - SearchBar
  pages/search.js
Labels: small, issue linked

#6031 [DOCS] Typo in the maintainers page #6001 fixed
  pages/docs/contributing/maintainers.mdx
Labels: small

#6039 fix: google analytics
  components/layouts/BlankLayout.js
  components/layouts/MultiLayout.js
  package-lock.json
  package.json
  pages/_app.js
Labels: large

#6041 fix: story points #5375
  pages/docs/contributing/labels.mdx
Labels: medium

#6047 data: RWUBAKWANAYO
  data/RWUBAKWANAYO.json
Labels: ✍ chore: profile addition, medium, LGTM

#6046 Update Younus-Saberi.json
  data/Younus-Saberi.json
Labels: ✍ chore: profile addition, large, LGTM
