Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-12, with the labels that each got.

#9860 data: mjr2595
  data/mjr2595.json
Labels: invalid, ✍ chore: profile

#9855 feat: show current character length on bio
  pages/account/manage/profile.js
Labels: issue linked

#9852 fix: replace deprecated key code
  components/tag/TagsInput.js
Labels: issue linked

#9823 fix: Re-ordering tags with Drag-and-Drop
  components/tag/TagsInput.js
  pages/account/manage/event/[[...data]].js
  pages/account/manage/profile.js
Labels: issue linked

#9875 data: mikebochenek
  data/mikebochenek.json
Labels: invalid, ✍ chore: profile

#9876 data: SaraviaMartin
  data/SaraviaMartin.json
Labels: invalid, ✍ chore: profile

#9870 fix: Milestone Icon Overflow by Removing Rounded Styling
  components/user/UserMilestone.js
Labels: issue linked

#9872 fix: Old screenshots on home page are replaced by new once
  pages/index.js
Labels: issue linked

#9896 Fix: progressbar background
  components/statistics/ProgressBar.js
Labels: issue linked

#9903 Data: Update mpotane.json dec2023
  data/mpotane.json
Labels: invalid, ✍ chore: profile

#9911 made some changes in my biodrop profile
  data/ibilalkayy.json
Labels: invalid, ✍ chore: profile

#9916 Create aayan14.json
  data/aayan14.json
Labels: invalid, ✍ chore: profile

#9921 data: khaymanii
  data/khaymanii.json
Labels: invalid, ✍ chore: profile

#9920 data: iSubhamMani
  data/iSubhamMani.json
Labels: invalid, ✍ chore: profile

#9918 Create 1708yash.json
  data/1708yash.json
Labels: invalid, ✍ chore: profile

#9922 Create aazad20.json
  data/aazad20.json
Labels: invalid, ✍ chore: profile

#9919 data:MutiatBash
  data/MutiatBash.json
Labels: invalid, ✍ chore: profile

#9924 creating a manmittiwade.json file
  data/Manmit124.json
Labels: invalid, ✍ chore: profile

#9894 [Fix]: Dragging Input field for Tags gives Error
  components/tag/TagsInput.js
Labels: issue linked

#9926 Create abdqudus.json
  data/abdqudus.json
Labels: invalid, ✍ chore: profile

#9928 added Vince-arch's data
  data/Vince-arch.json
Labels: invalid, ✍ chore: profile

#9925 Create anshsaxena1703.json
  data/anshsaxena1703.json
Labels: invalid, ✍ chore: profile

#9933 Create Moyo-Made.json
  data/Moyo-Made.json
Labels: invalid, ✍ chore: profile

#9937 fix: maintainers docs
  pages/docs/maintainers.mdx
Labels: issue linked, 📖 docs

#9936 Created Hydradaboss.json
  data/Hydradaboss.json
Labels: invalid, ✍ chore: profile

#9944 data: Olyray
  data/Olyray.json
Labels: invalid, ✍ chore: profile

#9950 data: destinedcodes
  data/DestinedCodes.json
Labels: invalid, ✍ chore: profile

#9945 data:Megagig
  data/Megagig.json
Labels: invalid, ✍ chore: profile

#9948 Create The-CodeINN.json
  data/The-CodeINN.json
Labels: invalid, ✍ chore: profile

#9949 data: phatwillis.json
  data/phatwillis.json
Labels: invalid, ✍ chore: profile

#9952 data: njogued
  data/njogued.json
Labels: invalid, ✍ chore: profile

#9954 data: de-maruader profile
  data/de-marauder.json
Labels: invalid, ✍ chore: profile

#9953 data: raoufcode
  data/fless-lab.json
Labels: invalid, ✍ chore: profile

#9955 thisisdishang patch 1
  data/thisisdishang.json
Labels: invalid, ✍ chore: profile

#9965 data: ruxy1212
  data/ruxy1212.json
Labels: invalid, ✍ chore: profile

#9957 Create WonahDshypoet.json
  data/WonahDshypoet.json
Labels: invalid, ✍ chore: profile

#9966 data: MuthoniMN
  data/MuthoniMN.json
Labels: invalid, ✍ chore: profile

#9968 data:josuembuyu
  data/josuembuyu.json
Labels: invalid, ✍ chore: profile

#9967 data: Olusoji01
  data/Olusoji01.json
Labels: invalid, ✍ chore: profile

#9969 data: tuhamworld
  data/tuhamworld.json
Labels: invalid, ✍ chore: profile

#9970 data: Odo-Peter
  data/Odo-Peter.json
Labels: invalid, ✍ chore: profile

#9977 data:emmyVon
  data/emmyVon.json
Labels: invalid, ✍ chore: profile

#9985 Tuhamworld patch 1
  data/tuhamworld.json
Labels: invalid, ✍ chore: profile

#9984 data: joelnyongesa.json
  data/joelnyongesa.json
Labels: invalid, ✍ chore: profile

#9982 data: shoetan
  data/Shoetan.json
  data/shoetan.json
Labels: invalid, ✍ chore: profile

#9973 Create fahmedo -profile.json
  data/Fahmedo.json
Labels: invalid, ✍ chore: profile

#9989 data: JustFelix-Dev
  data/JustFelix-Dev.json
Labels: invalid, ✍ chore: profile

#9994 data: davidemusi.
  data/davidemusi.json
Labels: invalid, ✍ chore: profile

#9996 data: Peter-TMK
  data/Peter-TMK.json
Labels: invalid, ✍ chore: profile

#9998 data: dirwolf
  data/dirwolf.json
Labels: invalid, ✍ chore: profile

#9974 data:emmyVon
  data/emmyVon.json
Labels: invalid, ✍ chore: profile

#9997 Adebaicy patch 2
  data/Adebaicy.json
Labels: invalid, ✍ chore: profile

#10005 Created new biodrop profile
  data/adetyaz.json
Labels: invalid, ✍ chore: profile

#10004 data: akintolarichard
  data/AkintolaRichard.json
Labels: invalid, ✍ chore: profile

#10006 data: gokul8747
  data/gokul8747.json
Labels: invalid, ✍ chore: profile

#10007 Create EmmanuelAjibokun.json
  data/EmmanuelAjibokun.json
Labels: invalid, ✍ chore: profile

#10008 Create Hikmahx.json
  data/Hikmahx.json
Labels: invalid, ✍ chore: profile

#10010 Create jorshimayor.json
  data/jorshimayor.json
Labels: invalid, ✍ chore: profile

#10000 fix: json profile source action
  .github/workflows/check-profile.yml
Labels: CI/CD

#10009 data: Olumarshal
  data/Olumarshal.json
Labels: invalid, ✍ chore: profile

#10013 data: codeInn001
  data/codeInn001.json
Labels: invalid, ✍ chore: profile

#10014 upload henrychris.json
  data/henrychris.json
Labels: invalid, ✍ chore: profile

#10016 data: iamaamunir
  data/iamaamunir.json
Labels: invalid, ✍ chore: profile

#10018 Create Emmanex01.json
  data/Emmanex01.json
Labels: invalid, ✍ chore: profile

#10022 data: Aditya-76
  data/Aditya-76.json
Labels: invalid, ✍ chore: profile

#10021 data: Riteshrajcloud
  data/Riteshrajcloud.json
Labels: invalid, ✍ chore: profile

#10024 Create Bakugo90.json
  data/Bakugo90.json
Labels: invalid, ✍ chore: profile

#10025 add new BioDrop user profile
  data/254guru.json
Labels: invalid, ✍ chore: profile

#10026 added another service link
  data/ibilalkayy.json
Labels: invalid, ✍ chore: profile

#10027 data: Mykelz
  data/Mykelz.json
Labels: invalid, ✍ chore: profile

#10030 data: Prashanth-bokkala
  data/Prashanth-bokkala.json
Labels: invalid, ✍ chore: profile

#10042 Create themanoz.json
  data/themanoz.json
Labels: invalid, ✍ chore: profile

#10049 Create orunto.json
  data/orunto.json
Labels: invalid, ✍ chore: profile

#10052 Update Dependencies
  package-lock.json
  package.json
Labels: dependencies

#10053 Update action dependencies
  .github/workflows/build.yml
  .github/workflows/check-assignee.yml
  .github/workflows/check-profile.yml
  .github/workflows/codeql.yml
  .github/workflows/data-filenames.yml
  .github/workflows/events.yml
  .github/workflows/json-check.yml
  .github/workflows/labels.yml
  .github/workflows/prettier.yml
  .github/workflows/release.yml
  .github/workflows/storybook.yml
  .github/workflows/testimonial.yml
  .github/workflows/vercel-preview.yml
  .github/workflows/vercel.yml
Labels: CI/CD

#9902 [Fix]: Modified Alert.js for Alert-info in dark mode
  components/Alert.js
Labels: issue linked

#10061 [Update data:sandramsc] Added and edited content
  data/sandramsc.json
Labels: invalid, ✍ chore: profile

#10059 data: fluentmoheshwar
  data/fluentmoheshwar.json
Labels: invalid, ✍ chore: profile

#10068 add jiafie7
  data/jiafie7.json
Labels: invalid, ✍ chore: profile

#10067 data: sawlew
  data/sawlew.json
Labels: invalid, ✍ chore: profile

#10066 Updated my profile with Milestones
  data/ibilalkayy.json
Labels: invalid, ✍ chore: profile

#10060 data: Kessi-ux
  data/Kessi-ux.json
Labels: invalid, ✍ chore: profile
