Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-01, with the labels that each got.

#2539 Beta tab sorting
  components/user/UserTabs.js
  data/eddiejaoude/testimonials/Akshu-on-github.json
  data/eddiejaoude/testimonials/CBID2.json
  pages/[username].js
Labels: ✍ chore: profile addition, large

#2560 data:imtiazpy
  data/imtiazpy.json
Labels: ✍ chore: profile addition, medium, LGTM

#2564 add profile to linkfree
  data/lucky-chap.json
Labels: ✍ chore: profile addition, medium, LGTM

#2563 data:gantoin
  data/gantoin.json
Labels: ✍ chore: profile addition, medium, LGTM

#2568 data: SurajJadhav-5
  data/SurajJadhav-5.json
Labels: ✍ chore: profile addition, medium, LGTM

#2567 Create Rahul-Prasad-07.json
  data/Rahul-Prasad-07.json
Labels: ✍ chore: profile addition, large, LGTM

#2573 Create Data aryasoni98.json
  data/aryasoni98.json
Labels: ✍ chore: profile addition, large, LGTM

#2575 data: krupalitrivedi
  data/krupalitrivedi.json
Labels: ✍ chore: profile addition, large, LGTM

#2565 added copy clipboard in "how-to-guides" under docs
  pages/docs/how-to-guides/bio.mdx
  pages/docs/how-to-guides/events.mdx
  pages/docs/how-to-guides/links.mdx
  pages/docs/how-to-guides/milestones.mdx
  pages/docs/how-to-guides/socials-shortcuts.mdx
  pages/docs/how-to-guides/statistics.mdx
  pages/docs/how-to-guides/tags.mdx
  pages/docs/how-to-guides/testimonials.mdx
Labels: large, waiting-for-reviewers

#2578 Update imtiazpy.json
  data/imtiazpy.json
Labels: ✍ chore: profile addition, small, LGTM

#2580 data: mocdaniel
  data/mocdaniel.json
  data/mocdaniel/events/2023-02-07-civo-navigate.json
Labels: ✍ chore: profile addition, large

#2579 [Feature] Popular profiles to display profile view count
  components/user/UserCard.js
Labels: medium

#2585 Add Display Stats to Avie's profile
  data/avie-dev.json
Labels: ✍ chore: profile addition, small, LGTM

#2590 Update juliafmorgado.json
  data/juliafmorgado.json
Labels: ✍ chore: profile addition, small, LGTM

#2589 data: krshkun
  data/krshkodes.json
  data/krshkun.json
Labels: ✍ chore: profile addition, large

#2591 Patch 2
  data/juliafmorgado/events/2023-02-07-civo-navigate.json
  data/juliafmorgado/events/2023-04-18-kubecon-eu.json
  data/juliafmorgado/events/2023-05-17-kubehuddle.json
Labels: ✍ chore: profile addition, large

#2588 Created my LinkFree profile
  data/shyam0705.json
Labels: ✍ chore: profile addition, large, LGTM

#2592 Update Arindam200.json
  data/Arindam200.json
Labels: ✍ chore: profile addition, large, LGTM

#2595 Fixed Avatar of Arindam200.json
  data/Arindam200.json
Labels: ✍ chore: profile addition, small, LGTM

#2593 fix: where to put links confusion
  pages/docs/quickstart.mdx
Labels: ✨ goal: improvement, 📄 aspect: text, small

#2599 data: Yagazie-davidson
  data/Yagazie-davidson.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2597 feat: add personal, community and event
  data/Schrodinger-Hat.json
  data/Schrodinger-Hat/events/2023-03-24-os-day.json
  data/davideimola.json
Labels: ✍ chore: profile addition, large

#2601 Added OlojaMuyiwa.json
  data/OlojaMuyiwa.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2602 data:Kaleem-abdull
  data/Kaleem-abdull.json
Labels: ✍ chore: profile addition, small, LGTM

#2571 Created my LinkFree profile
  data/Shield01.json
Labels: ✍ chore: profile addition, large, LGTM

#2596 Couldn't sleep so updating profile
  data/loftwah.json
Labels: ✨ goal: improvement, ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2608 data:Patelrahul4884
  data/Patelrahul4884.json
Labels: ✍ chore: profile addition, medium, LGTM

#2609 Added website
  data/fluentmoheshwar.json
Labels: ✍ chore: profile addition, small, LGTM

#2610 data:rohinish404
  data/rohinish404.json
Labels: ✍ chore: profile addition, medium, LGTM

#2612 Updated My Profile
  data/accodes21.json
Labels: ✍ chore: profile addition, medium, LGTM

#2611 Added personal linkfree page json
  data/abhick-dev.json
Labels: ✍ chore: profile addition, medium, LGTM

#2584 data: khalidx3
  data/khalidx3.json
Labels: ✍ chore: profile addition, medium, LGTM

#2615 abhijeet-26.json file added
  data/abhijeet-26.json
Labels: ✍ chore: profile addition, large, LGTM

#2613 data:SivaReddy184
  data/SivaReddy184.json
Labels: ✍ chore: profile addition, medium, LGTM

#2614 data: aravindraveendran7
  data/aravindraveendran7.json
Labels: ✍ chore: profile addition, medium, LGTM

#2620 Updated My Profile
  data/gurjeetsinghvirdee.json
Labels: ✍ chore: profile addition, large, LGTM

#2625 data: Enable testimonials on Pradumnasaraf's profile
  data/Pradumnasaraf.json
Labels: ✍ chore: profile addition, small, LGTM

#2628 Added Codepen link to the links
  data/imtiazpy.json
Labels: ✍ chore: profile addition, small, LGTM

#2627 Testimonial button added to profile page
  components/user/UserCard.js
  pages/[username].js
  pages/docs/how-to-guides/testimonials.mdx
  pages/index.js
Labels: large

#2629 Add testimonial
  data/juliafmorgado.json
Labels: ✍ chore: profile addition, medium, LGTM

#2635 Update AliReza1083.json
  data/AliReza1083.json
Labels: ✍ chore: profile addition, small, LGTM

#2643 data: Maina401
  data/maina401.json
Labels: ✍ chore: profile addition, large, LGTM

#2636 Added my LinkFree profile
  data/nanthakumaran-s.json
Labels: ✍ chore: profile addition, large, LGTM

#2621 data: thebarshablog
  data/thebarshablog.json
  data/thebarshablog/events/2023-05-16-kubehuddle-conference.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2644 Aravindraveendran7 patch 3
  data/aravindraveendran7.json
Labels: ✍ chore: profile addition, small, LGTM

#2638 issue #2637 fix
  next.config.mjs
Labels: ✍ chore: profile addition, small

#2658 data:ShreeyashGarde
  data/ShreeyashGarde.json
Labels: ✍ chore: profile addition, medium, LGTM

#2655 removed profiles from popular whose stats are not public
  pages/api/users/popular.js
Labels: small

#2660 GitHub Action testimonial should valid json before committing file #2659
  .github/workflows/testimonial.yml
Labels: small

#2657 Updated icon reference to Pradumna's website
  data/Pradumnasaraf.json
Labels: ✍ chore: profile addition, small

#2668 data:SamyabrataMaji
  data/samyabrata-maji.json
Labels: ✍ chore: profile addition, medium, LGTM

#2671 data: jarek-pacocha
  data/jarek-pacocha.json
Labels: ✍ chore: profile addition, large, LGTM

#2634 Yet another branch
  data/xperience001.json
Labels: ✍ chore: profile addition, large, LGTM

#2681 Added link to my blog in the Links and Milestones section
  data/CBID2.json
Labels: ✍ chore: profile addition, medium, LGTM

#2684 add testimonial from CBID2
  data/loftwah.json
Labels: ✍ chore: profile addition, small, LGTM

#2683 Added a testimonial section
  data/CBID2.json
Labels: ✍ chore: profile addition, small, LGTM

#2605 I have added filter options to see events virtual/in person
  pages/events.js
Labels: small

#2688 Add Line Break To Docs
  pages/docs/index.js
Labels: small

#2690 Added my profile
  data/haideralipunjabi.json
Labels: ✍ chore: profile addition, large, LGTM

#2692 data:tobySolutions
  data/tobySolutions.json
Labels: ✍ chore: profile addition, large, LGTM

#2693 data:sharipoff-0-1
  data/sharipoff-0-1.json
Labels: ✍ chore: profile addition, medium, LGTM

#2694 Add my profile
  data/marianaWest.json
Labels: ✍ chore: profile addition, medium, LGTM

#2699 data:Ellah120
  data/Ellah120.json
Labels: ✍ chore: profile addition, medium, LGTM

#2700 Update profile
  data/MadhuSaini22.json
Labels: ✍ chore: profile addition, medium, LGTM

#2702 Updated my links
  data/imtiazpy.json
Labels: ✍ chore: profile addition, small, LGTM

#2706 Add senali-d profile
  data/senali-d.json
Labels: ✍ chore: profile addition, large, LGTM

#2707 data:KimberlyPangilinan
  data/KimberlyPangilinan.json
Labels: ✍ chore: profile addition, large, LGTM

#2709 data: RobRuizR
  data/RobRuizR.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2716 data: krupalitrivedi
  data/krupalitrivedi.json
Labels: ✍ chore: profile addition, small, LGTM

#2719 data: sfolador
  data/sfolador.json
Labels: ✍ chore: profile addition, medium, LGTM

#2679 Closes issue #2678
  data/OlojaMuyiwa.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2713 data: ShanmukhiKairuppala
  data/ShanmukhiKairuppala.json
Labels: ✍ chore: profile addition, medium, LGTM

#2729 Ayush sarode patch 1 1
  data/AyushSarode.json
Labels: ✍ chore: profile addition, large, LGTM

#2722 data: dannyhw
  data/dannyhw.json
Labels: ✍ chore: profile addition, large, LGTM

#2723 data:A10-g
  data/A10-g.json
Labels: ✍ chore: profile addition, medium, LGTM

#2731 data: Pradumnasaraf
  data/Pradumnasaraf.json
Labels: ⭐ goal: addition, small, LGTM

#2747 data:BaileyLuu
  data/BaileyLuu.json
Labels: ✍ chore: profile addition, medium, LGTM

#2744 data: Ugyenwangdi
  data/Ugyenwangdi.json
Labels: ✍ chore: profile addition, large, LGTM

#2743 Update Oyebolade.json
  data/Oyebolade.json
Labels: 🛠 goal: fix, small, LGTM

#2742 added profile
  data/iamunnip.json
Labels: ✍ chore: profile addition, large, LGTM

#2738 data:netteNz Merge
  data/netteNz.json
Labels: ✍ chore: profile addition, medium, LGTM

#2737 data:Ayaan49
  data/Ayaan49.json
Labels: ✍ chore: profile addition, medium, LGTM

#2736 data: AftabAhmedAbro.json
  data/AftabAhmedAbro.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2705 New link(Updated With Milestones)
  data/AliJafriETH.json
Labels: ✍ chore: profile addition, large, LGTM

#2734 Adding Mslepko user
  data/mslepko.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2765 Toby solutions patch 4
  data/tobySolutions.json
Labels: ✍ chore: profile addition, small, LGTM

#2711 data: SoumyadeepOSD
  data/SoumyadeepOSD.json
Labels: ✍ chore: profile addition, medium, LGTM

#2749 data: shubhsharma19
  data/shubhsharma19.json
Labels: ✍ chore: profile addition, large, LGTM

#2770 data:Avi-88
  data/Avi-88.json
Labels: ✍ chore: profile addition, large, LGTM

#2730 data:Ellah120
  data/Ellah120.json
Labels: 💻 aspect: code, 🛠 goal: fix, small, LGTM

#2751 data:HarshPanchal26
  data/HarshPanchal26.json
Labels: ✍ chore: profile addition, large, LGTM

#2760 created Elozino.json
  data/Elozino.json
Labels: ✍ chore: profile addition, medium, LGTM

#2761 data: shwetavish
  data/shwetavish.json
Labels: ✍ chore: profile addition, medium, LGTM

#2763 Update LinuxGamer.json
  data/LinuxGamer.json
Labels: ✍ chore: profile addition, small, LGTM

#2764 data:utkarsh1311
  data/utkarsh1311.json
Labels: ✍ chore: profile addition, large, LGTM

#2773 data:Mvishal123
  data/Mvishal123.json
Labels: ✍ chore: profile addition, large, LGTM

#2762 MirzaBaig
  data/I-MirzaBaig.json
Labels: ✍ chore: profile addition, large, LGTM

#2752 data: Abhishekgupta47
  data/Abhishekgupta47.json
Labels: ✍ chore: profile addition, large, LGTM

#2649 updated images in quickstart.mdx
  pages/docs/quickstart.mdx
Labels: ✨ goal: improvement, 📄 aspect: text, small

#2727 angel-mba-branch
  data/Michelle031.json
Labels: ✍ chore: profile addition, medium, LGTM

#2775 data:suchakra012
  data/suchakra012.json
Labels: ✍ chore: profile addition, medium, LGTM

#2750 data:rishabhverma54321
  data/rishabhverma54321.json
Labels: ✍ chore: profile addition, medium, LGTM

#2687 Event filters
  components/event/EventCard.js
  components/event/EventKey.js
  components/user/UserEvents.js
  data/eddiejaoude/events/2023-09-18-talk-infobip.json
  data/juliafmorgado/events/2023-02-07-civo-navigate.json
  pages/docs/how-to-guides/events.mdx
  pages/events.js
Labels: ✍ chore: profile addition, large

#2790 data: RitaMwas
  data/RitaMwas.json
Labels: ✍ chore: profile addition, medium, LGTM

#2776 data:AasthaShahCodes
  data/AasthaShahCodes.json
Labels: ✍ chore: profile addition, medium

#2745 data: ADITYADAS1999
  data/ADITYADAS1999.json
Labels: ✍ chore: profile addition, large, LGTM

#2721 Profile update
  data/Saha-7.json
Labels: ✍ chore: profile addition, medium, LGTM

#2797 My profile
  data/muhammadanas0716.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#2799 data: king0203
  data/king0203.json
Labels: ✍ chore: profile addition, medium, LGTM

#2717 data: AamirxShaikh
  data/aamirxshaikh.json
Labels: ✍ chore: profile addition, large, LGTM

#2725 data:iamVP7
  data/iamVP7.json
Labels: ✍ chore: profile addition, large, LGTM

#2766 data:Crazycoder122
  data/Crazycoder122.json
Labels: ✍ chore: profile addition, medium, LGTM

#2789 data: OmerFI
  data/OmerFI.json
Labels: ✍ chore: profile addition, medium, LGTM

#2767 data: krshkun
  data/krshkun.json
Labels: ✨ goal: improvement, large, LGTM

#2806 Aasthashahcodes patch 1
  data/AasthaShahCodes.json
Labels: ✍ chore: profile addition, small

#2785 Updated my profile
  data/samyabrata-maji.json
Labels: ✍ chore: profile addition, large, LGTM

#2804 data:Aayush987
  data/Aayush987.json
Labels: ✍ chore: profile addition, medium, LGTM

#2784 data:YashPimple
  data/YashPimple.json
Labels: ✍ chore: profile addition, large, LGTM

#2777 data:Harsh971
  data/Harsh971.json
Labels: ✍ chore: profile addition, large, LGTM

#2801 data: priyapahwa
  data/priyapahwa.json
Labels: ✍ chore: profile addition, large, LGTM

#2800 data: RoHit4100
  data/RoHit4100.json
Labels: ✍ chore: profile addition, medium, LGTM

#2782 Update my profile
  data/gurjeetsinghvirdee.json
Labels: ⭐ goal: addition, ✍ chore: profile addition, small, LGTM

#2780 Data : KrishChopra22 ✅
  data/KrishChopra22.json
Labels: ✍ chore: profile addition, large, LGTM

#2754 data: skmominali17
  data/skmominali17.json
Labels: ✍ chore: profile addition, medium, LGTM

#2748 data: Omar8345
  data/Omar8345.json
Labels: ✍ chore: profile addition, large, LGTM

#2811 data: added lonebot's profile
  data/lonebots.json
Labels: ✍ chore: profile addition, large, LGTM

#2810 data:nowayski
  data/nowayski.json
Labels: ✍ chore: profile addition, large, LGTM

#2813 Add testimonial
  data/juliafmorgado.json
Labels: ✍ chore: profile addition, small, LGTM

#2809 Create kelvinparmar.json
  data/kelvinparmar.json
Labels: ✍ chore: profile addition, medium, LGTM

#2817 data:mohdfarhannawaz
  data/mohdfarhannawaz.json
Labels: ✍ chore: profile addition, large, LGTM

#2821 data:A10-g
  data/A10-g.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#2803 feat: discover random profiles #2558
  components/navbar/Navbar.js
  pages/api/users/discover.js
  pages/api/users/popular.js
  pages/discover.js
  pages/popular.js
  tests/discover.spec.js
  tests/popular.spec.js
Labels: large, kudos, tests

#2796 fix-readMe
  README.md
Labels: small

#2792 Add esau-morais to LinkFree
  data/esau-morais.json
Labels: ✍ chore: profile addition, medium, LGTM

#2783 data:VaibhavSingh
  data/VaibhavSinghDev.json
Labels: ✍ chore: profile addition, large, LGTM

#2816 Updated: grammar and spelling checks
  README.md
Labels: medium

#2793 data: BruceWangyq
  data/BruceWangyq.json
Labels: ✍ chore: profile addition, large, LGTM

#2787 data:harsitagarwalla187
  data/harsitagarwalla187.json
Labels: ✍ chore: profile addition, medium, LGTM

#2826 data: Trikcode
  data/Trikcode.json
Labels: ✍ chore: profile addition, large, LGTM

#2786 data: ubaniIsaac
  data/ubaniIsaac.json
Labels: ✍ chore: profile addition, large, LGTM

#2807 data:ssvali
  data/ssvali.json
Labels: ✍ chore: profile addition, medium, LGTM

#2824 Ayush sarode patch 1 2
  data/AyushSarode.json
Labels: ✍ chore: profile addition, small, LGTM

#2798 data: Ravi-Rsankar
  data/Ravi-Rsankar.json
Labels: ✍ chore: profile addition, medium, LGTM

#2827 data: marlonaesparza
  data/marlonaesparza.json
Labels: ✍ chore: profile addition, medium, LGTM

#2841 Changed the Typo on line 128
  pages/docs/quickstart.mdx
Labels: 🛠 goal: fix, 📄 aspect: text, small

#2838 data : Yashkapure06
  data/Yashkapure06.json
Labels: ✍ chore: profile addition, medium, LGTM

#2842 data:riteshgharat
  data/riteshgharat.json
Labels: ✍ chore: profile addition, large, LGTM

#2843 Aasthashahcodes patch 1
  data/AasthaShahCodes.json
Labels: ✍ chore: profile addition, small

#2845 data:karntheai
  data/karntheai.json
Labels: ✍ chore: profile addition, large, LGTM

#2851 feat: total and active users
  pages/api/statistics/totals.js
  pages/index.js
Labels: medium
