Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-09, with the labels that each got.

#8889 feat: Sort repo page
  components/form/Select.js
  pages/api/repos.js
  pages/repos.js
Labels: issue linked

#8887 Fix: use double bang operator to convert value to either true or false
  components/user/UserMini.js
Labels: issue linked

#8855 Fix: added margin to manage link page
  components/Button.js
  components/user/UserRepos.js
  pages/account/manage/links.js
  pages/account/manage/repos.js
Labels: issue linked

#8905 In Playwright tests, explicitly wait for link clicks to complete
  tests/changelog.spec.js
  tests/discover.spec.js
  tests/docs/docs.spec.js
  tests/events.spec.js
  tests/home.spec.js
  tests/playground.spec.js
  tests/profile.spec.js
  tests/repos.spec.js
  tests/search.spec.js
Labels: tests

#8904 feat: filter options for event section
  components/user/UserEvents.js
  pages/account/manage/events.js
  pages/api/account/manage/events.js
Labels: issue linked

#8624 docs: support for debugging LinkFree in VS Code
  components/layouts/DocsLayout.js
  pages/docs/environments/debugging-in-vscode.mdx
Labels: issue linked, 📖 docs

#8912 data: SreejitSengupta
  data/Sreejit-Sengupto.json
  data/sreejit-sengupto.json
Labels: ✍ chore: profile

#8913 Update toukirkhan.json
  data/toukirkhan.json
Labels: ✍ chore: profile

#8917 data:StarKnightt
  data/StarKnightt.json
Labels: ✍ chore: profile

#8914 Create XanderRubio.json
  data/XanderRubio.json
Labels: ✍ chore: profile

#8938 feat: added profile picture on manage testimonials
  pages/account/manage/testimonials.js
Labels: issue linked

#8919 feat: create Label component
  components/IconSearch.js
  components/form/Input.js
  components/form/Label.js
  components/form/Select.js
  components/form/Textarea.js
Labels: issue linked

#8925 Fix milestones order issue
  pages/api/account/manage/milestones.js
  pages/api/profiles/[username]/index.js
Labels: issue linked

#8956 data: p1kalys
  data/p1kalys.json
Labels: ✍ chore: profile

#8958 Delete data/shyamtawli.json
  data/shyamtawli.json
Labels: ✍ chore: profile

#8957 data: Update Viveksati5143.json
  data/Viveksati5143.json
Labels: ✍ chore: profile

#8966 data:Sxamoecode
  data/Sxamoecode.json
Labels: ✍ chore: profile

#8951 Create maithrivh.json
  data/maithrivh.json
Labels: ✍ chore: profile

#8977 data: Nwakaego-Ego.json
  data/Nwakaego-Ego.json
Labels: ✍ chore: profile

#8978 Update ShanmukhiKairuppala.json
  data/ShanmukhiKairuppala.json
Labels: ✍ chore: profile

#8981 Jossse69 patch 1
  data/jossse69.json
Labels: ✍ chore: profile

#8982 Update Gitpod
  .gitpod.yml
  README.md
  pages/docs/environments/gitpod.mdx
Labels: 📖 docs

#8945 [FEATURE] (changed bg): changed bg from #000000 to #121212 in dark mode
  components/Testimonials.js
  components/layouts/MultiLayout.js
  pages/docs/index.js
  pages/index.js
  pages/roadmap.js
  tailwind.config.js
Labels: issue linked

#8854 fix: glow animation in Links section
  components/layouts/MultiLayout.js
Labels: issue linked

#8921 fix: All events should show every event instead of no events
  components/user/UserEvents.js
Labels: issue linked

#9010 data: natlmartin
  data/natlmartin.json
Labels: ✍ chore: profile

#9005 data : created UlbertAO json
  data/UlbertAO.json
Labels: ✍ chore: profile

#9013 Modification
  data/ibilalkayy.json
Labels: ✍ chore: profile

#9015 data: malaviya-parth
  data/malaviya-parth.json
Labels: ✍ chore: profile

#9019 Update roberanegussie.json
  data/roberanegussie.json
Labels: ✍ chore: profile

#9023 Create VivekBaldha0712.json
  data/VivekBaldha0712.json
Labels: ✍ chore: profile

#9002 fix: update the biodrop-cli
  package-lock.json
  package.json
Labels: dependencies

#9016 docs: update the cli docs
  components/layouts/DocsLayout.js
  pages/docs/environments/biodrop-cli.mdx
  pages/docs/environments/linkfree-cli.mdx
Labels: 💻 aspect: code, 📄 aspect: text, BiopDrop CLI, 📖 docs

#9033 fix: map usermarker link in darkmode
  components/map/UserMarker.js
Labels: issue linked

#9031 data: Harsh-Trivedi03
  data/Harsh-Trivedi03.json
Labels: ✍ chore: profile

#8999 URL parameter update when search bar becomes empty
  pages/search.js
Labels: issue linked

#8953 fix:fixed the unable to save a link without specifying an icon
  pages/account/manage/link/[[...data]].js
Labels: issue linked

#9035 Update MaorBemdoo.json
  data/MaorBemdoo.json
Labels: ✍ chore: profile

#8960 [Feature] Added Confirmation Dialog for Repo Deletion
  components/user/UserRepos.js
  pages/account/manage/repos.js
Labels: issue linked

#8995 Update react-icons & migrate to Font Awesome 6
  components/Footer.js
  components/Icon.js
  components/IconSearch.js
  components/event/EventCard.js
  components/event/EventKey.js
  components/navbar/Navbar.js
  components/user/UserMilestone.js
  components/user/UserProfile.js
  config/app.json
  package-lock.json
  package.json
  pages/[username].js
  pages/account/statistics.js
  pages/events.js
  pages/icons.js
  pages/index.js
  tests/icon.spec.js
Labels: tests, dependencies

#9048 chore: remove nickytonline's data
  data/nickytonline.json
Labels: ✍ chore: profile

#9044 Fix QR-Code layout cut issue in small screens
  components/Modal.js
Labels: issue linked

#8954 feat: add Tags Input feature
  components/tag/TagsInput.js
  pages/account/manage/profile.js
Labels: issue linked

#8944 fix: premium upgrade link
  .env.docker
  .env.example
  .github/workflows/vercel-preview.yml
  components/navbar/Navbar.js
  config/schemas/clientSchema.js
  models/User.js
  pages/account/manage/premium.js
  pages/api/auth/[...nextauth].js
  pages/api/stripe.js
  pages/api/system/stripe.js
  pages/docs/terms.mdx
  pages/icons.js
  pages/index.js
  pages/pricing.js
  tests/icon.spec.js
Labels: tests, CI/CD, 📖 docs, models

#9058 fix: upgrade the BioDrop CLI
  package-lock.json
  package.json
Labels: BiopDrop CLI, dependencies

#8998 Adding Color picker for Events
  components/form/Input.js
  pages/account/manage/event/[[...data]].js
  pages/index.js
Labels: issue linked

#9063 Delete data/usmangt.json and the folder
  data/usmangt.json
Labels: ✍ chore: profile

#9070 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#9078 data: indigo423 adding publication in milestones
  data/indigo423.json
Labels: ✍ chore: profile

#9075 fix update twitter icon in footer
  components/Footer.js
Labels: issue linked

#9083 data: LinkedIn Profile
  data/J-CODE07.json
Labels: ✍ chore: profile

#9087 Update jugaaadd.json
  data/jugaaadd.json
Labels: ✍ chore: profile

#9091 Project Added
  data/kirtankp.json
Labels: ✍ chore: profile

#9092 Docs open source roadmap
  components/DataList.js
  components/Footer.js
  components/layouts/DocsLayout.js
  pages/docs/open-source-roadmap/checks.js
  pages/docs/open-source-roadmap/glossary.js
  pages/docs/open-source-roadmap/how-to-contribute.js
  pages/docs/open-source-roadmap/index.js
  pages/docs/open-source-roadmap/running-the-project-locally.js
  pages/docs/open-source-roadmap/what-next.js
  pages/docs/open-source-roadmap/what-to-contribute.js
  pages/docs/open-source-roadmap/what-why.js
  pages/docs/open-source-roadmap/where.js
Labels: 📖 docs

#9082 Test: find the profile after providing concise name - Closes #9081
  tests/search.spec.js
Labels: tests, issue linked

#9106 data:allexgut
  data/allexgut.json
Labels: ✍ chore: profile

#9123 data: Mayank-Sharma17
  data/Mayank-Sharma17.json
Labels: ✍ chore: profile

#9118 data: Gabriel-Giani
  data/Gabriel-Giani.json
Labels: ✍ chore: profile

#9120 fix: backspace key handling with no tags
  components/tag/TagsInput.js
Labels: issue linked

#9107 docs: BioDrop homePage will open in new tab
  pages/docs/quickstart-forms.mdx
Labels: issue linked, 📖 docs

#9134 data: Andrewyithub
  data/Andrewyithub.json
Labels: ✍ chore: profile

#9079 feat: remove a stat info from landing page
  pages/index.js
Labels: issue linked

#8896 data: fix testimonials that i broke because i had changed my username…
  data/EddieHubCommunity/testimonials/xkrishguptaa.json
  data/Pradumnasaraf.json
  data/Pradumnasaraf/testimonials/xkrishguptaa.json
  data/avie-dev.json
  data/avie-dev/testimonials/xkrishguptaa.json
  data/eddiejaoude/testimonials/xkrishguptaa.json
  data/krishstwt.json
  data/thebarshablog.json
  data/thebarshablog/testimonials/xkrishguptaa.json
  data/tobySolutions.json
  data/tobySolutions/testimonials/xkrishguptaa.json
  data/web3community.json
  data/web3community/testimonials/krishstwt.json
  data/xkrishguptaa/testimonials/LinuxGamer.json
  data/xkrishguptaa/testimonials/MadhuSaini22.json
  data/xkrishguptaa/testimonials/eddiejaoude.json
  data/xkrishguptaa/testimonials/loftwah.json
  data/xkrishguptaa/testimonials/shubhsharma19.json
  data/xkrishguptaa/testimonials/tobySolutions.json
Labels: ✍ chore: profile

#9143 Test: search persistence
  tests/search.spec.js
Labels: tests, issue linked

#9148 Update samikshakute.json
  data/samikshakute.json
Labels: ✍ chore: profile

#9074 data: HameedKareem
  data/maxton4life.json
Labels: ✍ chore: profile

#9160 Change Order Of Social Links
  data/SaarthakMaini.json
Labels: ✍ chore: profile

#9156 fix: testimonials for profiles with forms
  .github/workflows/vercel-pr-preview.yml
  .github/workflows/vercel-preview.yml
  .github/workflows/vercel.yml
  pages/api/system/testimonials-forms.js
Labels: issue linked, CI/CD

#9007 feat: add tabs to url
  components/user/themes/UserTabs.js
Labels: issue linked

#9168 Project Added
  data/kirtankp.json
Labels: ✍ chore: profile

#9169 data: Added testimonial section
  data/Viveksati5143.json
Labels: ✍ chore: profile

#9173 data: bL34cHig0
  data/bL34cHig0.json
Labels: ✍ chore: profile

#9174 feat: add tabs to url (Fix pr 9007)
  components/Tabs.js
  components/user/themes/UserTabs.js
  pages/changelog.js
  tests/profile.spec.js
Labels: tests, issue linked

#9154 Fix: On Mobile hide: stats, add testimonial button, and tags
  pages/[username].js
Labels: issue linked

#9182 Update bL34cHig0.json
  data/bL34cHig0.json
Labels: ✍ chore: profile

#9112 [Fix] : added warning to manage event page
  components/user/UserEvents.js
Labels: issue linked

#9157 feat: added a standard placement of price on events
  components/event/EventCard.js
Labels: issue linked

#9193 ci(release): squash merge release details
  .github/workflows/release.yml
Labels: CI/CD

#9186 Update bL34cHig0.json
  data/bL34cHig0.json
Labels: ✍ chore: profile

#9176 data: d4community
  data/D4-Community.json
Labels: ✍ chore: profile

#9181 fix: accessibility on tags input
  components/tag/TagsInput.js
Labels: issue linked

#9205 fix: removed optional zod schema from name and bio
  config/schemas/jsonProfileSchemas.js
Labels: issue linked

#9210 feat: dedup repos page
  components/user/UserRepos.js
  pages/api/repos.js
  pages/repos.js
Labels: issue linked

#9217 fix: test to check repo tab
  tests/profile.spec.js
  tests/setup/global-setup.js
Labels: tests
