Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-11, with the labels that each got.

#9639 update dependencies
  package-lock.json
  package.json
Labels: dependencies

#9631 issue fix #9581: heading strucutre fails WCAG 2.2AA- skipped heading
  components/DataList.js
  components/user/UserHorizontal.js
  components/user/UserLinks.js
  components/user/UserMilestone.js
  components/user/UserTestimonials.js
  package-lock.json
  tests/data/_test-profile-user-6.json
Labels: tests, issue linked

#9720 <chore> : I have deleted my data/devanshukoli.json file from /data folder.
  data/Devanshukoli.json
Labels: invalid, ✍ chore: profile

#9725 data: issamahwach.json
  data/issamahwach.json
Labels: invalid, ✍ chore: profile

#9723 chore: remove the Vercel PR preview action
  .github/workflows/vercel-pr-preview.yml
Labels: CI/CD

#9722 chore: remove GHCR Action
  .github/workflows/publish-ghcr.yml
Labels: CI/CD

#9715 Updated BioDrop Map Image
  pages/index.js
Labels: issue linked

#9714 Updated the QuickStart-JSON documentation with new BioDrop images
  pages/docs/quickstart-json.mdx
Labels: issue linked, 📖 docs

#9726 fix: Navbar overlaps with Icon notification
  components/layouts/MultiLayout.js
Labels: issue linked

#9732 fix: navbar menu layering bug in dark mode
  components/navbar/Navbar.js
Labels: issue linked

#9736 chore: improve feature issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: CI/CD

#9739 Fix Search tests
  tests/search.spec.js
Labels: tests, issue linked

#9436 Feat custom domain
  .env.example
  .github/workflows/vercel-preview.yml
  components/Button.js
  components/form/Input.js
  components/layouts/DocsLayout.js
  config/schemas/serverSchema.js
  middleware.js
  models/Profile.js
  pages/[username].js
  pages/account/manage/links.js
  pages/account/manage/premium.js
  pages/account/manage/repos.js
  pages/account/onboarding/index.js
  pages/api/account/manage/settings.js
  pages/api/profiles/[username]/index.js
  pages/api/search/[domain].js
  pages/changelog.js
  pages/docs/premium/auto.mdx
  pages/docs/premium/customisation.mdx
  pages/docs/premium/domain.mdx
  pages/pricing.js
Labels: CI/CD, 📖 docs, models

#9719 fix: heading strucuture fails WCAG 2.2AA (#9631)
  components/DataList.js
  components/user/UserHorizontal.js
  components/user/UserLinks.js
  components/user/UserMilestone.js
  components/user/UserTestimonials.js
  tests/profile.spec.js
  tests/search.spec.js
Labels: tests

#9655 feat: improving icons page
  pages/icons.js
Labels: issue linked

#9751 Updated my Porfilio URL
  data/Chamberezigbo.json
Labels: invalid, ✍ chore: profile

#9753 Update Markdown / MDX dependeicies to new Major Version
  components/Markdown.js
  package-lock.json
  package.json
  pages/map.js
Labels: dependencies

#9752 Icon search page improvements
  pages/icons.js
  tests/icon.spec.js
Labels: tests

#9766 data: JeremyMorgan
  data/JeremyMorgan.json
Labels: invalid, ✍ chore: profile

#9771 fix: github action for profile db check
  .github/workflows/check-profile.yml
  package-lock.json
  pages/changelog.js
Labels: CI/CD

#9773 Feat reload pwa
  .github/workflows/vercel-preview.yml
  pages/[username].js
Labels: CI/CD

#9770 Reduce bg-size on :after to fix Safari bug
  styles/animation.module.css
Labels: issue linked

#9787 Updated kshitij9896.json
  data/kshitij9896.json
Labels: invalid, ✍ chore: profile

#9508 Fixes Using Chips in the "add Tags" section #9103
  components/tag/TagsInput.js
  pages/account/manage/event/[[...data]].js
  pages/account/manage/profile.js
Labels: issue linked

#9789 feat: New 'Steps to Reproduce' section in bug template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: issue linked, CI/CD

#9703 Account Button replaced with User's GitHub Profile Picture
  components/navbar/Navbar.js
Labels: issue linked

#9513 Fixed : Docs URL refresh when using side nav issue #9486
  components/navbar/SideNav.js
Labels: issue linked

#9799 fix: homepage video
  pages/index.js
Labels: issue linked

#9248 fix: resolve mobile keyboard fluctuation during search
  pages/search.js
  tests/search.spec.js
Labels: tests, issue linked

#9805 fix: reduce link name length to min 1
  models/Link.js
  pages/account/manage/link/[[...data]].js
Labels: models

#9820 fix: duplicate tags issue using set constructor
  pages/account/manage/event/[[...data]].js
  pages/account/manage/profile.js
Labels: issue linked

#9825 Create Aishanya12.json
  data/Aishanya12.json
Labels: invalid, ✍ chore: profile

#9838 data:Arturo23FJ
  data/Arturo23FJ.json
Labels: invalid, ✍ chore: profile

#9832 data: shaileshthakur1
  data/shaileshthakur1.json
Labels: invalid, ✍ chore: profile

#9847 fix: null icons
  components/Icon.js
  pages/api/icons.js
  tests/icon.spec.js
Labels: tests

#9762 [FEATURE] Improvement - char limit on tags
  components/tag/TagsInput.js
  pages/account/manage/event/[[...data]].js
  pages/account/manage/profile.js
  pages/docs/how-to-guides/editing-forms.mdx
Labels: issue linked, 📖 docs

#9850 "remove my json based on the new biodrop guidelines"
  data/ABHIGYAN-MOHANTA.json
Labels: invalid, ✍ chore: profile

#9500 feat: enable user profile embed on external site
  components/embeds/external/Profile.js
  components/embeds/internal/Youtube.js
  components/user/UserProfile.js
  package-lock.json
  package.json
  pages/[username].js
  pages/api/profiles/[username]/embed.js
  pages/docs/how-to-guides/editing-forms.mdx
  pages/docs/how-to-guides/editing-json.mdx
  pages/docs/how-to-guides/json-to-forms.mdx
  pages/docs/quickstart-forms.mdx
  pages/docs/quickstart-json.mdx
  public/Inter-Bold.ttf
  public/Inter-Regular.ttf
  services/utils/twemoji.js
Labels: issue linked, dependencies, 📖 docs

#9814 fix: z-index issue of confirmation dialog modal in dark mode
  components/ConfirmDialog.js
Labels: issue linked
