Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-08, with the labels that each got.

#8427 Quarkyy77 patch 1
  data/Quarkyy77.json
Labels: ✍ chore: profile

#8426 data: AxelGarciaK
  data/AxelGarciaK.json
Labels: ✍ chore: profile

#8225 feat: GitHub repo to profile
  components/account/manage/Navigation.js
  components/user/UserRepos.js
  components/user/themes/UserColumn2.js
  components/user/themes/UserInline.js
  components/user/themes/UserTabs.js
  models/Profile.js
  models/Profile/Repo.js
  pages/account/manage/repos.js
  pages/api/account/manage/milestone/[[...data]].js
  pages/api/account/manage/repo/[[...data]].js
  pages/api/account/manage/repos.js
  pages/api/profiles/[username]/index.js
  services/github/getRepo.js
  tests/manage/repos.spec.js
Labels: large, waiting-for-reviewers, tests

#8404 refactor - Refactored the classNames function
  components/Tabs.js
  components/event/EventTabs.js
  components/form/Toggle.js
  components/navbar/SideNav.js
  components/navbar/SubNav.js
  pages/index.js
  pages/roadmap.js
  utils/functions/classNames.js
Labels: issue linked

#8445 data: saram7619
  data/saram7619.json
Labels: ✍ chore: profile

#8456 data : henilGondalia
  data/henilGondalia.json
Labels: ✍ chore: profile

#8459 data: Axorax
  data/Axorax.json
Labels: ✍ chore: profile

#8465 data: AyushRay06
  data/AyushRay06.json
Labels: ✍ chore: profile

#8468 updated my social links
  data/Aladdin4u.json
  data/aladdin.json
Labels: ✍ chore: profile

#8472 data:NikhilHuirem
  data/nikhilhuirem.json
Labels: ✍ chore: profile

#8483 Update SandipPalit.json
  data/SandipPalit.json
Labels: ✍ chore: profile

#8480 data: ElianCodes profile
  data/ElianCodes.json
Labels: ✍ chore: profile

#8488 Update chetannada.json
  data/chetannada.json
Labels: ✍ chore: profile

#8484 Sandip palit patch 2 1
  data/SandipPalit/events/2022-08-27-Cloud-Community-Days-2022-Kolkata.json
  data/SandipPalit/events/2023-08-05-Nomoskar-Kolkata.json
Labels: ✍ chore: profile

#8491 Fix: Issue with label in dark mode #8413
  components/user/UserEvents.js
Labels: issue linked

#8498 Update dushmanta05.json
  data/dushmanta05.json
Labels: ✍ chore: profile

#8504 data: debadityasingh8972
  data/debadityasingh8972.json
Labels: ✍ chore: profile

#8510 data: Sagar0-0
  data/Sagar0-0.json
Labels: ✍ chore: profile

#8511 Update harshsingh32.json
  data/harshsingh32.json
Labels: ✍ chore: profile

#8519 Minor changes in the bio and tags
  data/okrupesh.json
Labels: ✍ chore: profile

#8518 Fixes Consistency Issue: getUsers renamed to getProfiles
  pages/api/profiles/index.js
  pages/api/search/index.js
  pages/map.js
  pages/search.js
Labels: issue linked

#8056 fix: Event Card price icon bug
  pages/account/manage/event/[[...data]].js
  pages/api/events.js
Labels: small, waiting-for-reviewers, issue linked

#8525 Update sandramsc.json
  data/sandramsc.json
Labels: ✍ chore: profile

#8527 data: mhgolestan
  data/mhgolestan.json
Labels: ✍ chore: profile

#8220 [BUG] Duplicate select form element #8147
  components/Tabs.js
  components/event/EventTabs.js
  components/form/DropDown.js
  components/form/Select.js
  components/navbar/SubNav.js
  components/user/UserEvents.js
  pages/account/manage/milestone/[[...data]].js
  stories/components/form/DropDown.stories.js
  tests/events.spec.js
Labels: large, waiting-for-reviewers, tests, storybook, issue linked

#8530 Create SurajKumar.json
  data/Suraj-kumar00.json
Labels: ✍ chore: profile

#8538 data: Sahilll15
  data/Sahilll15.json
Labels: ✍ chore: profile

#8522 data: Akash-vadakkeveetil
  data/Akash-vadakkeveetil.json
Labels: ✍ chore: profile

#8540 data: Infinite8loop
  data/infinite8loop.json
Labels: ✍ chore: profile

#8541 feat: update mongo query to show active repos
  pages/api/repos.js
Labels: issue linked

#8506 Fixed: Edit-Milestone-icon comes over the Milestone-icon
  components/user/UserMilestone.js
Labels: issue linked

#8286 fixed need some margin on profile section #8210
  components/Alert.js
Labels: 💻 aspect: code, issue linked

#8308 enhancement - Fixed the active page highlighted feature
  components/layouts/DocsLayout.js
  components/navbar/SideNav.js
Labels: 💻 aspect: code, issue linked

#8555 Select & Storybook cleanup
  components/Tabs.js
  components/event/EventTabs.js
  components/form/Select.js
  components/navbar/SubNav.js
  components/user/UserEvents.js
  package-lock.json
  package.json
  stories/components/form/DropDown.stories.js
  stories/components/form/Select.stories.js
Labels: storybook

#8565 Update BDFL669.json
  data/BDFL669.json
Labels: ✍ chore: profile

#8566 Fixed #8526 : QR code link width
  components/ClipboardCopy.js
  components/user/UserProfile.js
Labels: issue linked

#8568 [Fixed] : Button visibility on light mode
  components/Button.js
Labels: issue linked

#8535 Fixed the z-index of edit icon in link
  components/account/manage/Edit.js
Labels: issue linked

#8509 Adds Highlight on Focus in Copy Button
  components/ClipboardCopy.js
Labels: issue linked

#8476 Added consistent style on className
  components/Badge.js
  components/Pagination.js
  components/SkipLink.js
  components/Tabs.js
  components/event/EventTabs.js
  components/form/Input.js
  components/form/Toggle.js
  components/navbar/Navbar.js
  components/navbar/SideNav.js
  components/navbar/SubNav.js
  components/tag/Tag.js
  components/user/UserLink.js
  components/user/UserMilestone.js
  pages/account/manage/testimonials.js
  pages/changelog.js
  pages/index.js
  pages/roadmap.js
  services/utils/classNames.js
Labels: issue linked

#8574 data: JulieB16
  data/JulieB16.json
Labels: ✍ chore: profile

#8575 data: isdavehill
  data/Isdavehill.json
Labels: ✍ chore: profile

#8581 automate issue linked label
  .github/workflows/labels.yml
Labels: CI/CD

#8505 Update links.js for hiding reorder button when there are no links.
  pages/account/manage/links.js
Labels: issue linked

#8463 [fix]: search input background-color in icons page for dark theme
  pages/icons.js
Labels: issue linked

#8594 feat: markdown multi lines
  components/Markdown.js
  components/event/EventCard.js
  components/form/Textarea.js
  components/map/UserMarker.js
  components/user/UserHorizontal.js
  components/user/UserMilestone.js
  components/user/UserMini.js
  components/user/UserProfile.js
  components/user/UserTestimonials.js
  pages/account/manage/event/[[...data]].js
  pages/account/manage/milestone/[[...data]].js
  pages/account/manage/profile.js
Labels: issue linked

#8496 fix: close button of download qr code modal fixed (#8455)
  components/Modal.js
Labels: issue linked

#8314 Fixed issue #8235 BUG: Testimonials shows zero if no testimonials exist for user
  pages/account/manage/testimonials.js
Labels: 💻 aspect: code, issue linked

#8514 Fix: Wrong list of users on search page
  pages/search.js
Labels: issue linked

#8601 data: ralphsulit
  data/ralphsulit.json
Labels: ✍ chore: profile

#8610 data: dfdevaney
  data/dfdevaney.json
Labels: ✍ chore: profile

#8615 feat: discover page for recently updated profiles
  components/navbar/Navbar.js
  pages/admin/profiles.js
  pages/api/discover/profiles.js
  pages/discover.js
  tests/discover.spec.js
Labels: tests, issue linked

#8626 data: Siwi0w0
  data/Siwi0w0.json
Labels: ✍ chore: profile

#8629 data: yashwanth-3000
  data/yashwanth-3000
Labels: ✍ chore: profile

#8630 Sandip palit patch 3
  data/SandipPalit/events/2022-08-27-Cloud-Community-Days-2022-Kolkata.json
  data/SandipPalit/events/2022-11-13-DevFest-2022-Kolkata.json
  data/SandipPalit/events/2023-02-11-TFUG-Kolkata-Reboot.json
  data/SandipPalit/events/2023-03-04-Being-Women-IWD-Celebration.json
  data/SandipPalit/events/2023-03-11-Dare-To-Be-an-Entrepreneur-IWD-2023.json
  data/SandipPalit/events/2023-05-07-Cloud-Community-Day-Kolkata-2023-Kolkata.json
  data/SandipPalit/events/2023-08-19-Google-IO-Extended-2023.json
  data/SandipPalit/events/2023-08-27-Keras-Community-Day-2023.json
Labels: ✍ chore: profile

#8623 Centered mascot on 404 page
  pages/404.js
Labels: issue linked

#8634 data: Sebastian james55 patch 1
  data/SebastianJames55.json
Labels: ✍ chore: profile

#8637 data:Chinwenma.json
  data/Chinwenma.json
Labels: ✍ chore: profile

#8552 Fixed: Navbar Overflow issue on smaller mobile devices.
  components/form/Select.js
  components/navbar/Navbar.js
Labels: issue linked

#8608 Documentation:Expanded the docker compose instructions and details
  README.md
Labels: issue linked

#8591 feature: success message and redirects to list page on successful delete
  pages/account/manage/event/[[...data]].js
  pages/account/manage/events.js
  pages/account/manage/link/[[...data]].js
  pages/account/manage/links.js
  pages/account/manage/milestone/[[...data]].js
  pages/account/manage/milestones.js
Labels: issue linked

#8636 fix: Failing to add repo with trailing slash
  pages/api/account/manage/repo/[[...data]].js
Labels: issue linked

#8649 data: grand-rick001 - Update twitter link
  data/grand-rick001.json
Labels: ✍ chore: profile

#8419 feat: Added tag highlighting to tags in profile card on search
  components/tag/TagSimple.js
  components/user/UserHorizontal.js
  pages/search.js
  services/utils/classNames.js
  services/utils/search/tags.js
Labels: issue linked

#8659 Update chetannada.json
  data/chetannada.json
Labels: ✍ chore: profile

#8662 Update RishikeshYadav95.json
  data/RishikeshYadav95.json
Labels: ✍ chore: profile

#8663 data: jfmartinz.json
  data/jfmartinz.json
Labels: ✍ chore: profile

#8667 Data: ElianCodes update bio
  data/ElianCodes.json
Labels: ✍ chore: profile

#8669 Fix dark mode display issue for bio label
  components/form/Textarea.js
Labels: issue linked

#8673 data: Added Quine
  data/Viveksati5143.json
Labels: ✍ chore: profile

#8677 feat: count profile visitors ip
  models/Profile.js
  models/ProfileStats.js
  package-lock.json
  package.json
  pages/[username].js
  pages/api/profiles/[username]/index.js
Labels: dependencies

#8689 data: sandramsc update
  data/sandramsc.json
Labels: ✍ chore: profile

#8693 data: BSatishSutar
  data/BSatishSutar.json
Labels: ✍ chore: profile

#8508 added animations in Userlink
  components/user/UserLink.js
  config/app.json
  models/Link.js
  pages/account/manage/link/[[...data]].js
  pages/api/account/manage/link/[[...data]].js
  services/utils/objectToLabelValueArray.js
  styles/animation.module.css
Labels: issue linked

#8706 Updating ./tests/search.spec.js automated test
  tests/search.spec.js
Labels: tests

#8698 Create search filter for icons in forms
  components/IconSearch.js
  pages/account/manage/link/[[...data]].js
  pages/account/manage/milestone/[[...data]].js
Labels: issue linked

#8685 fix: stop keydown event propagation on input
  components/form/Input.js
Labels: issue linked

#8720 data: sumitbhanushali
  data/sumitbhanushali.json
Labels: ✍ chore: profile

#8726 data: CRAZy-Monk3Y
  data/CRAZy-Monk3Y.json
Labels: ✍ chore: profile

#8728 data: sree-hari-s.json
  data/sree-hari-s.json
Labels: ✍ chore: profile

#8732 data: CRAZy-Monk3Y.json
  data/CRAZy-Monk3Y.json
Labels: ✍ chore: profile

#8683 add label for models updates
  .github/config/labeler.yml
Labels: CI/CD

#8708 Fixed: [OTHER] <Test error for "event listed" test on the /events end point> #8670
  tests/events.spec.js
Labels: tests, issue linked

#8676 Spaces in Missing Section
  pages/account/statistics.js
Labels: issue linked

#8718 Expose compose mongodb container port && update readme.md
  README.md
  compose.yml
  pages/docs/environments/local-development.mdx
Labels: issue linked, 📖 docs

#8607 Fixed : [BUG] <Profile update notification remains on screen>
  components/Notification.js
Labels: issue linked

#8524 Adjusted padding between section and pages
  pages/docs/index.js
Labels: issue linked

#8694 Fix: spacing between add repo form and repo list.
  pages/account/manage/repos.js
Labels: issue linked

#8577 feature: Community resources to array
  config/community-resources.json
  pages/docs/community-resources.mdx
Labels: issue linked, 📖 docs

#8729 data: Harshitahusts
  data/Harshitahusts.json
Labels: ✍ chore: profile

#8727 data: ismailwafid
  data/ismailwafid.json
Labels: ✍ chore: profile

#8177 BUG Fix: Docs side nav being hidden in the mobile view
  components/layouts/DocsLayout.js
  components/navbar/SideNav.js
  pages/docs/index.js
Labels: small, waiting-for-reviewers, issue linked, 📖 docs

#8739 Data: NiikNiik
  data/NiikNiik.json
Labels: ✍ chore: profile

#8747 Update kiyoshi-87.json
  data/kiyoshi-87.json
Labels: ✍ chore: profile

#8749 Removed data/sree-hari-s
  data/sree-hari-s.json
Labels: ✍ chore: profile

#8753 Create myrausman.json
  data/Myrausman.json
Labels: ✍ chore: profile

#8756 chore: delete json for Dun-sin
  data/Dun-sin.json
Labels: ✍ chore: profile

#8755 data: SohaMubashir
  data/SohaMubashir.json
Labels: ✍ chore: profile

#8758 data: MaorBemdoo
  data/MaorBemdoo.json
Labels: ✍ chore: profile

#8759 data: grand-rick001 - update twitter link
  data/grand-rick001.json
Labels: ✍ chore: profile

#8006 Adding Speaker Status and Speaker Title in Events Form
  components/event/EventCard.js
  models/Profile/Event.js
  pages/account/manage/event/[[...data]].js
  pages/api/system/reload.js
Labels: large, waiting-for-reviewers, issue linked

#8761 B satish sutar patch 5
  data/BSatishSutar.json
Labels: ✍ chore: profile

#8777 data: Praveen Raj
  data/praveen0raj.json
Labels: ✍ chore: profile

#8771 B satish sutar patch 6
  data/BSatishSutar.json
Labels: ✍ chore: profile

#8787 fix: terms date
  pages/docs/terms.mdx
Labels: 📖 docs

#8789 fix: update package-lock file
  package-lock.json
Labels: 💻 aspect: code, dependencies

#8797 fix: subdomain to domain
  CONTRIBUTING.md
  components/PageHead.js
  constants/index.js
  pages/[username].js
  pages/account/no-profile.js
  pages/docs/map.mdx
  pages/docs/quickstart-json.mdx
  stories/components/navbar/Navlink.stories.js
  stories/components/user/UserPage.stories.js
  stories/components/user/UserTestimonials.stories.js
  stories/components/user/profile.json
Labels: storybook, 📖 docs

#8801 fix: BioDrop app version
  config/app.json
  package-lock.json
  package.json
Labels: dependencies

#8805 data: MaorBemdoo
  data/MaorBemdoo.json
Labels: ✍ chore: profile

#8809 Removed data/himanshubalani/json
  data/himanshubalani.json
Labels: ✍ chore: profile

#8813 docs: gitpod environment variable
  pages/docs/environments/gitpod.mdx
Labels: 📖 docs

#8816 del: gambhir_sharma.json
  data/gambhirsharma.json
Labels: ✍ chore: profile

#8767 Create mdwasim74.json
  data/mdwasim74.json
Labels: ✍ chore: profile

#8808 feat: profile rank
  components/user/UserMini.js
  pages/account/statistics.js
  pages/api/account/statistics.js
Labels: issue linked

#8832 data: Arjun-Aravind
  data/Arjun-Aravind.json
Labels: ✍ chore: profile

#8828 Delete md-abid-hussain.json
  data/md-abid-hussain.json
Labels: ✍ chore: profile

#8842 feat: improved landing page
  components/CallToAction.js
  components/ThemedImage.js
  components/statistics/BasicCards.js
  pages/index.js
Labels: issue linked

#8838 data: kush6291.json
  data/kush6291.json
Labels: ✍ chore: profile

#8850 data: avinashharesh
  data/avinashharesh.json
Labels: ✍ chore: profile

#8852 data: jfmartinz
  data/jfmartinz.json
Labels: ✍ chore: profile

#8856 fix: (issue #7851) increased max length of link display name
  models/Link.js
  pages/account/manage/link/[[...data]].js
Labels: issue linked, models

#8836 improve the overall visual hierarchy of the features section #8810
  components/Testimonials.js
  pages/index.js
Labels: issue linked

#8722 Create m_latif.json
  data/m_latif/m_latif.json
Labels: ✍ chore: profile

#8701 data: RutikaW1155
  data/RutikaW1155
Labels: ✍ chore: profile

#8752 data/saadali05.json
  saadali.json
Labels: ✍ chore: profile

#8861 feat: Show profile stats publicly.
  components/form/Toggle.js
  components/user/UserProfile.js
  models/Profile.js
  pages/[username].js
  pages/account/manage/profile.js
  pages/api/account/manage/profile.js
Labels: issue linked, models

#8868 fix: curl command to follow redirects
  .github/workflows/vercel-pr-preview.yml
  .github/workflows/vercel-preview.yml
  .github/workflows/vercel.yml
Labels: CI/CD

#8870 [fix] overflow issue in repos section
  components/Link.js
Labels: issue linked

#8869 remove: File data/prnvtripathi.json
  data/prnvtripathi.json
Labels: ✍ chore: profile

#8877 data: Emmanuel-Adom
  data/Emmanuel-Adom.json
Labels: ✍ chore: profile

#8878 Update harisdev-netizen.json
  data/harisdev-netizen.json
Labels: ✍ chore: profile

#8881 data: Pravesh-Sudha.json deleted
  data/Pravesh-Sudha.json
Labels: ✍ chore: profile

#8387 Fix/pinned link style
  components/user/UserLink.js
Labels: issue linked
