Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-10, with the labels that each got.

#9142 feat: Increase execution time for loading json files
  vercel.json
Labels: issue linked

#8711 [TEST] Profile link navigates to url #8707
  tests/profile.spec.js
Labels: tests, issue linked

#9068 [FEATURE] Display most popular icons in Search for Icons page #8421
  pages/icons.js
  tests/icon.spec.js
Labels: tests, issue linked

#9060 Add min date for milestone
  models/Profile/Milestone.js
  pages/account/manage/milestone/[[...data]].js
Labels: issue linked, models

#9234 fix: default issue template dropdown to no
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: CI/CD

#9237 fix: hacktoberfest ignore label for profiles
  .github/config/labeler.yml
Labels: CI/CD

#9232 Removed my JSON file
  data/himanshu1221.json
Labels: invalid, ✍ chore: profile

#9244 data: Added dev.to link & minor changes
  data/Viveksati5143.json
Labels: invalid, ✍ chore: profile

#9250 Create Aditya-singh-9.json
  data/Aditya-singh-9.json
Labels: invalid, ✍ chore: profile

#9252 Create Akib-Vijapura.json
  data/Akib-Vijapura.json
Labels: invalid, ✍ chore: profile

#9253 feat: remove app alert for new icons
  config/app.json
Labels: issue linked

#9158 fix: Add more space between buttons and event card (#9119)
  pages/account/manage/event/[[...data]].js
Labels: issue linked

#9257 data: vaibhav-xt (profile update)
  data/vaibhav-xt.json
Labels: invalid, ✍ chore: profile

#8605 feat: log profile updates that occur by the manage forms
  models/Changelog.js
  models/Link.js
  models/index.js
  models/middlewares/logChange.js
  pages/api/account/manage/event/[[...data]].js
  pages/api/account/manage/link/[[...data]].js
  pages/api/account/manage/milestone/[[...data]].js
  pages/api/account/manage/profile.js
  pages/api/account/manage/repo/[[...data]].js
  pages/api/account/manage/settings.js
Labels: issue linked, models

#9270 Update SAD0XER.json
  data/SAD0XER.json
Labels: invalid, ✍ chore: profile

#9280 data: Ssaava
  data/Ssaava.json
Labels: invalid, ✍ chore: profile

#9284 Amit0804 tech patch 3
  data/amit0804-tech.json
Labels: invalid, ✍ chore: profile

#9283 data:Judge-Paul
  data/Judge-Paul.json
Labels: invalid, ✍ chore: profile

#9285 Update shubhsharma19.json
  data/shubhsharma19.json
Labels: invalid, ✍ chore: profile

#9286 Create njolipatrick.json
  data/njolipatrick.json
Labels: invalid, ✍ chore: profile

#9290 data Bishwajit-2810.json
  data/Bishwajit-2810.json
Labels: invalid, ✍ chore: profile

#9304 Create Mahendra5495.json
  data/Mahendra5495.json
Labels: invalid, ✍ chore: profile

#9305 data: theCephas
  data/theCephas.json
Labels: invalid, ✍ chore: profile

#9307 data: realdezzy
  data/realdezzy.json
Labels: invalid, ✍ chore: profile

#9287 feat: removing help badge on events page
  pages/events.js
Labels: Hacktoberfest, issue linked

#9322 Fix mobile give us a star banner styling
  components/layouts/Alert.js
Labels: issue linked

#9321 Vaibhav xt patch 1
  data/vaibhav-xt.json
Labels: invalid, ✍ chore: profile

#9330 data: marameref
  data/marameref.json
Labels: invalid, ✍ chore: profile

#9333 data: shubhalgupta
  data/shubhalgupta.json
Labels: invalid, ✍ chore: profile

#9335 data: itsayopapi
  data/itsayopapi.json
Labels: invalid, ✍ chore: profile

#9336 data: DonGuillotine
  data/DonGuillotine.json
Labels: invalid, ✍ chore: profile

#9172 added motion safe to animate
  styles/globals.css
Labels: issue linked

#9354 Himanshuch8055
  data/Himanshuch8055.json
Labels: invalid, ✍ chore: profile

#9356 data: Panquesito7
  data/Panquesito7.json
  data/Panquesito7/events/bugtrons.json
Labels: invalid, ✍ chore: profile

#9343 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#8973 feat: milestone-date-formatting
  components/user/UserMilestone.js
  components/user/UserMilestones.js
  models/Profile/Milestone.js
  pages/account/manage/milestone/[[...data]].js
  pages/api/account/manage/milestone/[[...data]].js
  pages/api/account/manage/milestones.js
  services/utils/dateFormat.js
Labels: issue linked, models

#9365 data: rossana87
  data/rossana87.json
Labels: invalid, ✍ chore: profile

#9366 data: Luwa-Tech
  data/Luwa-Tech.json
Labels: invalid, ✍ chore: profile

#9370 data: YanaGorina-alt
  data/YanaGorina-alt.json
Labels: invalid, ✍ chore: profile

#9372 Update jugaaadd.json
  data/jugaaadd.json
Labels: invalid, ✍ chore: profile

#9373 data: Update D4-Community.json
  data/D4-Community.json
Labels: invalid, ✍ chore: profile

#9339 Update DocsLayout.js
  components/layouts/DocsLayout.js
Labels: issue linked

#9342 Fix: Docs page missing nav
  pages/docs/open-source-roadmap/index.js
Labels: issue linked, 📖 docs

#9303 feat: help now redirect to docs/faqs
  pages/index.js
Labels: issue linked

#9262 fix: disable the reorder button unless there is more than one link added
  pages/account/manage/links.js
Labels: issue linked

#9391 fix: changelog and version bump
  .github/workflows/release.yml
Labels: CI/CD

#9247 fix: made community resources page responsive
  pages/docs/community-resources.mdx
Labels: issue linked, 📖 docs

#9369 Maxton4life patch 1
  data/maxton4life.json
Labels: invalid, ✍ chore: profile

#8580 Profile Views Graph: Displaying All Dates Including Zero Views
  components/statistics/StatsChart.js
  pages/account/statistics.js
Labels: issue linked

#9394 Update jugaaadd.json
  data/jugaaadd.json
Labels: invalid, ✍ chore: profile

#9400 refactor: deleted data/Blaize15.json file
  data/Blaize15.json
Labels: invalid, ✍ chore: profile

#9403 Add `data/stenwire.json`
  data/stenwire.json
Labels: invalid, ✍ chore: profile

#9404 Update SebastianJames55.json
  data/SebastianJames55.json
Labels: invalid, ✍ chore: profile

#9415 Fixed typos in Faq's section.
  pages/docs/faqs.mdx
Labels: issue linked, 📖 docs

#9416 add WassCodeur.json i
  data/WassCodeur.json
Labels: invalid, ✍ chore: profile

#9410 feat: location stats details
  components/statistics/PieGraph.js
  pages/account/statistics/index.js
  pages/account/statistics/locations.js
  pages/account/statistics/referers.js
  tests/account/stats/location.spec.js
  tests/account/stats/referer.spec.js
  tests/setup/global-setup.js
Labels: tests

#9426 Changed join to joining
  pages/docs/open-source-roadmap/where.js
Labels: issue linked, 📖 docs

#9428 data: mehra-sourav
  data/mehra-sourav.json
Labels: invalid, ✍ chore: profile

#9431 Delete dfdevaney.json
  data/dfdevaney.json
Labels: invalid, ✍ chore: profile

#9396 Feat: Pronoun field for biodrop users
  .gitignore
  config/app.json
  models/Profile.js
  pages/account/manage/profile.js
  pages/api/account/manage/profile.js
Labels: issue linked, models

#9435 data:niwei822
  data/niwei822.json
Labels: invalid, ✍ chore: profile

#9444 data:Akshatchaube01
  data/Akshatchaube01.json
Labels: invalid, ✍ chore: profile

#9412 Updated the a link to Link tag
  components/navbar/SideNav.js
Labels: issue linked

#9457 fix: tabs on mobile no label
  components/Tabs.js
Labels: issue linked

#9456 data: Nuellity
  data/Nuellity.json
Labels: invalid, ✍ chore: profile

#9459 data: alevel7
  data/alevel7.json
Labels: invalid, ✍ chore: profile, issue linked

#9464 fix: issue templates more specific
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  pages/docs/faqs.mdx
Labels: CI/CD, 📖 docs

#9467 fix: issue template bug and feature
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: CI/CD

#9469 fix: bug issue template for environments
  .github/ISSUE_TEMPLATE/bug.yml
Labels: CI/CD

#9472 fix: bug issue template environment to input
  .github/ISSUE_TEMPLATE/bug.yml
Labels: CI/CD

#9475 Update feature_request template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: CI/CD

#9474 Updated links-forms.mdx
  pages/docs/how-to-guides/links-forms.mdx
Labels: hacktoberfest-accepted, issue linked, 📖 docs

#9476 Fixed : <A typographical error> #9433
  pages/docs/open-source-roadmap/checks.js
Labels: hacktoberfest-accepted, issue linked, 📖 docs

#9477 data: waellerbe.json
  data/waellerbe.json
Labels: invalid, ✍ chore: profile

#9478 Create lakshay451.json
  data/lakshay451.json
Labels: invalid, ✍ chore: profile

#9481 feat: Increase profile count in search page
  pages/search.js
Labels: issue linked

#9485 data:kahmed-stack
  data/kahmed-stack.json
Labels: invalid, ✍ chore: profile

#9483 data: deepak039543
  data/deepak039543.json
Labels: invalid, ✍ chore: profile

#9487 data: AmbujaAK
  data/AmbujaAK.json
Labels: invalid, ✍ chore: profile

#9380 fix:multiple re-render in profile page
  components/Tabs.js
  components/navbar/SubNav.js
  components/user/themes/UserTabs.js
Labels: issue linked

#9489 feat: admin list premium users
  pages/admin/profiles.js
  pages/api/admin/profiles.js
  tests/profile.spec.js
Labels: tests

#9493 data: vanshiz
  data/vanshiz.json
Labels: invalid, ✍ chore: profile

#9276 feat: add tags to events
  components/event/EventCard.js
  models/Profile/Event.js
  pages/account/manage/event/[[...data]].js
  pages/api/account/manage/event/[[...data]].js
  pages/api/events.js
Labels: issue linked, models

#9498 feat: tags to events
  components/event/EventCard.js
  models/Profile/Event.js
  pages/account/manage/event/[[...data]].js
  pages/api/account/manage/event/[[...data]].js
  pages/api/events.js
Labels: models

#9510 deleted data/joelchully.json
  data/joelchully.json
Labels: invalid, ✍ chore: profile

#9497 Fixes #9294 Low contrast color change on the onboarding page.
  pages/account/onboarding/index.js
Labels: issue linked

#9249 feat: admin user check middleware
  middleware.js
  pages/admin/events.js
  pages/admin/profiles.js
  pages/admin/statistics.js
  pages/api/admin/events.js
  pages/api/admin/events/[...id].js
  pages/api/admin/profiles.js
  pages/api/admin/stats.js
Labels: issue linked

#9522 Create Blossomeze.json
  data/Blossomeze.json
Labels: invalid, ✍ chore: profile

#9353 feat: elaborating on step 8 in open source map
  pages/docs/open-source-roadmap/index.js
  pages/docs/open-source-roadmap/what-next.js
Labels: issue linked, 📖 docs

#9462 [TEST] home page stats #9384
  tests/home.spec.js
Labels: tests, issue linked

#9187 feat: sentry integration
  .github/workflows/vercel-preview.yml
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.js
  sentry.edge.config.js
  sentry.server.config.js
Labels: CI/CD, dependencies

#9447 data: harohar13
  data/harohar13.json
Labels: invalid, ✍ chore: profile

#9541 fixed typo #9525
  pages/docs/contributing/commits.mdx
Labels: issue linked, 📖 docs

#9538 data:Faopaw
  data/Faopaw.json
Labels: invalid, ✍ chore: profile

#9496 feat: remove discover page and implement the logic in search page
  components/navbar/Navbar.js
  pages/discover.js
  pages/pricing.js
  pages/search.js
  tests/discover.spec.js
Labels: tests, issue linked

#9545 Discover to Search (fix pr 9496)
  components/navbar/Navbar.js
  pages/discover.js
  pages/pricing.js
  pages/search.js
  tests/discover.spec.js
  tests/search.spec.js
Labels: tests

#9544 data:YashSalunke12
  data/YashSalunke12.json
Labels: invalid, ✍ chore: profile

#9529 fix: Typo mistake in Testimonials section on the onboarding screen (#9519)
  pages/account/onboarding/index.js
Labels: issue linked

#9413 [Feature]: will show `Free` text if event is free
  components/event/EventCard.js
Labels: issue linked

#9429 Update Footer.js [ Improved Footer Section in Mobile Design]
  components/Footer.js
Labels: issue linked

#9552 data:AnikethDeb2004
  data/AnikethDeb2004.json
Labels: invalid, ✍ chore: profile

#9554 data: AloisSeckar
  data/AloisSeckar.json
Labels: invalid, ✍ chore: profile

#9565 Data: Bratajit-03
  data/Bratajit-03.json
Labels: invalid, ✍ chore: profile

#9576 Update AnikethDeb2004.json
  data/AnikethDeb2004.json
Labels: invalid, ✍ chore: profile

#9568 Fixes Typographical error docs/environments/gitpod page
  pages/docs/environments/gitpod.mdx
Labels: issue linked, 📖 docs

#9577 improvement : footer text update
  components/Footer.js
Labels: issue linked

#9569 docs: Update docker rmi command
  pages/docs/environments/local-development.mdx
Labels: issue linked, 📖 docs

#9430 fixes#9334: adds more information in Step5
  pages/docs/open-source-roadmap/what-to-contribute.js
Labels: issue linked, 📖 docs

#9584 feat: populate basic profile on login
  pages/api/auth/[...nextauth].js
  pages/docs/quickstart-forms.mdx
Labels: 📖 docs

#9503 Added hover color for links on open source roadmap
  pages/docs/open-source-roadmap/index.js
Labels: issue linked, 📖 docs

#9302 Add GitHub Discussions Section to FAQs
  pages/docs/faqs.mdx
Labels: issue linked, 📖 docs

#9560 docs: add correct date format to clipboards of Milestones-json
  pages/docs/how-to-guides/milestones-json.mdx
Labels: issue linked, 📖 docs

#9527 Feat middleware to protect auth and admin pages
  .github/workflows/vercel-preview.yml
  middleware.js
  pages/account/manage/event/[[...data]].js
  pages/account/manage/events.js
  pages/account/manage/link/[[...data]].js
  pages/account/manage/links.js
  pages/account/manage/milestone/[[...data]].js
  pages/account/manage/milestones.js
  pages/account/manage/premium.js
  pages/account/manage/profile.js
  pages/account/manage/repos.js
  pages/account/manage/testimonials.js
  pages/account/no-profile.js
  pages/account/onboarding/index.js
  pages/account/statistics/index.js
  pages/account/statistics/link/[id].js
  pages/account/statistics/locations.js
  pages/account/statistics/referers.js
  pages/admin/changelog.js
  pages/admin/events.js
  pages/admin/profiles.js
  pages/admin/statistics.js
  pages/api/account/account.js
  pages/api/account/manage/event/[[...data]].js
  pages/api/account/manage/events.js
  pages/api/account/manage/link/[[...data]].js
  pages/api/account/manage/links.js
  pages/api/account/manage/milestone/[[...data]].js
  pages/api/account/manage/milestones.js
  pages/api/account/manage/profile.js
  pages/api/account/manage/repo/[[...data]].js
  pages/api/account/manage/repos.js
  pages/api/account/manage/settings.js
  pages/api/account/manage/testimonials.js
  pages/api/account/statistics/index.js
  pages/api/account/statistics/link/[id].js
  pages/api/admin/changelog.js
  pages/api/admin/events.js
  pages/api/admin/events/[...id].js
  pages/api/admin/profiles.js
  pages/api/admin/stats.js
Labels: CI/CD

#9591 Remove JSON Profile
  data/ThomasCode92.json
Labels: invalid, ✍ chore: profile

#9558 Fixes Issue: #8533 [BUG] The order of pinned icons doesn't change
  pages/api/profiles/[username]/index.js
Labels: issue linked

#9603 fix: update assign comment check
  .github/workflows/check-assignee.yml
Labels: CI/CD

#9605 ci: action comment text
  .github/workflows/check-assignee.yml
  .github/workflows/codeql.yml
Labels: CI/CD

#9606 Akshat171 patch 2
  data/Akshat171.json
Labels: invalid, ✍ chore: profile

#9607 data:nilandev
  data/nilandev.json
Labels: invalid, ✍ chore: profile

#9611 ci: assigned issue check filter repo
  .github/workflows/check-assignee.yml
Labels: CI/CD

#9612 data: aqib-m31
  data/aqib-m31.json
Labels: invalid, ✍ chore: profile

#9613 data: update nilandev
  data/nilandev.json
Labels: invalid, ✍ chore: profile

#9599 Updated my account details PoulavBhowmick.json
  data/PoulavBhowmick03.json
Labels: invalid, ✍ chore: profile

#9615 add: singodiyashubham87
  data/singodiyashubham87.json
Labels: invalid, ✍ chore: profile

#9556 [OTHER] <Click link click increase tests> /tests/profile.spec.js
  tests/profile.spec.js
Labels: tests

#9622 Samuelaidoo45 patch 1
  data/samuelaidoo45.json
Labels: invalid, ✍ chore: profile

#9620 fix: url wrap in stats list
  pages/account/statistics/index.js
Labels: issue linked

#9551 removed unnecessary label on Tab component
  components/Tabs.js
Labels: issue linked

#9520 data: waellerbe
  data/waellerbe.json
Labels: invalid, ✍ chore: profile

#9621 Small typos
  README.md
  pages/docs/how-to-guides/bio-json.mdx
  pages/docs/how-to-guides/events-forms.mdx
  pages/docs/open-source-roadmap/glossary.js
  pages/docs/open-source-roadmap/how-to-contribute.js
  pages/docs/open-source-roadmap/what-to-contribute.js
  pages/docs/open-source-roadmap/where.js
Labels: 📖 docs

#9442 FIx: Renamed the StatsChart to BarGraph and updated its usage
  components/statistics/StatsChart.js
  pages/account/statistics/index.js
  pages/account/statistics/link/[id].js
Labels: issue linked

#9640 Create New Profile JSON File TO Data Folder
  data/RJPalmer.json
Labels: invalid, ✍ chore: profile

#9641 fix: view Profile Button not align properly.
  components/user/UserMini.js
Labels: issue linked

#9643 data: VidipGhosh
  data/Vidip-Ghosh.json
Labels: invalid, ✍ chore: profile

#9629 style: fix light theme border issue
  pages/index.js
Labels: issue linked

#9638 Feat/check json profile api
  .github/workflows/check-profile.yml
Labels: issue linked, CI/CD

#9642 feat: check authors assigned issues workflow
  .github/workflows/check-author-issues.yml
Labels: issue linked, CI/CD

#9648 ci: fix gh action issue
  .github/workflows/check-author-issues.yml
Labels: CI/CD

#9661 ❌: Delete mrdanishsaleem.json file from data folder
  data/mrdanishsaleem.json
Labels: invalid, ✍ chore: profile

#9667 fix: github action skip on profile not found
  .github/workflows/check-profile.yml
Labels: CI/CD

#9669 fix: gh action profile status code type
  .github/workflows/check-profile.yml
Labels: CI/CD

#9671 fix: gh action profile check method
  .github/workflows/check-profile.yml
Labels: CI/CD

#9673 fix: gh action profile check flag
  .github/workflows/check-profile.yml
Labels: CI/CD

#9675 fix: gh action profile check ignore 404
  .github/workflows/check-profile.yml
Labels: CI/CD

#9677 fix: gh action profile check method
  .github/workflows/check-profile.yml
Labels: CI/CD

#9665 data archeana
  data/archeana.json
Labels: invalid, ✍ chore: profile

#9679 data:SAD0XER
  data/SAD0XER.json
Labels: invalid, ✍ chore: profile

#9683 Update and rename J-CODE07.json to Jagan-07.json
  data/Jagan-07.json
Labels: invalid, ✍ chore: profile

#9690 data: guranshdeol
  data/guranshdeol.json
Labels: invalid, ✍ chore: profile

#9663 fix: double border on input field in icons page
  pages/icons.js
Labels: issue linked
