Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-03, with the labels that each got.

#5148 Remove lint-staged & prettier from husky config
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 💻 aspect: code, large

#4997 Call username lookup code directly
  components/user/UserPage.js
  config/logger.js
  pages/[username].js
  pages/api/users/[username]/index.js
  stories/components/user/UserPage.stories.js
Labels: large, storybook

#5151 data: 0rigin-c0de
  data/0rigin-c0de.json
Labels: ✍ chore: profile addition, medium, LGTM

#5150 data: Alkaison
  data/Alkaison.json
Labels: ✍ chore: profile addition, large, LGTM

#5165 docs: local dev link to env vars
  pages/docs/environments/gitpod.mdx
  pages/docs/environments/local-development-docker-compose.mdx
  pages/docs/environments/local-development.mdx
Labels: medium

#5155 add Chaos Carnival
  data/thebarshablog/events/2023-03-15-chaos-carnival.json
Labels: ✍ chore: profile addition, medium

#5157 updated broken links
  data/yrncollo.json
Labels: ✍ chore: profile addition, small, LGTM

#5163 Drabzit patch 1
  data/Drabzit.json
Labels: ✍ chore: profile addition, medium, LGTM

#5168 fix: envar link
  pages/docs/environments/gitpod.mdx
  pages/docs/environments/local-development-docker-compose.mdx
  pages/docs/environments/local-development.mdx
Labels: small

#5153 Delete 2023-02-21-Decoding-CFPs-Twitter-Space.json [EVENT DONE]
  data/thebarshablog/events/2023-02-21-Decoding-CFPs-Twitter-Space.json
Labels: ✍ chore: profile addition, medium

#5154 Delete 2023-02-18-harvard-wecode-conf.json [EVENT DONE]
  data/thebarshablog/events/2023-02-18-harvard-wecode-conf.json
Labels: ✍ chore: profile addition, medium, kudos

#5158 Fix: Memoize user profile for performance improvement
  components/user/UserProfile.js
Labels: small

#5182 Data: RishikaVishnoi
  data/Rishikavishnoi.json
Labels: ✍ chore: profile addition, large, LGTM

#5117 fix: Add padding to inline code block
  styles/onedark.css
Labels: small

#5193 docs: contributors guide
  CONTRIBUTING.md
Labels: large, waiting-for-reviewers

#5171 data: ShivanshPratap
  data/ShivanshPratap.json
Labels: ✍ chore: profile addition, large, LGTM

#5172 data: Ashutosh-s07
  data/Ashutosh-s07.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#5174 data: Update SurajPratap10.json
  data/SurajPratap10.json
Labels: ✍ chore: profile addition, large, LGTM

#5173 data: BSatishSutar
  data/BSatishSutar.json
Labels: ✍ chore: profile addition, large, LGTM

#5176 data: aakashditya
  data/aakashditya.json
Labels: ✍ chore: profile addition, medium, LGTM

#5179 data: rohitverse
  data/rohitverse.json
Labels: ✍ chore: profile addition, large, LGTM

#5186 data:twitter account
  data/nithin999989.json
Labels: ✍ chore: profile addition, medium, LGTM

#5185 data: hishammpsnhn
  data/Hishammpsnhn.json
Labels: ✍ chore: profile addition, medium, LGTM

#5192 data:Gautam-666
  data/Gautam-666.json
Labels: ✍ chore: profile addition, large, LGTM

#5188 data: JohnnyLegault
  data/JohnnyLegault.json
Labels: ✍ chore: profile addition, medium, LGTM

#5200 data: 1010nishant
  data/1010nishant.json
Labels: ✍ chore: profile addition, large, LGTM

#5201 data:LeoAdd
  data/leo7736.json
Labels: ✍ chore: profile addition, large, LGTM

#5203 data:Ukaypromise
  data/Ukaypromise.json
Labels: ✍ chore: profile addition, large, LGTM

#4971 Raj210 kumari patch 2
  data/Raj210Kumari.json
Labels: ✍ chore: profile addition, medium, LGTM

#5199 Adding the link to my Blog in NOCODE-CHANGELOG.md
  NOCODE-CHANGELOG.md
Labels: small

#5206 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: medium

#5211 data: poojasanwal
  data/poojasanwal.json
Labels: ✍ chore: profile addition, medium, LGTM

#5214 Kellyn codes patch 2
  data/KellynCodes.json
Labels: ✍ chore: profile addition, medium, LGTM

#5215 Create KQuiggins.json
  data/KQuiggins.json
Labels: ✍ chore: profile addition, medium, LGTM

#5218 data: anurag-dhamala
  data/anurag-dhamala.json
Labels: ✍ chore: profile addition, large, LGTM

#5220 data: sahil-sagwekar2652
  data/sahil-sagwekar2652.json
Labels: ✍ chore: profile addition, large, LGTM

#5225 data: fix Gautam-666
  data/Gautam-666.json
Labels: ✍ chore: profile addition, small

#5222 data:sharsha315
  data/sharsha315.json
Labels: ✍ chore: profile addition, medium, LGTM

#5219 data:rezarex
  data/rezarex.json
Labels: ✍ chore: profile addition, medium, LGTM

#5196 BSatishSutar-patch-1 - Added Social links and milestones
  data/BSatishSutar.json
Labels: ✍ chore: profile addition, large, LGTM

#5228 data: panquesito7
  data/Panquesito7.json
Labels: ✍ chore: profile addition, medium, LGTM

#5231 data: dominicfrei
  data/DominicFrei.json
Labels: ✍ chore: profile addition, large, LGTM

#5230 data: panquesito7
  data/Panquesito7.json
Labels: ✍ chore: profile addition, small, LGTM

#5221 data:KishanGupta
  data/KishanGupta114.json
Labels: ✍ chore: profile addition, medium, LGTM

#5236 docs: linked to full documentation
  README.md
Labels: small

#5229 data: remove avatar key
  data/atanda0x.json
  data/ksen21.json
Labels: ✍ chore: profile addition, small

#5246 Update AtharvaRaut2002.json
  data/AtharvaRaut2002.json
Labels: ✍ chore: profile addition, small, LGTM

#5245 Data: Fahad Ali
  data/imf-ali.json
Labels: ✍ chore: profile addition, large, LGTM

#5243 update rupali-codes.json
  data/rupali-codes.json
Labels: ✍ chore: profile addition, large, LGTM

#5244 I messed up my testimony for Dominic
  data/DominicFrei/testimonials/loftwah.json
Labels: ✍ chore: profile addition, small

#5239 data: J-CODE07
  data/J-CODE07.json
Labels: ✍ chore: profile addition, medium, LGTM

#5207 data: dev-phantom
  data/dev-phantom.json
Labels: ✍ chore: profile addition, medium, LGTM

#5248 data: mrdanishsaleem
  data/mrdanishsaleem.json
Labels: ✍ chore: profile addition, large, LGTM

#5250 data: J-CODE07
  data/J-CODE07.json
Labels: ✍ chore: profile addition, small

#5265 Update mrdanishsaleem.json
  data/mrdanishsaleem.json
Labels: ✍ chore: profile addition, medium, LGTM

#5264 Bug Fixes
  data/kshitij9896.json
Labels: ✍ chore: profile addition, large, LGTM

#5262 data:LaPulgaaa
  data/LaPulgaaa.json
Labels: ✍ chore: profile addition, medium, LGTM

#5261 data: an4s911
  data/an4s911.json
Labels: ✍ chore: profile addition, medium, LGTM

#5260 Update KishanGupta114.json
  data/KishanGupta114.json
Labels: ✍ chore: profile addition, medium, LGTM

#5253 Grand rick001 patch 6
  data/grand-rick001/events/2023-03-9-apis-101-with-postman.json
Labels: ✍ chore: profile addition, small

#5252 Added glitch profile and fixed codepen icon
  data/md-abid-hussain.json
Labels: ✍ chore: profile addition, small, LGTM

#5266 data: yashpandey002
  data/yashpandey002.json
Labels: ✍ chore: profile addition, medium, LGTM

#5255 data: donaina
  data/donaina.json
Labels: ✍ chore: profile addition, medium, LGTM

#5204 data: 1010nishant
  data/1010nishant.json
Labels: ✍ chore: profile addition, large, LGTM

#5258 data: anuragts
  data/anuragts.json
Labels: ✍ chore: profile addition, large, LGTM

#4211 feat: Added playground and preview feature
  components/PreviewModal.js
  components/navbar/Navbar.js
  components/user/UserProfile.js
  pages/playground.js
Labels: large

#5267 data: VardaanAggarwal
  data/VardaanAggarwal.json
Labels: ✍ chore: profile addition, large, LGTM

#5278 Update tobySolutions.json
  data/tobySolutions.json
Labels: ✍ chore: profile addition, small, LGTM

#5128 data: juanf1990
  data/juanf1990.json
Labels: ✍ chore: profile addition, medium, LGTM

#5268 Create DrVickie8.json
  data/DrVickie8.json
Labels: ✍ chore: profile addition, large, LGTM

#5274 data: Akash Reddy Jammula
  data/Akash3121.json
Labels: ✍ chore: profile addition, medium, LGTM

#5289 Update .dockerignore file
  .dockerignore
Labels: small

#5275 Update: Shivam-katare.json
  data/Shivam-Katare.json
Labels: ✍ chore: profile addition, large, LGTM

#5287 Corrected a link in docs/how-to-guides/editing
  pages/docs/how-to-guides/editing.mdx
Labels: 🛠 goal: fix, 📄 aspect: text, small

#5284 data: paulaxisabel
  data/paulaxisabel.json
Labels: ✍ chore: profile addition, large, LGTM

#5282 data: panquesito7
  data/Panquesito7.json
Labels: ✍ chore: profile addition, medium, LGTM

#5283 Updated Milestones section
  data/CBID2.json
Labels: ✍ chore: profile addition, small, LGTM

#5277 data: Gautam-666
  data/Gautam-666.json
Labels: ✍ chore: profile addition, large, LGTM

#5276 Update Tusharjagi-patch-3
  data/Tusharjagi.json
Labels: ✍ chore: profile addition, medium, LGTM

#5273 Playground refactor
  components/Button.js
  components/FallbackImage.js
  components/form/input.js
  components/modals/ProfilePreview.js
  components/navbar/Navbar.js
  components/user/UserPage.js
  components/user/UserProfile.js
  components/user/UserTestimonials.js
  pages/playground.js
  pages/search.js
Labels: large

#5295 docs: user changelog
  pages/changelog.js
Labels: small

#5298 data:AFB-M
  data/AFB-M.json
Labels: ✍ chore: profile addition, medium, LGTM

#5304 docs: reviewing pull requests
  CONTRIBUTING.md
Labels: ✨ goal: improvement, 📄 aspect: text, small

#5008 Update avie-dev.json
  data/avie-dev.json
Labels: ✍ chore: profile addition, small, LGTM

#5067 Feature filter map by tag
  components/map/Map.js
  pages/map.js
Labels: large

#5303 data: EslemOuederni
  data/EslemOuederni.json
Labels: ✍ chore: profile addition, medium, LGTM

#5297 data: SageKyle
  data/SageKyle.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#5124 Convert fetches to function calls for index page
  pages/api/statistics/today.js
  pages/api/statistics/totals.js
  pages/index.js
Labels: large

#5109 data:AyebakuroOruwori
  data/AyebakuroOruwori.json
Labels: ✍ chore: profile addition, large, LGTM

#5334 data:harshit-002
  data/harshit-002.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#5328 Zende aditya patch 3
  data/ZendeAditya.json
Labels: ✍ chore: profile addition, small, LGTM

#5340 Editing my profile
  data/jmgrd98.json
Labels: ✍ chore: profile addition, small, LGTM

#5320 data: fatemaker254
  data/fatemaker254.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#5321 data: ArjanDhakal
  data/arjandhakal.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#5323 Changed my "Socials" to "links"
  data/VarchasvH.json
Labels: ✍ chore: profile addition, small, LGTM

#5326 added ni5arga.json
  data/ni5arga.json
Labels: ✍ chore: profile addition, medium, LGTM

#5322 data:Akhilbisht798
  data/Akhilbisht798.json
Labels: ✍ chore: profile addition, medium, LGTM

#5327 data: khushalarora
  data/khushalarora.json
Labels: ✍ chore: profile addition, large, LGTM

#5330 data: itsshahinhere
  data/itsshahinhere.json
Labels: ✍ chore: profile addition, medium, LGTM

#5333 data: JohnOkari
  data/JohnOkari.json
Labels: ✍ chore: profile addition, medium, LGTM

#5338 Update shubhsharma19.json
  data/shubhsharma19.json
Labels: ✍ chore: profile addition, medium, LGTM

#5341 data: Uthycloud
  data/Uthycloud.json
Labels: ✍ chore: profile addition, small, LGTM

#5343 data: tenyapious
  data/tenyapious.json
Labels: ✍ chore: profile addition, small, LGTM

#5345 Update shubhsharma19.json
  data/shubhsharma19.json
Labels: ✍ chore: profile addition, small, LGTM

#5336 data:coder-chahal
  data/coder-chahal.json
Labels: ✍ chore: profile addition, medium, LGTM

#5342 data: iAnonymous3000
  data/iAnonymous3000.json
Labels: ✍ chore: profile addition, medium, LGTM

#5347 [Add]: YouTube Channel links and Milestone at ```Arindam200.json```
  data/Arindam200.json
Labels: ✍ chore: profile addition, large, LGTM

#5353 data: AKHIL-GIREESH
  data/AKHIL-GIREESH.json
Labels: ✍ chore: profile addition, medium, LGTM

#5354 data:HaroonHayat
  data/hayatharoon.json
Labels: ✍ chore: profile addition, medium, LGTM

#5357 data: aakshitaa
  aakshitaa.json
Labels: large

#5372 Update iAnonymous3000.json
  data/iAnonymous3000.json
Labels: ✍ chore: profile addition, large, LGTM

#5368 data: CodingWithCard
  data/CodingWithCard.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#5380 data: move aakshitaa.json to `data` folder
  data/aakshitaa.json
Labels: ✍ chore: profile addition, small

#5379 add:testimonials on my profile
  data/MadhuSaini22.json
Labels: ✍ chore: profile addition, small, LGTM

#5369 data:MAYANKpandey14
  data/MAYANKpandey14.json
Labels: ✍ chore: profile addition, medium, LGTM

#5382 Madhu saini22 patch 2
  NOCODE-CHANGELOG.md
Labels: ✍ chore: profile addition, small

#5391 data: Danypooh
  data/Danypooh.json
Labels: ✍ chore: profile addition, medium, LGTM

#5388 data: vprankul0306
  data/vprankul0306.json
Labels: ✍ chore: profile addition, medium, LGTM

#5387 Create mrunlikeliest.json
  data/mrunlikeliest.json
Labels: ✍ chore: profile addition, medium, LGTM

#5384 Update ankushtripathii.json
  data/ankushtripathii.json
Labels: ✍ chore: profile addition, small, LGTM

#5385 data: Tejasp2003
  data/Tejasp2003.json
Labels: ✍ chore: profile addition, medium, LGTM

#5383 data: MahabubArafat
  data/MahabubArafat.json
Labels: ✍ chore: profile addition, medium, LGTM

#5378 data:ArslanYM
  data/ArslanYM.json
Labels: ✍ chore: profile addition, medium, LGTM

#5361 data : avnigoyal25
  data/avnigoyal25.json
Labels: ✍ chore: profile addition, large, LGTM

#5359 data: mdarslan7
  data/mdarslan7.json
Labels: ✍ chore: profile addition, large, LGTM

#5358 data: dfdevaney
  data/dfdevaney.json
Labels: ✍ chore: profile addition, medium, LGTM

#5392 Create 2023-03-11-Dare-To-Be-an-Entrepreneur-IWD-2023.json
  data/SandipPalit/events/2022-08-27-Cloud-Community-Days-2022-Kolkata.json
  data/SandipPalit/events/2022-11-13-DevFest-2022-Kolkata.json
  data/SandipPalit/events/2023-02-11-TFUG-Kolkata-Reboot.json
  data/SandipPalit/events/2023-02-22-aws-innovate.json
  data/SandipPalit/events/2023-03-11-Dare-To-Be-an-Entrepreneur-IWD-2023.json
  data/SandipPalit/events/Being-Women-IWD-Celebration.json
Labels: ✍ chore: profile addition, medium

#5331 [FEATURE] Tag filter highlight on map page #5313
  pages/map.js
Labels: large

#5377 data: sahil-sagwekar2652
  data/sahil-sagwekar2652.json
  data/sahil-sagwekar2652/events/2023-03-11-MumbaiFOSS.json
Labels: ✍ chore: profile addition, medium, LGTM

#5397 data: added tags to myprofile .
  data/pacifiquem.json
Labels: ✍ chore: profile addition, small, LGTM

#5402 Adding of json data fadebowley.json to LinkFree
  data/fadebowaley.json
Labels: ✍ chore: profile addition, medium, LGTM

#5409 data:Visakan-official
  data/Visakan-official.json
Labels: ✍ chore: profile addition, medium, LGTM

#5335 create a personal profile
  data/officialrajdeepsingh.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#5411 data: deepakrudrapaul
  data/deepakrudrapaul.json
Labels: ✍ chore: profile addition, large, LGTM

#5396 feat: clear filters for map (#5312)
  pages/map.js
Labels: large

#4438 Added location to all events (In-person && Remote)
  components/event/EventCard.js
  pages/docs/how-to-guides/events.mdx
Labels: medium

#5424 Event location
  components/event/EventCard.js
  data/eddiejaoude/events/2023-07-27-wearedevelopers.json
  data/eddiejaoude/events/2023-09-18-talk-infobip.json
  pages/docs/how-to-guides/events.mdx
Labels: ✍ chore: profile addition, large

#5426 docs: event location
  pages/docs/how-to-guides/events.mdx
Labels: medium

#5428 docs: new domain notes in changelog
  pages/changelog.js
Labels: small

#5125 Fixed #4944 - [FEATURE] hover effect on docs page - Border added
  pages/docs/index.js
Labels: small

#5386 data:sebashmh
  data/sebashmh.json
Labels: ✍ chore: profile addition, large, LGTM

#5408 data:ShuShu-8788
  data/ShuShu-8788.json
Labels: ✍ chore: profile addition, large, LGTM

#5436 Update README.md
  README.md
Labels: medium

#5430 Docs hover
  pages/docs/index.js
Labels: small

#5444 docs: update link to latest domain
  pages/docs/how-to-guides/editing.mdx
Labels: small

#5460 docs: fix typos on "local development with docker compose" page
  pages/docs/environments/local-development-docker-compose.mdx
Labels: small

#5449 data: aarkaynegi
  data/aarkaynegi.json
Labels: ✍ chore: profile addition, medium, LGTM

#5462 data: tausiq2003
  data/tausiq2003.json
Labels: ✍ chore: profile addition, large, LGTM

#5317 data: analizzi
  data/analizzi.json
Labels: ✍ chore: profile addition, medium, LGTM

#5417 data: tejas-raskar
  data/tejas-raskar.json
Labels: ✍ chore: profile addition, large, LGTM
