Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-07, with the labels that each got.

#7881 data: jainam-r
  data.jainam-r.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers

#7889 data: jainam-r
  data/jainam-r.json
Labels: ✍ chore: profile, small, waiting-for-reviewers

#7562 Logging Improvement
  config/logger.js
Labels: medium, waiting-for-reviewers, issue linked

#7894 Revert logger
  .github/workflows/vercel-preview.yml
  config/logger.js
Labels: medium, waiting-for-reviewers

#7898 data: Pravesh-Sudha.json
  data/Pravesh-Sudha.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#7900 Fix pr random profile
  .env.example
  components/user/UserMini.js
  config/schemas/serverSchema.js
  pages/account/statistics.js
  pages/api/discover/random.js
  pages/index.js
Labels: large, waiting-for-reviewers

#7902 Update reviewers.mdx
  pages/account/no-profile.js
  pages/docs/contributing/reviewers.mdx
  pages/docs/profile-tips.mdx
Labels: small, waiting-for-reviewers

#7884 feat: testimonial ordering
  models/Profile.js
  models/Profile/Event.js
  models/Profile/Milestone.js
  package-lock.json
  package.json
  pages/account/manage/event/[[...data]].js
  pages/account/manage/milestone/[[...data]].js
  pages/account/manage/testimonials.js
  pages/api/account/manage/testimonials.js
  pages/api/profiles/[username]/index.js
  pages/api/system/reload.js
Labels: large, waiting-for-reviewers

#7905 fix: random profile text
  components/user/UserMini.js
  pages/index.js
Labels: small, waiting-for-reviewers

#7906 fix: profiles with no events
  pages/api/profiles/[username]/index.js
Labels: large, waiting-for-reviewers

#7913 fix: link and linkstats relationship
  models/Link.js
  pages/api/profiles/[username]/links/[_id].js
Labels: medium, waiting-for-reviewers

#7926 docs: fix broken link
  pages/docs/index.js
Labels: small, waiting-for-reviewers

#7910 data: Parvej2001
  data/Parvej2001.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7925 data:KrownWealth
  data/KrownWealth.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#7928 docs: fix missing next auth url
  pages/docs/environments/environment-variables.mdx
Labels: small, waiting-for-reviewers

#7930 data: paaggeli
  data/paaggeli.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7893 Fix #7871 : fixed negative value for event ticket price
  pages/account/manage/event/[[...data]].js
Labels: small, waiting-for-reviewers, issue linked

#7936 fix: manage testimonial dark mode
  pages/account/manage/testimonials.js
Labels: small, waiting-for-reviewers

#7644 fix:7102 - Added config to enable hot reload when project started with docker compose up
  docker-compose.yml
Labels: small, waiting-for-reviewers, issue linked

#7941 fix: responsive background color for mange profile
  pages/account/manage/profile.js
Labels: small, waiting-for-reviewers

#7946 data: nikitakoselev
  data/nikitakoselev.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7951 data: nikitakoselev
  data/nikitakoselev.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7954 Update profile Collins-Omariba.json
  data/Collins-Omariba.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#7955 fix: popular docs link
  pages/docs/index.js
Labels: small, waiting-for-reviewers

#7931 [Bug fix]: move tab nav to the top #7875
  pages/account/manage/profile.js
  pages/account/statistics.js
Labels: small, waiting-for-reviewers, issue linked

#7950 Handle milestones w/ non-Date info in date field
  pages/api/system/reload.js
Labels: medium, waiting-for-reviewers, issue linked

#7919 data: Alexxanderr20
  data/Alexxanderr20.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7963 data: piaseckijulian
  data/piaseckijulian.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7947 fix: margin issue in homepage
  components/Testimonials.js
Labels: small, waiting-for-reviewers, issue linked

#7967 chore: remove profile
  data/ManishBisht777.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#7961 data: Abhish7k
  data/Abhish7k.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7564 feat: Add another layout
  components/user/themes/grid/EventCard.js
  components/user/themes/grid/UserEvents.js
  components/user/themes/grid/UserPage.js
  components/user/themes/grid/UserTestimonials.js
Labels: large, waiting-for-reviewers, issue linked

#7969 Added padding between text and button in testimonial section
  pages/account/manage/testimonials.js
Labels: small, waiting-for-reviewers, issue linked

#7982 data: SagarBawanthade
  data/SagarBawanthade.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7979 data: amanpreet-dev
  data/amanpreet-dev.json
  data/amanpreet-dev/events/2023-05-01-hashnode-bootcamp.json
Labels: ✍ chore: profile, large, waiting-for-reviewers

#7988 data: SaraviaMartin
  data/SaraviaMartin.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#7989 data:Kaisunoo
  data/kaisunoo.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#7990 data: Update vamsikurimeti.json
  data/vamsikurimeti.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#7995 Update chetannada.json
  data/chetannada.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#7992 Added my Data
  data/danishhansari.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7998 fix: improve docs & broken links
  pages/docs/contributing/reviewers.mdx
  pages/docs/environments/gitpod.mdx
  pages/docs/full-profile-example.mdx
  pages/docs/how-to-guides/bio-json.mdx
  pages/docs/how-to-guides/events-json.mdx
  pages/docs/how-to-guides/links-json.mdx
  pages/docs/how-to-guides/milestones-json.mdx
  pages/docs/how-to-guides/socials-shortcuts-json.mdx
  pages/docs/how-to-guides/tags-json.mdx
  pages/docs/profile-tips.mdx
Labels: large, waiting-for-reviewers

#8002 fix: sort links when managing
  components/user/UserLink.js
  components/user/UserLinks.js
  pages/account/manage/links.js
  pages/api/account/manage/links.js
  pages/api/profiles/[username]/index.js
Labels: large, waiting-for-reviewers

#8010 fix: user changelog update
  pages/changelog.js
Labels: medium, waiting-for-reviewers

#7994 Closes #7920
  pages/account/manage/testimonials.js
Labels: medium, waiting-for-reviewers, issue linked

#7985 fix : Inputs Values Bug #7962
  pages/account/manage/event/[[...data]].js
  pages/account/manage/milestone/[[...data]].js
Labels: large, waiting-for-reviewers, issue linked

#8013 Fix pr 7985 for default form values
  pages/account/manage/event/[[...data]].js
  pages/account/manage/milestone/[[...data]].js
Labels: medium, waiting-for-reviewers

#7977 Fix pr 7564 (2 column profile layout)
  components/user/UserPage.js
  components/user/themes/UserColumn2.js
  config/app.json
  models/Profile.js
  pages/account/manage/profile.js
Labels: large, waiting-for-reviewers

#7991 data: Kishore-r-77
  data/Kishore-r-77.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8005 data: Viveksati5143
  data/Viveksati5143.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8007 file deleted
  data/1010nishant.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8017 data:itssouray
  data/itssouray.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8019 bug fixed - #7981
  pages/404.js
Labels: small, waiting-for-reviewers

#8021 docs: alert to restart for envar changes
  pages/docs/environments/environment-variables.mdx
Labels: medium, waiting-for-reviewers

#7993 Remove 0 when there are no links
  components/user/UserLinks.js
Labels: small, waiting-for-reviewers, issue linked

#8027 fix: no tags on profile then hide
  components/user/UserProfile.js
  pages/api/account/manage/profile.js
Labels: medium, waiting-for-reviewers

#8032 fix: roadmap responsive wit badge
  pages/roadmap.js
Labels: medium, waiting-for-reviewers

#8034 fix: use zod config
  pages/account/manage/event/[[...data]].js
  pages/account/manage/link/[[...data]].js
  pages/account/manage/links.js
  pages/account/manage/milestone/[[...data]].js
  pages/account/manage/profile.js
  pages/account/manage/testimonials.js
Labels: medium, waiting-for-reviewers

#8037 data: Mohd Wamid
  data/Mohd-Wamid.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8041 data: added events to Viveksati5143
  data/Viveksati5143/events/2023-06-17-first-in-person-meetup.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers

#8044 chore: remove schmelto.json
  data/schmelto.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#7976 [fix]: NewsLetter form position in mobile view
  pages/newsletter.js
Labels: small, waiting-for-reviewers, issue linked

#8026 fix(): Alert components should start with capital letter
  components/Alert.js
Labels: small, waiting-for-reviewers, issue linked

#8049 feat: admin section with basic stats
  .env.docker
  .env.example
  config/schemas/serverSchema.js
  pages/admin/index.js
  pages/api/admin/stats.js
Labels: large, waiting-for-reviewers

#7700 feat: social share for profile
  components/ClipboardCopy.js
  components/Modal.js
  components/user/UserProfile.js
  config/socials.js
Labels: large, waiting-for-reviewers, issue linked

#8022 fix : inconsistent styling in Events section
  components/user/UserEvents.js
Labels: large, waiting-for-reviewers, issue linked

#8024 data: IfeanyiOsuji.json
  data/IfeanyiOsuji.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8051 chore: remove profile
  data/shoebilyas123.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#7912 ci: Add vercel preview PR workflow
  .github/workflows/vercel-pr-preview.yml
Labels: large, waiting-for-reviewers, CI/CD

#8058 data: Bharath292003
  data/Bharath292003.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8063 data: beherabikram
  data/beherabikram.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8072 Update Bharath292003.json
  data/Bharath292003.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8064 data: Create 2023-06-08-AWSOME-DAY-Conference.json
  data/Viveksati5143/events/2023-06-08-AWSOME-DAY-Conference.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers

#8018 Create hakkanoodels.json
  data/hakkanoodles.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8067 data TusharPaul01
  data/TusharPaul01.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8075 Update environment-variables.mdx
  pages/docs/environments/environment-variables.mdx
Labels: small, waiting-for-reviewers, issue linked

#7987 Add basic tests for forms
  .github/workflows/build.yml
  components/account/manage/edit.js
  components/account/manage/navigation.js
  components/event/EventCard.js
  components/form/Toggle.js
  components/user/UserLink.js
  components/user/UserMilestone.js
  components/user/UserMilestones.js
  pages/account/manage/profile.js
  pages/account/manage/testimonials.js
  tailwind.config.js
  tests/manage/events.spec.js
  tests/manage/links.spec.js
  tests/manage/milestones.spec.js
  tests/manage/profile.spec.js
  tests/manage/testimonials.spec.js
Labels: large, waiting-for-reviewers, tests

#8077 deleted data/VaishnavJois.json
  data/VaishnavJois.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8081 chore: deleted AliMora83.json
  data/AliMora83.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8084 data: Sudarshan-t-1999
  data/Sudarshan-t-1999.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8065 data: AbhishekSharma
  data/AbhishekSharma6903.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#7522 Community events to map
  components/map/Clusters.js
  components/map/EventMarker.js
  components/map/Map.js
  models/Profile/Event.js
  pages/api/events.js
  pages/api/system/reload.js
  pages/map.js
  public/placard.png
Labels: large, waiting-for-reviewers, tests, storybook, issue linked

#8073 data: paudelpr1
  data/paudelpr1.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8082 Updates
  data/ibilalkayy.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8086 data: PandeyHarsh433
  data/PandeyHarsh433.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8095 Dhruv sood patch 1
  data/Dhruv-Sood.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8030 data: money8203.json
  data/money8203.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8099 FEAT: Social Share Button improved
  components/Badge.js
  components/user/UserProfile.js
Labels: small, waiting-for-reviewers

#8087 [fix]: comma misbehave in profile form section
  components/user/UserProfile.js
  pages/account/manage/profile.js
  pages/api/account/manage/profile.js
Labels: medium, waiting-for-reviewers

#8104 cleanup AxeBuilder imports
  tests/404.spec.js
  tests/changelog.spec.js
  tests/docs/docs.spec.js
  tests/events.spec.js
  tests/home.spec.js
  tests/map.spec.js
  tests/playground.spec.js
  tests/profile.spec.js
  tests/search.spec.js
Labels: medium, waiting-for-reviewers, tests

#8106 docs: more info on gh token
  pages/docs/environments/environment-variables.mdx
Labels: medium, waiting-for-reviewers

#8096 data: DavidRaigozaJ
  data/DavidRaigozaJ.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8110 added my json file to create profile
  data/Chavda-Mitul.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8100 fix: broken link in testimonial github action
  .github/workflows/testimonial.yml
Labels: small, waiting-for-reviewers, issue linked

#8102 Updated dropdown options to improve visibility in dark mode
  components/form/Select.js
Labels: small, waiting-for-reviewers

#8113 fix image overflow
  components/GitHubAccelerator.js
Labels: small, waiting-for-reviewers

#7747 fix: Skip-Empty-Releases (#7496)
  .github/workflows/release.yml
  .github/workflows/vercel.yml
Labels: small, waiting-for-reviewers, issue linked

#8115 data: Update Viveksati5143.json
  data/Viveksati5143.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8120 Create DevP-ai.json
  data/DevP-ai.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8123 add my blog to LinkFree community resources
  pages/docs/community-resources.mdx
Labels: small, waiting-for-reviewers

#8128 docs: share with social media
  pages/changelog.js
Labels: small, waiting-for-reviewers

#8131 Revert "fix: releases to skip if empty (#7496) (#7747)"
  .github/workflows/release.yml
  .github/workflows/vercel.yml
Labels: small, waiting-for-reviewers

#8134 fix: release action skip on empty
  .github/workflows/release.yml
  .github/workflows/vercel.yml
Labels: small, waiting-for-reviewers

#8137 docs: json to forms
  pages/docs/how-to-guides/json-to-forms.mdx
Labels: large, waiting-for-reviewers

#8138 feat: daily app stats
  models/Stats.js
  pages/api/system/stats.js
  vercel.json
Labels: large, waiting-for-reviewers

#8126 Deleted data:yoyoekta.json
  data/yoyoekta.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8130 data: DevYoma
  data/DevYoma.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8133 data:CodeKisku
  data/CodeKisku.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8142 data: shubhampatil9500
  data/shubhampatil9500.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8144 Improve forms Select & DropDown in dark mode
  components/form/DropDown.js
  components/form/Select.js
  stories/components/form/DropDown.stories.js
  stories/components/form/Select.stories.js
Labels: large, waiting-for-reviewers, storybook

#8149 Delete this suspicious Loftwah character
  data/loftwah.json
  data/loftwah/testimonials/AussieDev81.json
  data/loftwah/testimonials/CBID2.json
  data/loftwah/testimonials/eddiejaoude.json
  data/loftwah/testimonials/ibilalkayy.json
  data/loftwah/testimonials/krishstwt.json
  data/loftwah/testimonials/shubhsharma19.json
  data/loftwah/testimonials/stevenovak123.json
Labels: ✍ chore: profile, large, waiting-for-reviewers

#8127 fix: The delete button's text color has been changed from black to white
  components/ConfirmDialog.js
Labels: small, waiting-for-reviewers, issue linked

#7942 fix: Event CSS issue fixed
  components/event/EventCard.js
  components/user/UserEvents.js
  models/Profile/Event.js
  pages/account/manage/event/[[...data]].js
  pages/api/account/manage/event/[[...data]].js
  pages/events.js
Labels: medium, waiting-for-reviewers, issue linked

#8036 Create Gulam-Mustafa231999.json
  data/Gulam-Mustafa231999.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8157 Update ankushtripathii.json
  data/ankushtripathii.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8162 data:manishd17
  data/manishd17.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#7960 [BUG FIX] milestones tab ui is not consistent with others
  components/user/UserMilestones.js
  pages/account/manage/testimonials.js
Labels: medium, waiting-for-reviewers, issue linked

#8164 Created abhijeetgauravm.json
  data/abhijeetgauravm.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8167 new project added
  data/kirtankp.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8170 Fix PR 7960 for milestone alert consistency
  components/user/UserEvents.js
  components/user/UserLinks.js
  components/user/UserMilestones.js
  components/user/UserTestimonials.js
  pages/account/manage/links.js
  pages/account/manage/testimonials.js
Labels: large, waiting-for-reviewers

#8175 data: iamfasal
  data/iamfasal.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8179 deleted data/connectrajesh.json file
  data/connectrajesh.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8173 data: MohdSaquib114
  data/MohdSaquib114.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8174 data: flexzy2011
  data/flexzy2011.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#7966 feat: redirect router
  pages/account/manage/event/[[...data]].js
  pages/account/manage/events.js
  pages/account/manage/link/[[...data]].js
  pages/account/manage/links.js
  pages/account/manage/milestone/[[...data]].js
  pages/account/manage/milestones.js
Labels: large, waiting-for-reviewers, issue linked

#8184 data: Pravesh-Sudha.json
  data/Pravesh-Sudha.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8187 Use test users for all tests
  pages/admin/index.js
  tests/admin/index.spec.js
  tests/data/_test-profile-user-1.json
  tests/data/_test-profile-user-2.json
  tests/data/_test-profile-user-3.json
  tests/data/_test-profile-user-4.json
  tests/data/_test-profile-user-5.json
  tests/data/_test-profile-user-6.json
  tests/data/_test-profile-user-6/events/2022-12-10-talk.json
  tests/data/_test-profile-user-6/events/2027-09-18-talk-infobip.json
  tests/data/_test-profile-user-6/testimonials/FrancescoXX.json
  tests/data/_test-profile-user-6/testimonials/unknown-loftwah.json
  tests/profile.spec.js
  tests/setup/global-setup.js
  tests/setup/global-teardown.js
  tests/util/reload-check.js
  tests/util/reload-fake.js
Labels: large, waiting-for-reviewers, tests

#8199 Delete priyankarpal.json
  data/priyankarpal.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8201 Fixes typo in signup success message for premium updates
  pages/premium.js
Labels: small, waiting-for-reviewers

#8203 Removed unnecessary Console.log()
  components/user/UserPage.js
Labels: small, waiting-for-reviewers

#8197 Create bellsofaba.json
  data/bellsofaba.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8200 Deletes data for mocdaniel as it's managed via forms now
  data/mocdaniel.json
  data/mocdaniel/events/2023-02-07-civo-navigate.json
  data/mocdaniel/events/2023-04-18-kubecon-eu.json
Labels: ✍ chore: profile, large, waiting-for-reviewers

#8207 data : SagarBawanthade
  data/SagarBawanthade.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8190 data: Saan-king
  data/Saan-king.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8211 data: Sankhadip-Roy
  data/Sankhadip-Roy.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8216 Create adityjoshi.json
  data/adityjoshi.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8158 BUG Fix: Events are now sorted in date ascending order
  pages/api/events.js
Labels: small, waiting-for-reviewers, issue linked

#8222 data: DavidRaigozaJ
  data/DavidRaigozaJ.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8226 docs: missing docs in envar for admin users
  pages/docs/environments/environment-variables.mdx
Labels: medium, waiting-for-reviewers

#8178 Feat: Edit on GitHub section added
  components/EditOnGithub.js
  components/navbar/SideNav.js
Labels: large, waiting-for-reviewers, issue linked

#8229 data: update profile with milestones
  data/Ananya2001-an.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM, kudos

#8233 data: theanantchoubey
  data/theanantchoubey.json
Labels: ✍ chore: profile, large, waiting-for-reviewers, LGTM

#8238 data: Create 13-07-2023-AWS-Builders-Online-Series.json
  data/Viveksati5143/events/13-07-2023-AWS-Builders-Online-Series.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers

#8241 Update SandipPalit.json
  data/SandipPalit.json
Labels: ✍ chore: profile, small, waiting-for-reviewers, LGTM

#8192 fix: profile card hover color
  components/user/UserCard.js
Labels: small, waiting-for-reviewers, issue linked

#8246 data: Pravesh-Sudha.json
  data/Pravesh-Sudha.json
Labels: ✍ chore: profile, medium, waiting-for-reviewers, LGTM

#8254 data: adityjoshi
  data/adityjoshi.json
Labels: ✍ chore: profile addition

#8252 data: biswabaibhab007
  data/biswabaibhab007.json
Labels: ✍ chore: profile addition

#8267 Renamed `docker-compose.yml` to `compose.yml`
  .dockerignore
  compose.yml
Labels: issue linked

#8228 Setup codeql checking
  .github/workflows/codeql.yml
  pages/api/search/index.js
  pages/search.js
Labels: large, waiting-for-reviewers

#8284 data: Update Viveksati5143.json
  data/Viveksati5143.json
Labels: ✍ chore: profile
