Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-05, with the labels that each got.

#6416 chore: update docker image version
  docker-compose.yml
  mongo-compose.yml
Labels: 💻 aspect: code, small, waiting-for-reviewers, Docker

#6304 Closes issue #6287 using optional chaining
  components/user/UserLinks.js
  components/user/UserPage.js
Labels: small, waiting-for-reviewers, issue linked

#6227 doc: Put all local dev env instructions in one place
  README.md
  components/mdx/ComponentStyle.js
  components/mdx/H2.js
  pages/docs/environments/local-development-docker-compose.mdx
  pages/docs/environments/local-development.mdx
  pages/docs/index.js
Labels: large, issue linked

#6527 data: RushikeshGandhmal
  data/RushikeshGandhmal.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6533 data: Dhirendra17
  data/Dhirendra17.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6536 data: nvspavankalyanch
  data/nvspavankalyanch.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6534 Create testimonials for Aaron
  data/aaronmack/testimonials/milkBoy.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers

#6535 Update aaronmack.json
  data/aaronmack.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6537 data:curi-adi
  data/curi-adi.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6538 Update existing profile data Het-Joshi.json
  data/Het-Joshi.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6540 docs: linkfree cli
  pages/docs/environments/linkfree-cli.mdx
Labels: small, waiting-for-reviewers

#6539 Use Mongoose aggregate to sum views & clicks
  pages/api/statistics/totals.js
Labels: medium, waiting-for-reviewers

#6518 updated profile
  data/Shalini469717.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6522 Created liza-bhutani.json
  data/liza-bhutani.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6524 Fixed the double borders on inputs; issue #6310
  components/form/input.js
  pages/icons.js
  pages/playground.js
  pages/search.js
  styles/globals.css
Labels: large, waiting-for-reviewers

#6543 Update testimonials
  data/aaronmack.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6544 data NickAzureDevops
  data/NickAzureDevops.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6546 Mnik7044 patch 1
  data/mnik7044.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6547 data: daniloparrajr
  data/daniloparrajr.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6548 Create thtauhid.json
  data/thtauhid.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6294 Closes #6249 Removed placeholder and added default json
  pages/playground.js
Labels: medium, waiting-for-reviewers, issue linked

#6552 Fix playground zhreyu
  components/form/Input.js
  components/form/input.js
  pages/playground.js
  pages/search.js
  tests/playground.spec.js
Labels: large, waiting-for-reviewers, tests

#6147 index imports for models (#5654)
  models/index.js
  pages/api/account/statistics.js
  pages/api/auth/db-adapter.js
  pages/api/discover/random.js
  pages/api/statistics/today.js
  pages/api/statistics/totals.js
  pages/api/users/[username]/index.js
  pages/api/users/[username]/links/[url].js
  pages/api/users/index.js
  services/profiles/getLocation.js
Labels: large, waiting-for-reviewers, issue linked

#6549 (fix): date visibility on stats page
  pages/account/statistics.js
Labels: small, waiting-for-reviewers

#6567 data: Eric obeng patch 2
  data/Eric-Obeng.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6562 data: amanpreet-dev
  data/amanpreet-dev.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6560 data: Mayank-Sharma17
  data/Mayank-Sharma17.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6558 Update rohitagr0310.json
  data/rohitagr0310.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6563 Implementing useRef hook in userDetails QR
  components/user/UserProfile.js
Labels: medium, waiting-for-reviewers

#6016 (feat): custom signin page
  pages/api/auth/[...nextauth].js
  pages/auth/signin.js
Labels: large, issue linked

#6571 Technicave patch 1
  data/technicave.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6574 data: nfa1
  data/nfa1.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6564 data: amanpreet-dev
  data/amanpreet-dev/events/2023-05-01-hashnode-bootcamp.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6586 fix: events gh action
  .github/workflows/events.yml
Labels: small, waiting-for-reviewers

#6583 data: Add Viktar Patotski aka xp-vit
  data/xp-vit.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6585 data: gekkowrld
  data/gekkowrld.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6591 docs: GitHub Accelerator announcement
  README.md
Labels: medium, waiting-for-reviewers

#6589 data: the-lazy-learner
  data/the-lazy-learner.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6593 data: Update xp-vit profile
  data/xp-vit.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6569 data: itsshivamsrivastava
  data/itsshivamsrivastava.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6578 Fix login page
  components/Button.js
  pages/api/auth/[...nextauth].js
  pages/auth/signin.js
Labels: large, waiting-for-reviewers, issue linked

#6598 docs: changelog custom login page
  pages/changelog.js
Labels: small, waiting-for-reviewers

#6595 data: devhabib429
  data/devhabib429.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6605 Update KshitizRana.json
  data/KshitizRana.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6606 Update aaronmack.json
  data/aaronmack.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6607 Samil web patch 1 deleted duplicate file
  data/samil-web.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6610 data: SanskritiGupta05
  data/SanskritiGupta05.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6611 data: pranshuj73
  data/pranshuj73.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6603 GitHub accelerator
  components/GitHubAccelerator.js
  components/Testimonials.js
  pages/index.js
Labels: large, waiting-for-reviewers, issue linked

#6615 data: Webdevava
  data/Webdevava.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6618 Update Harsh3341.json
  data/Harsh3341.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6619 data:SimonLopezJara
  data/SimonLopezJara.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6620 data: Panth1823
  data/Panth1823.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6621 data: Sid-Lais
  data/Sid-Lais.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6623 stop running deploy on releases
  .github/workflows/deploy.yml
Labels: small, waiting-for-reviewers

#6627 fix bio issue
  data/Sheriff-Oladimeji.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6630 data: Create 2023-05-07-GoogleCloudCommunityDays.json
  data/priyankarpal/events/2023-05-07-GoogleCloudCommunityDays.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6625 fix: remove clicks states (#6609)
  components/user/UserLink.js
Labels: small, waiting-for-reviewers

#6633 Fix duplicate in map
  components/map/Map.js
Labels: small, waiting-for-reviewers, issue linked

#6570 data: kedar1998
  data/kedar1998.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6651 data: C0dewordSky
  data/C0dewordSky.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6650 Updated the Links
  data/ibilalkayy.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6647 data: money8203
  data/money8203.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6645 data: HassanTanveer
  data/HassanTanveer.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6652 data:Rohit2k3
  data/rohit2k3.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6643 data: Update sarthakroy2002 data
  data/sarthakroy2002.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6634 Create exzekai.json
  data/exzekai.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6646 GitHub icon visibility on both light and dark mode
  config/icons.json
Labels: small, waiting-for-reviewers

#6655 ci: update cron time - prettier.yml
  .github/workflows/prettier.yml
Labels: small, waiting-for-reviewers

#6656 ci: Add cron to publish-ghcr.yml
  .github/workflows/publish-ghcr.yml
Labels: small, waiting-for-reviewers

#6636 data:SarthakNegi
  data/sarthaksarthak9.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6653 data: bakar-dev
  data/bakar-dev.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6654 data:zheroin
  data/zheroin.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6659 data: money8203
  data/money8203.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6665 Technicave patch 2
  data/technicave.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6639 Events file updated
  data/SandipPalit/events/2023-05-07-Cloud-Community-Day-Kolkata-2023-Kolkata.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers

#6641 data: OmkarBorhade98 LinkFree Profile
  data/OmkarBorhade98.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6664 Create jordeguevara.json
  data/jordeguevara.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6670 fix: Remove if statement & add default values for props
  components/PageHead.js
Labels: large, waiting-for-reviewers

#6580 Removed unnecessary useState
  components/navbar/Navbar.js
  pages/events.js
  pages/search.js
Labels: medium, waiting-for-reviewers

#6676 fix: highlight nav page in lightmode
  components/navbar/NavLink.js
Labels: small, waiting-for-reviewers

#6666 data:Rahul-Bhati
  data/Rahul-Bhati.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6667 Create Aditya1404Sal.json
  data/Aditya1404Sal.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6669 data : Rohit-Gupta11
  data/Rohit-Gupta11.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6674 Updated the Icon
  data/ibilalkayy.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6680 data : Rohit-Gupta11 - update profile
  data/Rohit-Gupta11.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6679 data: SAD0XER
  data/SAD0XER.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6682 data: ismail-benlaredj
  data/ismail-benlaredj.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6685 DATA:MPOTANE change bio
  data/mpotane.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6686 data: Bikramjit21
  data/Bikramjit21.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6688 data: Rohan Sasne
  data/RohanSasne.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6689 feat: update oyepriyansh
  data/oyepriyansh.json
Labels: ✍ chore: profile addition, large

#6687 Footer premium terms fix
  components/Button.js
  components/Footer.js
  pages/premium.js
  pages/terms.js
  tests/events.spec.js
  tests/icon.spec.js
  tests/playground.spec.js
  tests/search.spec.js
Labels: large, waiting-for-reviewers, tests

#6690 docs: update MongoDB Atlas setup guide for local development (#6354)
  pages/docs/environments/local-with-atlas.mdx
  pages/docs/index.js
Labels: large, waiting-for-reviewers

#6637 feat: footer, premium, terms
  components/Button.js
  components/Footer.js
  components/GitHubAccelerator.js
  pages/changelog.js
  pages/premium.js
  pages/terms.js
  tests/events.spec.js
  tests/icon.spec.js
  tests/playground.spec.js
  tests/search.spec.js
Labels: large, waiting-for-reviewers, tests

#6582 data : yosr-fourati
  data/yosr-fourati.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6703 docs: maintainers guide
  pages/docs/contributing/reviewers.mdx
  pages/docs/index.js
  pages/docs/maintainers.mdx
Labels: large, waiting-for-reviewers

#6694 data:Sagar-Wadhwa-726.json
  data/Sagar-Wadhwa-726.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6702 data: MahirMahdi
  data/MahirMahdi.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6708 data: DrVickie8.json
  data/DrVickie8.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6596 Add a link to your profile in the account tab
  pages/account/statistics.js
Labels: small, waiting-for-reviewers, issue linked

#6668 fix: Changed the user 'Skyhero-admin' to 'Skyhero-alt'
  data/Skyhero-alt.json
  package-lock.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers

#6715 fix: add a link to your profile in the account tab
  pages/account/statistics.js
Labels: medium, waiting-for-reviewers

#6716 fix: changed the user 'Skyhero-admin' to 'Skyhero-alt' (#6668)
  data/Skyhero-alt.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers

#6701 Althios patch 4
  data/althios.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6706 data: bkpecho
  data/bkpecho.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6711 data: SurajPratap10 (milestone update)
  data/SurajPratap10.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6712 Added userdata file to 'data:PratyayDhond.json'
  data/PratyayDhond.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6444 Create Garvitaj12.json
  data/Garvitaj12.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6446 Create navneet17360.json
  data/navneet17360.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6489 data: Harsh2920
  data/Harsh2920.json
Labels: ✍ chore: profile addition, medium, LGTM

#6718 Create ronak-pal1.json
  data/ronak-pal1.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6719 Updated Data:PratyayDhond.json
  data/PratyayDhond.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6494 createkritipatwa.json
  data/kritipatwa.json
Labels: ✍ chore: profile addition, medium

#6469 Create bhawanak0504
  data/bhawanak0504
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6481 Create lucky123lohar.json
  data/lucky123lohar
Labels: ✍ chore: profile addition, medium

#6477 Create Kanishk10k.json
  Kanishk10k.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6487 Create Konpal-Sharma.json
  data/Konpal-Sharma.json
Labels: ✍ chore: profile addition, medium

#6722 docs: fix maintainers channel
  pages/docs/maintainers.mdx
Labels: small, waiting-for-reviewers

#6445 Create shubhamds24.json
  data/shubhamds24
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6448 Create khushigahlot29.json
  khushigahlot29.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6438 Create Manas-tech.json
  Manas-tech.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6492 Bhavya Mehta
  bhavyamehta4439.json
  bhavyamehta4439.json{   "name": "Sara Jaoude",   "type": "personal",   "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado" }
Labels: ✍ chore: profile addition, large

#6725 data: avionmission.json
  data/avionmission.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6731 Sara fix profiles
  data/bhavyamehta4439.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers

#6728 Update Bikramjit21.json
  data/Bikramjit21.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6733 data: SoniBasant
  data/SoniBasant.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6736 Fixed issues mentioned
  data/Tanvi-shah02.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6735 feat: roadmap
  components/Footer.js
  components/navbar/Navbar.js
  pages/roadmap.js
  tailwind.config.js
Labels: large, waiting-for-reviewers

#6742 data:ujjwalkirti
  data/ujjwalkirti.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6743 data: Stephanie Chester
  data/Stephanie-Chester.json
Labels: ✍ chore: profile addition, medium, LGTM

#6744 data rep-pierce
  data/rep-pierce.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6750 Fix eddie docs
  data/Kritipatwa16.json
  pages/maintainers.js
Labels: ✍ chore: profile addition, small, waiting-for-reviewers

#6753 1 shubham7 linkfree profile
  data/1Shubham7.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers, LGTM

#6754 data: DrVickie8.json
  data/DrVickie8.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6755 data: bishalbera
  data/bishalbera.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6756 Patch 1
  data/kirtankp.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6760 fix: links to use component
  components/GitHubAccelerator.js
  components/navbar/Navbar.js
  pages/account/no-profile.js
  pages/roadmap.js
Labels: large, waiting-for-reviewers

#6707 Fix postinstall script
  package.json
Labels: small, waiting-for-reviewers, issue linked

#6765 Fix postinstall script
  package-lock.json
  package.json
Labels: medium, waiting-for-reviewers

#6809 data: bkpecho.json
  data/bkpecho.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6808 Update oyepriyansh.json
  data/oyepriyansh.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6805 data: manojsai1
  data/manojsai1.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6804 Update khushbumaheshwarii.json
  data/khushbumaheshwarii.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6803 data:kirtankp.json
  data/kirtankp.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#6779 data: poorvijn
  data/poorvijn.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6777 docs: added blog resources
  pages/docs/community-resources.mdx
Labels: small, waiting-for-reviewers

#6769 data:LucF120
  data/LucF120.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6773 Create rakesh-nj.json
  data/rakesh-nj.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#6768 data: adisuyash
  data/adisuyash.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM
