Repository EddieHubCommunity/BioDrop, pull requests merged in 2023-02, with the labels that each got.

#4317 removed extra main tag
  pages/index.js
Labels: small, waiting-for-reviewers

#4334 data: krshkun
  data/krshkun.json
Labels: ✍ chore: profile addition, small, LGTM

#3841 Attending/Speaking information added in personal event card
  components/event/EventCard.js
  components/user/UserEvents.js
  pages/docs/how-to-guides/events.mdx
Labels: large

#4343 Issue 3711
  components/event/EventCard.js
  data/eddiejaoude/events/2023-03-10-devrelcon.json
  data/eddiejaoude/events/2023-09-18-talk-infobip.json
  pages/docs/how-to-guides/events.mdx
Labels: ✍ chore: profile addition, large

#4250 fix link
  pages/docs/quickstart.mdx
Labels: ✨ goal: improvement, 📄 aspect: text, small

#4298 Update sidharthviz.json
  data/sidharthviz.json
Labels: ✍ chore: profile addition, large, LGTM

#4296 Update priyankarpal.json
  data/priyankarpal.json
Labels: ✍ chore: profile addition, small, LGTM

#4187 Ibukunoluwanap patch 1
  data/ibukunoluwanap.json
Labels: ✍ chore: profile addition, large, LGTM

#4314 Update MadhuSaini22 Profile
  data/MadhuSaini22.json
  data/MadhuSaini22/testimonials/loftwah.json
Labels: ✍ chore: profile addition, large, LGTM

#4345 Parth ranalkar patch 2
  data/parth-ranalkar.json
Labels: ✍ chore: profile addition, large, LGTM

#4351 data: money8203
  data/money8203.json
Labels: ✍ chore: profile addition, small, LGTM

#4272 data: Chrisidoko
  data/Chrisidoko.json
Labels: ✍ chore: profile addition, large, LGTM

#4337 foss2cyber patch 2
  data/foss2cyber.json
Labels: ✍ chore: profile addition, medium, LGTM

#4341 data: raghu-007
  data/raghu-007.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#4300 data: akhil3shh
  data/akhil3shh.json
Labels: ✍ chore: profile addition, large, LGTM

#4327 Update Drabzit.json
  data/Drabzit.json
Labels: ✍ chore: profile addition, large, LGTM

#4350 data: PRATHAM-099
  data/PRATHAM-099.json
Labels: ✍ chore: profile addition, medium, LGTM

#4357 Added Testimonial of MadhuSaini22
  data/Arindam200.json
Labels: ✍ chore: profile addition, small, LGTM

#4326 data: dmprieto
  data/dmprieto.json
Labels: ✍ chore: profile addition, medium, LGTM

#4323 Create Exar04.json
  data/Exar04.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#4316 data: Badbatunde
  data/Badbatunde.json
Labels: ✍ chore: profile addition, medium, LGTM

#4290 Update data: Collins-Omariba
  data/Collins-Omariba.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#4210 data:ayush-3150
  data/ayush-3150.json
Labels: ✍ chore: profile addition, large, LGTM

#4209 data: theVatsal3802
  data/theVatsal3802.json
  data/theVatsal3802/events/25-01-2023-flutter-forward.json
Labels: ✍ chore: profile addition, large, waiting-for-reviewers

#3597 alignment of headings
  pages/discover.js
Labels: small

#4373 data: SandipPalit #4275
  data/SandipPalit/events/2023-02-22-aws-innovate.json
Labels: ✍ chore: profile addition, small

#4030 Updated Search page UI
  components/Tag.js
  pages/discover.js
  pages/search.js
Labels: large

#4369 Update jmgrd98.json
  data/jmgrd98.json
Labels: ✍ chore: profile addition, medium, LGTM

#4322 Update ShivangShandilya.json
  data/ShivangShandilya.json
Labels: ✍ chore: profile addition, large, LGTM

#4368 added leetcode in links
  data/samarth8765.json
Labels: ✍ chore: profile addition, small, waiting-for-reviewers, LGTM

#4338 Malishkapandey patch 1
  data/malishkapandey.json
Labels: ✍ chore: profile addition, medium, LGTM

#4292 data:rajmaurya-dev
  data/rajmaurya-dev.json
Labels: ✍ chore: profile addition, medium, LGTM

#4364 dmprieto branch3
  data/dmprieto.json
Labels: ✍ chore: profile addition, small, LGTM

#4383 data: AtharvaRaut
  data/AtharvaRaut2002.json
Labels: ✍ chore: profile addition, large, LGTM

#4378 AtifShaik
  data/AtifShaik-47.json
Labels: ✍ chore: profile addition, medium, LGTM

#4381 feat: add @ sign for usernames in testimonials
  components/user/UserTestimonials.js
Labels: small

#4385 Update tobySolutions.json
  data/tobySolutions.json
Labels: ✍ chore: profile addition, small, LGTM

#4359 data: add 2002-harshit
  data/2002-harshit.json
Labels: ✍ chore: profile addition, medium, LGTM

#4216 Devanshukoli patch 1
  data/Devanshukoli.json
Labels: ✍ chore: profile addition, large, LGTM

#4387 Dynamically import icons
  components/Icon.js
Labels: medium

#4394 fix: missing icon #4393
  components/user/UserLink.js
Labels: small

#3250 data: jontstaz
  data/jontstaz.json
Labels: ✍ chore: profile addition, large, LGTM

#4375 Multi tag search
  components/Tag.js
  components/user/UserProfile.js
  pages/discover.js
  pages/search.js
  tests/profile.spec.js
Labels: large, tests

#4399 fix: change md to sm #4301
  pages/index.js
Labels: large

#4400 fixed tag trigger issue
  pages/index.js
  pages/search.js
Labels: small

#4404 data: himanshubalani
  data/himanshubalani.json
Labels: ✍ chore: profile addition, medium, LGTM

#4396 data: aadityadike
  data/aadityadike.json
Labels: ✍ chore: profile addition, large, LGTM

#4390 data: TusharKesarwani
  data/TusharKesarwani.json
Labels: ✍ chore: profile addition, medium, LGTM

#4398 Created ChiragKhatri.json
  data/chiragkhatri19.json
Labels: ✍ chore: profile addition, large, LGTM

#4388 Kordedekehine patch 3
  Kordedekehine.json
Labels: medium

#4407 fix: user links key
  components/user/UserLinks.js
Labels: small

#4409 Rename Kordedekehine.json to data/Kordedekehine.json
  data/Kordedekehine.json
Labels: ✍ chore: profile addition, small

#4389 Create Lavishmunjal.json
  data/Lavishmunjal.json
Labels: ✍ chore: profile addition, medium, LGTM

#4405 data:Chandupuram
  data/Chandupuram.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#4329 Add milestone mpotane.json #2 👣.
  data/mpotane.json
Labels: ✍ chore: profile addition, large, LGTM

#4412 Fixed the Icon on line 71 in my profile
  data/shubhsharma19.json
Labels: ✍ chore: profile addition, small, LGTM

#4414 Revert "feat: dynamically import icons (#4387)"
  components/Icon.js
Labels: medium

#4148 Feat: add quickstart video doc
  components/YoutubeVideo.js
  pages/docs/quickstart.mdx
Labels: medium

#4426 Docs youtube
  components/embeds/Youtube.js
  pages/docs/quickstart.mdx
Labels: medium

#4430 fix: triage label to features
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: small

#4372 Sachi goto patch 1 1
  data/SachiGoto.json
Labels: ✍ chore: profile addition, medium, LGTM

#4435 Re-implement dynamic icons import w/ error handling
  components/Icon.js
  tests/setup/global-setup.js
Labels: large, tests

#4436 Update tobySolutions.json
  data/tobySolutions.json
Labels: ✍ chore: profile addition, small, LGTM

#4433 data:philipcodes
  data/oyenolaphilipinc.json
Labels: ✍ chore: profile addition, medium, LGTM

#4410 data: vishnu-mouli-102408
  data/vishnu-mouli-102408.json
Labels: ✍ chore: profile addition, large, LGTM

#4441 Update profile
  data/loftwah.json
Labels: ✍ chore: profile addition, medium, LGTM

#4245 added outline to hamburger on tab
  components/navbar/Navbar.js
Labels: small

#4466 data: update AbbeyIT
  data/AbbeyIT.json
Labels: ✍ chore: profile addition, medium, LGTM

#4469 Update loftwah.json
  data/loftwah.json
Labels: ✍ chore: profile addition, small, LGTM

#4467 data:muhammedhasann
  data/muhammedhasann.json
Labels: ✍ chore: profile addition, medium, LGTM

#4464 adding one more testimonial to profile
  data/imran1509.json
Labels: ✍ chore: profile addition, small, LGTM

#4461 Update YashPimple.json
  data/YashPimple.json
Labels: ✍ chore: profile addition, small, LGTM

#4452 Added link to Twitter page
  data/CBID2.json
Labels: ✍ chore: profile addition, small, LGTM

#4474 data: Pradumnasaraf
  data/Pradumnasaraf.json
Labels: ✍ chore: profile addition, medium, LGTM

#4386 data: add ams0.json
  data/ams0.json
Labels: ✍ chore: profile addition, large, LGTM

#4437 Mpotane patch 1
  data/mpotane.json
Labels: ✍ chore: profile addition, medium, LGTM

#4413 DATA: Parsifal-M added event FOSDEM 2023
  data/Parsifal-M/events/2023-02-04-FOSDEM.json
Labels: ✍ chore: profile addition, medium

#4472 A pull request for my linkfree contribution
  data/Ewaaugustine.json
Labels: ✍ chore: profile addition, large, LGTM

#4471 Update SiddheshBangar.json
  data/SiddheshBangar.json
Labels: ✍ chore: profile addition, medium, LGTM

#4440 Reduce _app bundle size to improve load time
  components/Footer.js
  components/navbar/Navbar.js
Labels: medium

#4446 Create RohitGhumare.json
  data/rohitg00.json
Labels: ✍ chore: profile addition, large, LGTM

#4361 modified button to open link on next tab
  pages/index.js
Labels: small

#4315 Add a11y plugin for storybook
  .storybook/main.js
  .storybook/preview.js
  data/rohitg00.json
  package-lock.json
  package.json
  stories/components/user/UserCard.stories.js
  stories/components/user/UserLink.stories.js
  stories/pages/[username].stories.js
Labels: ✍ chore: profile addition, large, storybook

#4486 fix: package log
  package-lock.json
Labels: large

#4488 docs: number of ways to run project
  pages/docs/index.js
  pages/docs/quickstart.mdx
Labels: small

#4503 fix: issue template label
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
Labels: small

#4491 Updated bio
  data/YashPimple.json
Labels: ✍ chore: profile addition, medium, LGTM

#4489 data: VaishnavJois
  data/VaishnavJois.json
Labels: ✍ chore: profile addition, medium, LGTM

#4478 data:ikembakwem
  data/ikembakwem.json
Labels: ✍ chore: profile addition, medium, LGTM

#4450 data : priyanshu-11000
  data/priyanshu-11000.json
Labels: ✍ chore: profile addition, large, LGTM

#4459 Update priyankarpal.json
  data/priyankarpal.json
Labels: ✍ chore: profile addition, large, LGTM, kudos

#4454 data:rahul152-ai
  data/rahul152-ai.json
Labels: ✍ chore: profile addition, large, LGTM

#4495 Update baibhav-tiwari.json
  data/baibhav-tiwari.json
Labels: ✍ chore: profile addition, large, LGTM

#4515 Create 023-02-08-stateofopencon.json
  data/rohitg00/events/023-02-08-stateofopencon.json
Labels: ✍ chore: profile addition, medium

#4509 Fixed #4506
  components/layouts/DocsLayout.js
Labels: small

#4538 fix: do not run GH Action on fork #4537
  .github/workflows/deploy.yml
  .github/workflows/prettier.yml
  .github/workflows/release.yml
Labels: small

#4501 data: anthonrodgrs01
  data/anthonrodgrs01.json
Labels: ✍ chore: profile addition, medium, LGTM

#4542 Add robots.txt for SEO
  public/robots.txt
Labels: small

#4544 data: mohitparmar1
  data/mohitparmar1.json
Labels: ✍ chore: profile addition, medium, LGTM

#4494 data: sri-rishi
  data/sri-rishi.json
Labels: ✍ chore: profile addition, medium, LGTM

#4498 data:lakshmishreea122003
  data/lakshmishreea122003.json
Labels: ✍ chore: profile addition, medium, LGTM

#4522 Rohitg00 patch 1
  data/rohitg00/events/023-02-08-stateofopencon.json
Labels: ✍ chore: profile addition, small

#4483 update my bio and links
  data/shivam-sharma7.json
Labels: ✍ chore: profile addition, medium, LGTM

#4534 Bharat5604 patch 1
  data/bharat5604.json
Labels: ✍ chore: profile addition, medium, LGTM

#4520 data:Sandeep277
  data/Sandeep277.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#4540 data: vishal206
  data/vishal206.json
Labels: ✍ chore: profile addition, medium, LGTM

#4476 feat: debounce results
  pages/search.js
Labels: large

#4549 data: vishnu-mouli-102408
  data/vishnu-mouli-102408.json
Labels: ✍ chore: profile addition, medium, LGTM

#4548 Fix: renamed 'Community Events' to 'Events'
  components/navbar/Navbar.js
Labels: small

#4536 data: tplive
  data/tplive.json
Labels: ✍ chore: profile addition, medium, LGTM

#4528 data: deepanshu-rawat6
  data/deepanshu-rawat6.json
Labels: ✍ chore: profile addition, medium, LGTM

#4553 Update quickstart and editing doc to highlight maintainer reviews
  pages/docs/how-to-guides/editing.mdx
  pages/docs/quickstart.mdx
Labels: small

#4475 data: ShailavMalik
  data/ShailavMalik.json
Labels: ✍ chore: profile addition, large, LGTM

#4442 Create LinkFree profile for SavvasStephanides
  data/SavvasStephanides.json
Labels: ✍ chore: profile addition, medium, LGTM

#4468 data: mariamadeyemi
  data/mariamadeyemi.json
Labels: ✍ chore: profile addition, medium, LGTM

#4470 data: Anmol-Baranwal
  data/Anmol-Baranwal.json
Labels: ✍ chore: profile addition, large, LGTM

#4502 Anujkumarwebdev patch 1
  data/anujkumarwebdev.json
Labels: ✍ chore: profile addition, small, LGTM

#4505 data: foss2cyber
  data/foss2cyber.json
Labels: ✍ chore: profile addition, medium, LGTM

#4508 data:Taheer10
  data/Taheer10.json
Labels: ✍ chore: profile addition, medium, LGTM

#4511 data:abhiraj-ku
  data/abhiraj-ku.json
Labels: ✍ chore: profile addition, large, LGTM

#4513 ABHIGYAN-MOHANTA.json file added
  data/ABHIGYAN-MOHANTA.json
Labels: ✍ chore: profile addition, medium, LGTM

#4518 data: money8203
  data/money8203.json
Labels: ✍ chore: profile addition, medium, LGTM, kudos

#4519 data:Vikkybliz
  data/Vikkybliz.json
Labels: ✍ chore: profile addition, large, LGTM

#4521 search: Add randomize users on tag search.
  pages/search.js
Labels: small

#4561 chore: search code formatting
  pages/search.js
Labels: medium

#4448 Nav bar fix
  components/MDXComponentStyle.js
  components/layouts/DocsLayout.js
  next.config.mjs
  styles/onedark.css
Labels: 💻 aspect: code, 🛠 goal: fix, medium

#4564 Fix docs small screen
  components/layouts/DocsLayout.js
  components/mdx/ComponentStyle.js
  next.config.mjs
  styles/onedark.css
Labels: medium

#3893 added hover effects to the card
  components/user/UserCard.js
Labels: small

#4568 feat: hover effects to user card (#3893)
  components/user/UserCard.js
Labels: small

#4382 Navigation bar animation
  components/navbar/Navbar.js
Labels: small

#4299 data: viveksinra
  data/viveksinra.json
Labels: ✍ chore: profile addition, large, LGTM

#4527 Request for profile Create AbhiJain.json
  data/abhijain2003.json
Labels: ✍ chore: profile addition, medium, LGTM

#2910 data:atanda0x
  data/atanda0x.json
Labels: ✍ chore: profile addition, medium, LGTM

#3137 data:ksen21
  data/ksen21.json
Labels: ✍ chore: profile addition, medium, LGTM

#4572 Sara fix profiles
  data/atanda0x.json
  data/viveksinra.json
Labels: ✍ chore: profile addition, large

#4566 Storybook bugfix
  .storybook/main.js
  package-lock.json
  package.json
Labels: large

#4590 Run storybook workflow on config changes
  .github/workflows/storybook.yml
Labels: small

#4592 Fix storybook warning & deploy on dispatch
  .github/workflows/storybook.yml
  .storybook/main.js
Labels: small

#4596 Update tobySolutions.json
  data/tobySolutions.json
Labels: ✍ chore: profile addition, small, LGTM

#4477 data: Danny4life
  data/Danny4life.json
Labels: ✍ chore: profile addition, medium, LGTM

#4588 data : jennifer-pecky
  data/jennifer-pecky.json
Labels: ✍ chore: profile addition, medium, LGTM

#4577 data: davydocsurg
  data/davydocsurg.json
Labels: ✍ chore: profile addition, large, LGTM

#4597 data:ChinatuL
  data/ChinatuL.json
Labels: ✍ chore: profile addition, medium, LGTM

#4586 data: alek-v
  data/alek-v.json
Labels: ✍ chore: profile addition, large, LGTM

#4585 update oyenolaphilipinc.json
  data/oyenolaphilipinc.json
Labels: ✍ chore: profile addition, medium, LGTM

#4604 data:Shukla007
  data/Shukla007.json
  data/shukla007.json
Labels: ✍ chore: profile addition, large

#4587 data: iamravi1
  data/iamravi1.json
Labels: ✍ chore: profile addition

#4599 Update SandipPalit.json
  data/SandipPalit.json
Labels: ✍ chore: profile addition, large, LGTM

#4567 data:ritika728
  data/ritika728.json
Labels: ✍ chore: profile addition, medium, waiting-for-reviewers, LGTM

#4573 Added a more links and user.json
  data/singhmohit14072002.json
Labels: ✍ chore: profile addition, large, LGTM
