Repository EddieHubCommunity/BioDrop, pull requests merged in 2024-02, with the labels that each got.

#10206 fix: delete data/TobySolutions directory
  data/TobySolutions/testimonials/loftwah.json
Labels: invalid, ✍ chore: profile

#10202 Update paths-filter action version
  .github/workflows/vercel.yml
Labels: CI/CD

#10213 Update git-auto-commit-action to v5
  .github/workflows/prettier.yml
  .github/workflows/testimonial.yml
Labels: CI/CD

#10217 data: updates to links and milestones
  data/mikejw.json
Labels: invalid, ✍ chore: profile

#10179 Fix key attribute while showing links on statistics page
  pages/account/statistics/index.js
Labels: issue linked

#10224 Update kshitij9896.json
  data/kshitij9896.json
Labels: invalid, ✍ chore: profile

#10214 Docs(local-development guide): Add a step to local development using Docker
  pages/docs/environments/local-development.mdx
Labels: issue linked, 📖 docs

#10238 data: kiyoshi-87
  data/kiyoshi-87.json
Labels: invalid, ✍ chore: profile

#10244 Removed: data/mjr2595.json
  data/mjr2595.json
Labels: invalid, ✍ chore: profile
