Repository EddieHubCommunity/BioDrop, pull requests merged in 2024-06, with the labels that each got.

#9913 Closes #9707 - Keyboard Accesibility Issue with Icon Dropdown Fixed
  components/IconSearch.js
Labels: issue linked

#10032 feat: clear all tags in one click button added in search page
  pages/search.js
Labels: issue linked

#10115 feat: adds capability to export user qr-code into wallpaper
  components/user/QRcodeWallpaper.js
  components/user/UserProfile.js
  package-lock.json
  package.json
Labels: issue linked, dependencies

#10184 feat: avatar integration
  components/avatar/Avatar.js
  components/avatar/AvatarGroup.js
  components/avatar/UserAvatarGroup.js
  components/user/UserRepos.js
  services/github/getUserAvatar.js
Labels: issue linked

#10212 Switch playwright to github reporter on CI
  .github/workflows/build.yml
  playwright.config.js
Labels: CI/CD

#10220 Update dessant/label-actions to v4
  .github/workflows/issue-lock-unlock.yml
Labels: CI/CD

#10221 Fixes the issue realted to adding/ updating events tags not been saved and making form unsubmissive
  pages/account/manage/event/[[...data]].js
Labels: issue linked

#10227 Fix: 8824 Edit Icon Alignment fix in the links page.
  components/account/manage/Edit.js
  components/user/UserLink.js
  pages/account/manage/links.js
Labels: issue linked

#10276 Fix (9738): Prevent showing the initial state when changing query [search page]
  components/Loading.js
  pages/search.js
Labels: issue linked

#10315 fix: Manage profile page button is disabled while adding new tags
  pages/account/manage/profile.js
Labels: issue linked

#10324 Update Dependencies
  package-lock.json
  package.json
Labels: dependencies

#10339 update actions/labeler to Node 20 compatable version
  .github/workflows/labels.yml
Labels: CI/CD

#10355 feat: update navbar hover effect (#10305)
  components/navbar/Navbar.js
Labels: issue linked

#10357 fix: Navbar hidden when toggled on medium screen size
  components/navbar/Navbar.js
Labels: issue linked

#10381 actions/labelers version update
  .github/workflows/labels.yml
Labels: CI/CD

#9743 move premium check to middleware
  middleware.js
  pages/api/auth/[...nextauth].js
  tests/account/stats/location.spec.js
  tests/account/stats/referer.spec.js
Labels: tests, issue linked

#10208 Added animation in feature section
  hooks/useElementOnScreen.jsx
  pages/index.js
  tailwind.config.js
Labels: issue linked
