Repository EddieHubCommunity/BioDrop, pull requests merged in 2024-01, with the labels that each got.

#10070 data: uuvedant4
  data/uuvedant4.json
Labels: invalid, ✍ chore: profile

#10071 Created yobuir.json
  data/yobuir.json
Labels: invalid, ✍ chore: profile

#10074 data: Limebee
  data/Limebee.json
Labels: invalid, ✍ chore: profile

#10039 updated robert5313.json
  data/robert5313.json
Labels: invalid, ✍ chore: profile

#10085 Rename I-MirzaBaig.json to MiirzaBaig.json
  data/MiirzaBaig.json
Labels: invalid, ✍ chore: profile

#10086 data: Shukazuby
  data/Shukazuby.json
Labels: invalid, ✍ chore: profile

#10081 data: nnodim
  data/nnodim.json
Labels: invalid, ✍ chore: profile

#10089 data: Ousman37
  data/Ousman37.json
Labels: invalid, ✍ chore: profile

#10095 data: jonasermert
  data/jonasermert.json
Labels: invalid, ✍ chore: profile

#10097 fix: rolled back mongoose version
  package-lock.json
  package.json
Labels: dependencies

#10102 Handle Mongoose Validate error with try/catch
  package-lock.json
  package.json
  pages/api/account/manage/link/[[...data]].js
Labels: dependencies

#10100 data: lambeboluwatife
  data/lambeboluwatife.json
Labels: invalid, ✍ chore: profile

#9947 fix: update version location in bug.yml
  .github/ISSUE_TEMPLATE/bug.yml
Labels: issue linked, CI/CD

#10104 Update MiirzaBaig.json
  data/MiirzaBaig.json
Labels: invalid, ✍ chore: profile

#10107 Creating my BioDrop Profile
  data/ALIPHATICHYD.json
Labels: invalid, ✍ chore: profile

#10029 Update Gitpod images at docs environment #9734
  pages/docs/environments/gitpod.mdx
Labels: issue linked, 📖 docs

#10119 data: eugene4545
  data/eugene4545.json
Labels: invalid, ✍ chore: profile

#10120 fix: remove avatar & type keys from json files.
  data/Prashanth-bokkala.json
  data/gekkowrld.json
Labels: invalid, ✍ chore: profile

#9878 feat: group suggestions for users link
  components/GroupLinkSearch.js
  pages/account/manage/link/[[...data]].js
  pages/api/account/manage/link/[[...data]].js
Labels: issue linked

#10123 fix(docs-testimonial): Update Testimonial Addition Process
  pages/docs/how-to-guides/testimonials-json.mdx
Labels: issue linked, 📖 docs

#9889 fix: optimized event filtering
  components/event/EventTabs.js
  components/user/UserEvents.js
  pages/events.js
  services/utils/event/filterEvent.js
Labels: issue linked

#9713 Fixes(milestone): Multiple Milestone on spam clicking.
  pages/account/manage/event/[[...data]].js
  pages/account/manage/link/[[...data]].js
  pages/account/manage/milestone/[[...data]].js
  pages/account/manage/profile.js
  pages/account/manage/repos.js
Labels: issue linked

#10133 added more data into my profile
  data/ibilalkayy.json
Labels: invalid, ✍ chore: profile

#10134 added the business information in my profile
  data/ibilalkayy.json
Labels: invalid, ✍ chore: profile

#9943 No Space between add link and first link original pr #9822
  components/account/manage/Edit.js
Labels: issue linked

#9905 fix: add placeholder to select component on `account/onboarding` path
  components/Tabs.js
  components/form/Select.js
  components/navbar/SubNav.js
Labels: issue linked

#10137 update siddarth2810.json
  data/siddarth2810.json
Labels: invalid, ✍ chore: profile

#9972 Changed old twitter icon to X
  config/socials.js
Labels: issue linked

#10023 fix: secondary navbar overflow (#9891)
  components/Tabs.js
  components/navbar/Navbar.js
Labels: issue linked

#10158 data: Adarsh-619
  data/Adarsh-619.json
Labels: invalid, ✍ chore: profile

#9898 Fix: Icon dropdown shifts layout when suggestions are shown
  components/IconSearch.js
  pages/account/manage/link/[[...data]].js
  pages/account/manage/milestone/[[...data]].js
Labels: issue linked

#10169 Delete data/harisdev-netizen.json
  data/harisdev-netizen.json
Labels: invalid, ✍ chore: profile

#10171 Create Haru-hue.json
  data/Haru-hue.json
Labels: invalid, ✍ chore: profile

#10174 Create vemuladinesh25082002.json
  data/vemuladinesh25082002.json
Labels: invalid, ✍ chore: profile

#10176 Create WaqarTabish2807
  data/WaqarTabish2807.json
Labels: invalid, ✍ chore: profile

#10186 fix: show events select
  components/user/UserEvents.js
Labels: issue linked

#10188 fix(docs): Update Testimonial Issue Template Image
  pages/docs/how-to-guides/testimonials-json.mdx
Labels: issue linked, 📖 docs

#10196 data: shagunsharma6677
  data/shagunsharma6677.json
Labels: invalid, ✍ chore: profile

#10172 switch code highlighter to rehype-pretty-code
  next.config.mjs
  package-lock.json
  package.json
  pages/docs/full-profile-example.mdx
  pages/docs/how-to-guides/bio-json.mdx
  pages/docs/how-to-guides/events-json.mdx
  pages/docs/how-to-guides/links-json.mdx
  pages/docs/how-to-guides/milestones-json.mdx
  pages/docs/how-to-guides/socials-shortcuts-json.mdx
  pages/docs/how-to-guides/tags-json.mdx
  pages/docs/how-to-guides/testimonials-json.mdx
  pages/docs/quickstart-json.mdx
  styles/globals.css
Labels: dependencies, 📖 docs

#10201 data: Kevinkp09
  data/Kevinkp09.json
Labels: invalid, ✍ chore: profile
