Repository EddieHubCommunity/BioDrop, pull requests merged in 2024-03, with the labels that each got.

#10252 Update dushmanta05.json
  data/dushmanta05.json
Labels: invalid, ✍ chore: profile

#10232 Fixed the Issue #10203 - The icon drop-down suggestions are not visible properly
  components/IconSearch.js
Labels: issue linked

#10210 FIX : [BUG] groups field dropdown shift layout while suggestions are shown #10163
  components/GroupLinkSearch.js
  pages/account/manage/link/[[...data]].js
Labels: issue linked

#10254 Delete data/satkkeerthi.json
  data/satkkeerthi.json
Labels: invalid, ✍ chore: profile

#10260 Create Freedteck.json
  data/Freedteck.json
Labels: invalid, ✍ chore: profile

#10259 data: aniketkumar7
  data/aniketkumar7.json
Labels: invalid, ✍ chore: profile

#10262 Create alien1403.json
  data/alien1403.json
Labels: invalid, ✍ chore: profile

#10263 data: hariFED
  data/hariFED.json
Labels: invalid, ✍ chore: profile

#10256 fix: Typo in pages/icons.js
  pages/icons.js
Labels: issue linked

#10270 Add Priyanshu's profile information
  data/Priyanshu085.json
Labels: invalid, ✍ chore: profile

#10275 Added OlibhiaGhosh.json
  data/OlibhiaGhosh.json
Labels: invalid, ✍ chore: profile

#10277 data: Justice-Udehegbunam
  data/Justice-Udehegbunam.json
Labels: invalid, ✍ chore: profile

#10278 Data: MaorBemdoo
  data/MaorBemdoo.json
Labels: invalid, ✍ chore: profile

#10281 Add profile
  data/AashishKr27.json
Labels: invalid, ✍ chore: profile

#10283 Delete data/sharsha315.json file
  data/sharsha315.json
Labels: invalid, ✍ chore: profile

#10287 data :AzraNaseri
  data/AzraNaseri.json
Labels: invalid, ✍ chore: profile

#10273 Add rajesh.json
  data/rajeshj11.json
Labels: invalid, ✍ chore: profile

#10285 Add Aniket Botre's Profile json file and update package-lock.json file
  data/Aniket200-ind.json
Labels: invalid, ✍ chore: profile

#10296 data: ayodejiades
  data/ayodejiades.json
Labels: invalid, ✍ chore: profile

#10191 FIX : [BUG] No padding around 'Select a tab' label in mobile view #10150
  components/event/EventTabs.js
Labels: issue linked

#10294 Delete data/nickaldwin.json
  data/nickaldwin.json
Labels: invalid, ✍ chore: profile

#10298 Update nagaadshe1.json
  data/nagaadshe1.json
Labels: invalid, ✍ chore: profile

#10173 Use Flexbox to Improve Repos Page Header
  pages/repos.js
Labels: issue linked

#9912 Add the possibility to reorder the repositories
  components/user/UserRepos.js
  models/Profile/Repo.js
  pages/account/manage/repos.js
  pages/api/account/manage/repos.js
  pages/api/profiles/[username]/index.js
Labels: issue linked, models

#10301 data: SasankTanikella99
  data/SasankTanikella99.json
Labels: invalid, ✍ chore: profile

#10300 Delete data/jmgrd98.json
  data/jmgrd98.json
Labels: invalid, ✍ chore: profile

#10308 update dependencies
  .husky/pre-commit
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  stories/components/navbar/Navbar.stories
  stories/components/user/UserMilestone.stories.js
Labels: storybook, dependencies

#10310 revert husky to regular dependency
  package-lock.json
  package.json
Labels: dependencies

#10314 Update singh1203.json
  data/singh1203.json
Labels: invalid, ✍ chore: profile
